export const BASE_USER_REPOSITORY_IDENTIFIER = "BASE_USER_REPOSITORY";
export const UPLOAD_AVATAR_USECASE_IDENTIFIER = "UPLOAD_AVATAR_USECASE";
export const UPLOAD_AVATAR_CONTROLLER_IDENTIFIER = "UPLOAD_AVATAR_CONTROLLER";