export const BASE_USER_REPOSITORY_IDENTIFIER = "BASE_USER_REPOSITORY";
export const UPLOAD_AVATAR_USECASE_IDENTIFIER = "UPLOAD_AVATAR_USECASE";
export const UPLOAD_AVATAR_CONTROLLER_IDENTIFIER = "UPLOAD_AVATAR_CONTROLLER";
export const DNC_PARTICIPANT_REPOSITORY_IDENTIFIER = "DNC_PARTICIPANT_REPOSITORY";
export const REPOSITORY_FACTORY_IDENTIFIER = "REPOSITORY_FACTORY";
export const DNC_NOT_GRADE_SEEKING_PARTICIPANT_REPOSITORY_IDENTIFIER = "DNC_NOT_GRADE_SEEKING_PARTICIPANT_REPOSITORY";