export const enum AddHomeworkTranslationKeysEnum {
  ADD_HOMEWORK_BY_ADMIN_RESPONSE = "ADD_HOMEWORK_BY_ADMIN_RESPONSE",
  CLASS_NOT_FOUND = "CLASS_NOT_FOUND",
  SESSION_GIVEN_NOT_FOUND = "SESSION_GIVEN_NOT_FOUND",
  SESSION_TO_DO_NOT_FOUND = "SESSION_TO_DO_NOT_FOUND",
  GROUP_DOES_NOT_BELONG_TO_THIS_CLASS = "GROUP_DOES_NOT_BELONG_TO_THIS_CLASS",
  HOMEWORK_MUST_BE_RELATED_TO_TOPIC = "HOMEWORK_MUST_BE_RELATED_TO_TOPIC",
  SESSION_DOES_NOT_HAVE_TEACHER_ASSESS = "SESSION_DOES_NOT_HAVE_TEACHER_ASSESS",
  YOU_ARE_NOT_THE_OWNER_OF_THIS_SESSION = "YOU_ARE_NOT_THE_OWNER_OF_THIS_SESSION",
  SESSION_TO_DO_OR_SESSION_GIVEN_IN_NOT_FOR_A_SUBJECTTYPE_SESSION = "SESSION_TO_DO_OR_SESSION_GIVEN_IN_NOT_FOR_A_SUBJECTTYPE_SESSION",
  SESSION_TO_DO_OR_SESSION_GIVEN_IN_NOT_FOR_A_SUBSUBJECTTYPE_SESSION = "SESSION_TO_DO_OR_SESSION_GIVEN_IN_NOT_FOR_A_SUBSUBJECTTYPE_SESSION",
  SESSION_TO_DO_OR_SESSION_GIVEN_IN_NOT_FOR_A_GROUP_SESSION = "SESSION_TO_DO_OR_SESSION_GIVEN_IN_NOT_FOR_A_GROUP_SESSION",
  SESSION_TO_DO_OR_SESSION_GIVEN_IN_NOT_FOR_A_CLASS_SESSION = "SESSION_TO_DO_OR_SESSION_GIVEN_IN_NOT_FOR_A_CLASS_SESSION",
}

export const checkHomeworkOfErrorResponse = (topicType: string) => {
  return `SESSION_TO_DO_OR_SESSION_GIVEN_IN_NOT_FOR_A_${topicType.toUpperCase()}_SESSION`;
};

export const HOMEWORK_STATUS_ENUM = {
  TODO: "to do",
  DONE: "done",
} as const;
export type THomeworkStatusEnum = (typeof HOMEWORK_STATUS_ENUM)[keyof typeof HOMEWORK_STATUS_ENUM];
