export const enum UpdateHomeworkTranslationKeysEnum {
  UPDATE_HOMEWORK_RESPONSE = "UPDATE_HOMEWORK_RESPONSE",
  HOMEWORK_NOT_BELONG_TO_TEACHER = "HOMEWORK_NOT_BELONG_TO_TEACHER",
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_TO_DO_MUST_BE_IN_THE_FUTURE = "SESSION_TO_DO_MUST_BE_IN_THE_FUTURE",
}
