export const enum SharedScheduleManagementTranslationKeysEnum {
  CLASS_NOT_FOUND = "CLASS_NOT_FOUND",
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  STUDENT_NOT_FOUND = "STUDENT_NOT_FOUND",
  TEACHER_NOT_FOUND = "TEACHER_NOT_FOUND",
  SHARED_SCHEDULE_RESPONSE = "SHARED_SCHEDULE_RESPONSE",
}
