export const enum ValidateAndProcessSessionTranslationKeysEnum {
  INVALID_TEACHER = "INVALID_TEACHER",
  YOU_CAN_ONLY_START_THIS_SESSION_AFTER_THE_MINIMUM_SESSION_LAUNCH_TIME = "YOU_CAN_ONLY_START_THIS_SESSION_AFTER_THE_MINIMUM_SESSION_LAUNCH_TIME",
  SESSION_CANNOT_BE_LUNCHED = "SESSION_CANNOT_BE_LUNCHED",
  TEACHER_HAS_ALREADY_RUNNING_SESSION = "TEACHER_HAS_ALREADY_RUNNING_SESSION",
}
