export const enum DeleteSessionTranslationKeysEnum {
  DELETE_SESSION_RESPONSE = "DELETE_SESSION_RESPONSE",
  ONLY_PENDING_CANCELED_SESSION_CAN_BE_DELETED = "ONLY_PENDING_CANCELED_SESSION_CAN_BE_DELETED",
  TEACHER_OF_THIS_SESSION_ALREADY_PAID = "TEACHER_OF_THIS_SESSION_ALREADY_PAID",
}
