export const enum GetFutureSessionOfTeacherTranslationKeysEnum {
  GET_FUTURE_SESSION_OF_TEACHER_RESPONSE = "GET_FUTURE_SESSION_OF_TEACHER_RESPONSE",
  SUB_SUBJECT_TYPE_NOT_FOUND = "SUB_SUBJECT_TYPE_NOT_FOUND",
  SUBJECT_TYPE_NOT_FOUND = "SUBJECT_TYPE_NOT_FOUND",
}
