export const enum UpdateSessionStatusTranslationKeysEnum {
  UPDATE_SESSION_STATUS_RESPONSE = "UPDATE_SESSION_STATUS_RESPONSE",
  TEACHER_ALREADY_PAID_FOR_THE_SESSION = "TEACHER_ALREADY_PAID_FOR_THE_SESSION",
  SESSION_STATUS_CANNOT_BE_UPDATE_IT_TO_PENDING = "SESSION_STATUS_CANNOT_BE_UPDATE_IT_TO_PENDING",
  CANCELED_SESSION_ONLY_UPDATE_TO_PENDING = "CANCELED_SESSION_ONLY_UPDATE_TO_PENDING",
  CANNOT_CHANGE_STATUS_FROM_COMPLETED_TO_PENDING = "CANNOT_CHANGE_STATUS_FROM_COMPLETED_TO_PENDING",
  YOU_CANNOT_ONLY_CLOSE_THIS_SESSION_BEFORE_END_TIME = "YOU_CANNOT_ONLY_CLOSE_THIS_SESSION_BEFORE_END_TIME",
  SESSION_IS_ALREADY_COMPLETED = "SESSION_IS_ALREADY_COMPLETED",
}
