export const enum SaveFcmTokenTranslationKeysEnum {
  SAVE_FCM_TOKEN_RESPONSE = "SAVE_FCM_TOKEN_RESPONSE",
  USER_AGENT_MUST_BE_TRUTHY = "USER_AGENT_MUST_BE_TRUTHY",
  NOTIFICATION_SETTING_NOT_FOUND = "NOTIFICATION_SETTING_NOT_FOUND",
}
