export const enum UpdateNotificationSettingsTranslationKeysEnum {
  UPDATE_NOTIFICATION_SETTINGS_RESPONSE = "UPDATE_NOTIFICATION_SETTINGS_RESPONSE",
  USER_AGENT_MUST_BE_PROVIDED = "USER_AGENT_MUST_BE_PROVIDED",
}
