import "reflect-metadata";
import { GetChildAttendanceStatsUseCase } from "../../feature/parents/useCases/GetChildAttendanceStats.usecase";
import { GetTeacherDashboardUseCase } from "../../feature/dashboards/useCases/GetTeacherDashboard.usecase";
import { GetParentDashboardUseCase } from "../../feature/dashboards/useCases/GetParentDashboard.usecase";
import { GetStudentDashboardUseCase } from "../../feature/dashboards/useCases/GetStudentDashboard.usecase";
import { AdminApplicationService } from "./../../feature/admins/application/admin.application.service";
import { ClientSession, Connection } from "mongoose";
import { AdminRepo } from "../../feature/admins/domain/Admin.repo";
import { AddAdminUseCase } from "../../feature/admins/useCases/AddAdmin.usecase";
import { GetAdminByNewIdUseCase } from "../../feature/admins/useCases/GetAdminByNewId.usecase";
import { GetAdminDashboardUseCase } from "../../feature/dashboards/useCases/getAdminDashboard.usecase";
import { ListAdminsUseCase } from "../../feature/admins/useCases/ListAdmins.usecase";
import { UpdateAdminUseCase } from "../../feature/admins/useCases/UpdateAdmin.usecase";
import { ArchiveAdminUseCase } from "../../feature/archive/useCases/archiveAdmin.usecase";
import { ArchiveParentUseCase } from "../../feature/archive/useCases/archiveParent.usecase";
import { ArchiveStudentUseCase } from "../../feature/archive/useCases/archiveStudent.usecase";
import { ArchiveTeacherUseCase } from "../../feature/archive/useCases/archiveTeacher.usecase";
import { UnArchiveAdminUseCase } from "../../feature/archive/useCases/unarchiveAdmin.usecase";
import { UnArchiveParentUseCase } from "../../feature/archive/useCases/unarchiveParent.usecase";
import { UnArchiveStudentUseCase } from "../../feature/archive/useCases/unarchiveStudent.usecase";
import { UnArchiveTeacherUseCase } from "../../feature/archive/useCases/unarchiveTeacher.usecase";
import { VerificationCodeRepo } from "../../feature/authentication/domain/VerificationCode.repo";
import { ForgetPasswordUseCase } from "../../feature/authentication/useCases/ForgetPassowrd.usecase";
import { LoginUseCase } from "../../feature/authentication/useCases/Login.usecase";
import { LoginByMasterUseCase } from "../../feature/authentication/useCases/LoginByMaster.usecase";
import { LogoutUseCase } from "../../feature/authentication/useCases/Logout.usecase";
import { ResendInvitationUseCase } from "../../feature/authentication/useCases/ResendInvitation.usecase";
import { ResetPasswordUseCase } from "../../feature/authentication/useCases/ResetPassword.usecase";
import { ResetUserPasswordUseCase } from "../../feature/authentication/useCases/ResetUserPassword.usecase";
import { SwitchToUserUseCase } from "../../feature/authentication/useCases/SwitchToUser.usecase";
import { UpdateCurrentUserPasswordUseCase } from "../../feature/authentication/useCases/UpdateCurrentUserPassword.usecase";
import { VerifyCodeUseCase } from "../../feature/authentication/useCases/VerifyCode.usecase";
import { RoleRepo } from "../../feature/authorization/domain/Role.repo";
import { AddRoleUseCase } from "../../feature/authorization/useCases/AddRole.usecase";
import { DeleteRoleUseCase } from "../../feature/authorization/useCases/DeleteRole.usecase";
import { GetOneRoleUseCase } from "../../feature/authorization/useCases/GetOneRole.usecase";
import { ListRolesUseCase } from "../../feature/authorization/useCases/ListRoles.usecase";
import { UpdateRoleUseCase } from "../../feature/authorization/useCases/UpdateRole.usecase";
import { ClassRepo } from "../../feature/classes/domain/Class.repo";
import { ClassService } from "../../feature/classes/domain/Class.service";
import { ClassGroupRepo } from "../../feature/classes/domain/classGroup.repo";
import { AddClassUseCase } from "../../feature/classes/useCases/AddClass.usecase";
import { AssignStudentToClassUseCase } from "../../feature/classes/useCases/AssignStudentToClass.usecase";
import { AssignTeachersToSubjectsInClassUseCase } from "../../feature/classes/useCases/AssignTeacherToSubjectInClass.usecase";
import { AssignTeacherToSubSubjectInClassUseCase } from "../../feature/classes/useCases/AssignTeacherToSubSubjectInClass.usecase";
import { DeleteClassUseCase } from "../../feature/classes/useCases/DeleteClass.usecase";
import { GetClassDashboardUseCase } from "../../feature/classes/useCases/GetClassDashboard.usecase";
import { GetClassListUseCase } from "../../feature/classes/useCases/GetClassList.usecase";
import { GetClassOverviewUseCase } from "../../feature/classes/useCases/GetClassOverview.usecase";
import { GetGroupsOfClassUseCase } from "../../feature/classes/useCases/GetGroupsOfClass.usecase";
import { GetStudentsCodeBarePdfUseCase } from "../../feature/classes/useCases/GetStudentsCodeBarePdf.usecase";
import { GetStudentsOfClassUseCase } from "../../feature/classes/useCases/GetStudentsOfClass.usecase";
import { GetSubjectTypesOfClassUseCase } from "../../feature/classes/useCases/GetSubjectTypesOfClass.usecase";
import { GetSubjectsOfClassUseCase } from "../../feature/classes/useCases/GetSubjectsOfClass.usecase";
import { GetTeacherClassAndGroupsUseCase } from "../../feature/classes/useCases/GetTeacherClassAndGroups.usecase";
import { ListClassesUseCase } from "../../feature/classes/useCases/ListClasses.usecase";
import { ListClassesByTeacherUseCase } from "../../feature/classes/useCases/ListClassesByTeacher.usecase";
import { UnassignStudentFromClassUseCase } from "../../feature/classes/useCases/UnassignStudentFromClass.usecase";
import { UnAssignTeacherFromSubjectUseCase } from "../../feature/classes/useCases/UnAssignTeacherFromSubject.usecase";
import { UnAssignTeacherFromSubSubjectUseCase } from "../../feature/classes/useCases/UnAssignTeacherFromSubSubject.usecase";
import { UpdateClassUseCase } from "../../feature/classes/useCases/UpdateClass.usecase";
import { UpdateStudentGroupUseCase } from "../../feature/classes/useCases/UpdateStudentGroup.usecase";
import { ClassroomRepo } from "../../feature/classrooms/domains/classroom.repo";
import { AddClassroomUseCase } from "../../feature/classrooms/useCases/AddClassroom.usecase";
import { DeleteClassroomUseCase } from "../../feature/classrooms/useCases/DeleteClassroom.usecase";
import { GetAvailableClassroomUseCase } from "../../feature/classrooms/useCases/GetAvailableClassroom.usecase";
import { GetAvailableClassroomInWeeklySessionUseCase } from "../../feature/classrooms/useCases/GetAvailableClassroomInWeeklySession.usecase";
import { ListClassroomsUseCase } from "../../feature/classrooms/useCases/ListClassrooms.usecase";
import { UpdateClassroomUseCase } from "../../feature/classrooms/useCases/UpdateClassroom.usecase";
import { ClassTypeRepo } from "../../feature/classTypes/repo/ClassType.repo";
import { AddClassTypeUseCase } from "../../feature/classTypes/useCases/addClassTypes.usecase";
import { AddFieldToClasstypeUseCase } from "../../feature/classTypes/useCases/AddFieldToClasstype.usecase";
import { AddSubjectToClassTypeUseCase } from "../../feature/classTypes/useCases/AddSubjectToClassType.usecase";
import { AddSubSubjectToClassTypeUseCase } from "../../feature/classTypes/useCases/AddSubSubjectToClassType.usecase";
import { DeleteClassTypeUseCase } from "../../feature/classTypes/useCases/DeleteClassType.usecase";
import { DeleteFieldFromClassTypeUseCase } from "../../feature/classTypes/useCases/DeleteFieldFromClassType.usecase";
import { DeleteSubjectFromClassTypeUseCase } from "../../feature/classTypes/useCases/DeleteSubjectFromClassType.usecase";
import { DeleteSubSubjectFromClassTypeUseCase } from "../../feature/classTypes/useCases/DeleteSubSubjectFromClassType.usecase";
import { GetClassTypeUseCase } from "../../feature/classTypes/useCases/GetClassType.usecase";
import { GetFieldsOfClassTypeUseCase } from "../../feature/classTypes/useCases/GetFieldsOfClassTypes.usecase";
import { GetSubjectsOfClassTypesUseCase } from "../../feature/classTypes/useCases/GetSubjectsOfClassTypes.usecase";
import { ListClassTypeUseCase } from "../../feature/classTypes/useCases/ListClassTypes.usecase";
import { ListNextClassTypesUseCase } from "../../feature/classTypes/useCases/ListNextClassTypes.usecase";
import { ReorderFieldsOfClassTypesUseCase } from "../../feature/classTypes/useCases/ReorderFieldsOfClassType.usecase";
import { ReorderSubjectInClassTypeUseCase } from "../../feature/classTypes/useCases/ReorderSubjectInClassType.usecase";
import { ReorderSubSubjectInClassTypeUseCase } from "../../feature/classTypes/useCases/ReorderSubSubjectInClassType.usecase";
import { UpdateClassTypeUseCase } from "../../feature/classTypes/useCases/updateClassTypes.usecase";
import { UpdateFieldOfClassTypeUseCase } from "../../feature/classTypes/useCases/UpdateFieldOfClassType.usecase";
import { UpdateSubjectFromClassTypeUseCase } from "../../feature/classTypes/useCases/UpdateSubjectOfClassType.usecase";
import { UpdateSubSubjectOfClassTypeUseCase } from "../../feature/classTypes/useCases/UpdateSubSubjectOfClassType.usecase";
import { EmailManager } from "../../feature/emailManager/domain/EmailManager";
import { GroupRepo } from "../../feature/groupManagement/repos/Group.repo";
import { GroupTypeRepo } from "../../feature/groupManagement/repos/GroupType.repo";
import { DeleteGroupUseCase } from "../../feature/groupManagement/useCases/DeleteGroup.usecase";
import { GetGroupListUseCase } from "../../feature/groupManagement/useCases/GetGroupList.usecase";
import { GetGroupsOfStudentUseCase } from "../../feature/groupManagement/useCases/GetGroupsOfStudent.usecase";
import { UpdateGroupUseCase } from "../../feature/groupManagement/useCases/UpdateGroup.usecase";
import { UpdateGroupTeacherUseCase } from "../../feature/groupManagement/useCases/UpdateGroupTeacher.usecase";
import { AddGroupTypeUseCase } from "../../feature/groupType/useCases/AddGroupType.usecase";
import { DeleteGroupTypeUseCase } from "../../feature/groupType/useCases/DeleteGroupType.usecase";
import { ListGroupTypesUseCase } from "../../feature/groupType/useCases/ListGroupTypes.usecase";
import { UpdateGroupTypeUseCase } from "../../feature/groupType/useCases/UpdateGroupType.usecase";
import { LevelRepo } from "../../feature/levels/repos/Level.repo";
import { AddLevelUseCase } from "../../feature/levels/useCases/AddLevel.usecase";
import { DeleteLevelUseCase } from "../../feature/levels/useCases/DeleteLevel.usecase";
import { GetLevelsOverviewUseCase } from "../../feature/levels/useCases/GetLevelsOverview.usecase";
import { ReorderLevelsUseCase } from "../../feature/levels/useCases/ReorderLevels.usecase";
import { UpdateLevelUseCase } from "../../feature/levels/useCases/UpdateLevel.usecase";
import { AppVersionRepo } from "../../feature/masters/domain/AppVersion.repo";
import { MasterRepo } from "../../feature/masters/domain/Master.repo";
import { AddMasterUseCase } from "../../feature/masters/useCases/AddMaster.usecase";
import { DeleteMasterUseCase } from "../../feature/masters/useCases/DeleteMaster.usecase";
import { ListMastersUseCase } from "../../feature/masters/useCases/ListMasters.usecase";
import { UpdateMasterUseCase } from "../../feature/masters/useCases/UpdateMaster.usecase";
import { ConversationRepo } from "../../feature/messages/domain/Conversation.repo";
import { MessageRepo } from "../../feature/messages/domain/Message.repo";
import { MessageAttachmentRepo } from "../../feature/messages/domain/MessageAttachment.repo";
import { MessageLinksRepo } from "../../feature/messages/domain/MessageLinks.repo";
import { AddMessageUseCase } from "../../feature/messages/useCases/AddMessage.usecase";
import { GetMessageReactionsUseCase } from "../../feature/messages/useCases/GetMessageReactions.usercase";
import { ListConversationParticipantsUseCase } from "../../feature/messages/useCases/ListConversationParticipants.usecase";
import { ListConversationsUseCase } from "../../feature/messages/useCases/ListConversations.usecase";
import { ReactToMessageUseCase } from "../../feature/messages/useCases/ReactToMessage.usecase";
import { NotificationRepo } from "../../feature/notifications/Notification.repo";
import { NotificationSettingsRepo } from "../../feature/notifications/NotificationSettings.repo";
import { NotificationSettingsService } from "../../feature/notifications/NotificationSettings.service";
import { ParentRepo } from "../../feature/parents/domain/Parent.repo";
import { AddParentUseCase } from "../../feature/parents/useCases/AddParent.usecase";
import { GetChildrenOfParentUseCase } from "../../feature/parents/useCases/GetChildrenOfParent.usecase";
import { GetParentByNewIdUseCase } from "../../feature/parents/useCases/GetParentByNewId.usecase";
import { ListParentsUseCase } from "../../feature/parents/useCases/ListParents.usecase";
import { UpdateParentUseCase } from "../../feature/parents/useCases/UpdateParent.usecase";
import { ScheduleApplicationService } from "../../feature/schedules/applications/Schedule.application.service";
import { ApplyWeeklyScheduleForClassUseCase } from "../../feature/schedules/useCases/ApplyWeeklyScheduleForClass.usecase";
import { DeleteSessionUseCase } from "../../feature/schedules/useCases/DeleteSession.usecase";
import { GetEntityScheduleUseCase } from "../../feature/schedules/useCases/GetEntitySchedule.usecase";
import { GetScheduleUseCase } from "../../feature/schedules/useCases/GetSchedule.usecase";
import { SchoolRepo } from "../../feature/schools/domain/School.repo";
import { SmsSoldHistoryRepo } from "../../feature/schools/domain/SmsSoldHistory.repo";
import { AddSchoolUseCase } from "../../feature/schools/useCases/AddSchool.usecase";
import { GetSchoolDetailsUseCase } from "../../feature/schools/useCases/GetSchoolInformation.usecase";
import { ListSchoolsUseCase } from "../../feature/schools/useCases/ListSchools.usecase";
import { SwitchToSchoolUsecase } from "../../feature/schools/useCases/SwitchToSchool.usecase";
import { UpdateFlagsUseCase } from "../../feature/schools/useCases/UpdateFlags.usecase";
import { UpdateSchoolUseCase } from "../../feature/schools/useCases/UpdateSchool.usecase";
import { UpdateSmsSoldUseCase } from "../../feature/schools/useCases/UpdateSmsSold.usecase";
import { SchoolYearRepo } from "../../feature/schoolYears/domain/SchoolYear.repo";
import { AddSchoolYearUseCase } from "../../feature/schoolYears/useCases/AddSchoolYear.usecase";
import { ListSchoolYearUseCase } from "../../feature/schoolYears/useCases/ListSchoolYear.usecase";
import { UpdateSchoolYearUseCase } from "../../feature/schoolYears/useCases/UpdateSchoolYear.usecase";
import { SessionApplicationService } from "../../feature/sessionManagement/applicationServices/Session.application.service";
import { SessionRepo } from "../../feature/sessionManagement/domain/Session.repo";
import { SessionService } from "../../feature/sessionManagement/domain/Session.service";
import { AddSessionForClassUseCase } from "../../feature/sessionManagement/useCases/AddSessionForClass.usecase";
import { AddSessionForGroupUseCase } from "../../feature/sessionManagement/useCases/AddSessionForGroup.usecase";
import { GetSessionDetailsUseCase } from "../../feature/sessionManagement/useCases/getSessionDetails.usecase";
import { UpdateSessionDetailsUseCase } from "../../feature/sessionManagement/useCases/updateSessionDetails.usecase";
import { UpdateSessionForClassUseCase } from "../../feature/sessionManagement/useCases/UpdateSessionForClass.usecase";
import { UpdateSessionForGroupUseCase } from "../../feature/sessionManagement/useCases/UpdateSessionForGroup.usecase";
import { SessionTypeRepo } from "../../feature/sessionTypes/repos/SessionType.repo";
import { AddSessionTypeUseCase } from "../../feature/sessionTypes/usecases/AddSessionType.usecase";
import { DeleteSessionTypeUseCase } from "../../feature/sessionTypes/usecases/DeleteSessionType.usecase";
import { ListSessionTypeUseCase } from "../../feature/sessionTypes/usecases/ListSessionType.usecase";
import { UpdateSessionTypeUseCase } from "../../feature/sessionTypes/usecases/UpdateSessionType.usecase";
import { SmsManager } from "../../feature/smsManager/domain/SmsManager";
import { StudentApplicationService } from "../../feature/students/application/Student.application.service";
import { StudentRepo } from "../../feature/students/domain/Student.repo";
import { StudentProfileRepo } from "../../feature/students/domain/StudentProfile.repo";
import { AddStudentUseCase } from "../../feature/students/useCases/AddStudent.usecase";
import { GetStudentAttendanceCertificateUseCase } from "../../feature/students/useCases/GetStudentAttendanceCertificate.usecase";
import { GetStudentProfileUseCase } from "../../feature/students/useCases/GetStudentProfile.usecase";
import { ImportStudentsUseCase } from "../../feature/students/useCases/ImportStudents.usecase";
import { ToggleUserActivationUseCase } from "../../feature/students/useCases/ToggleUserActivation.usecase";
import { UpdateStudentUseCase } from "../../feature/students/useCases/UpdateStudent.usecase";
import { SubjectTypeRepo } from "../../feature/subjectTypes/domains/SubjectType.repo";
import { AddSubjectTypeUseCase } from "../../feature/subjectTypes/useCases/AddSubjectType.usecase";
import { DeleteSubjectTypeUseCase } from "../../feature/subjectTypes/useCases/DeleteSubjectType.usecase";
import { UpdateSubjectTypeUseCase } from "../../feature/subjectTypes/useCases/UpdateSubjectType.usecase";
import { SubLevelRepo } from "../../feature/subLevels/domains/SubLevel.repo";
import { AddSubLevelUseCase } from "../../feature/subLevels/useCases/AddSubLevel.usecase";
import { DeleteSubLevelUseCase } from "../../feature/subLevels/useCases/DeleteSubLevel.usecase";
import { ReorderSubLevelsUseCase } from "../../feature/subLevels/useCases/ReorderSubLevels.usecase";
import { UpdateSubLevelUseCase } from "../../feature/subLevels/useCases/UpdateSubLevel.usecase";
import { SubSubjectTypesRepo } from "../../feature/subSubjectTypes/repos/SubSubjectTypes.repo";
import { AddSubSubjectTypeUseCase } from "../../feature/subSubjectTypes/usecases/AddSubSubjectType.usecase";
import { DeleteSubSubjectTypeUseCase } from "../../feature/subSubjectTypes/usecases/DeleteSubSubjectType.usecase";
import { ListSubSubjectTypeUseCase } from "../../feature/subSubjectTypes/usecases/ListSubSubjectType.usecase";
import { UpdateSubSubjectTypeUsecase } from "../../feature/subSubjectTypes/usecases/UpdateSubSubjectType.usecase";
import { TeacherRepo } from "../../feature/teachers/domain/Teacher.repo";
import { TeacherProfileRepo } from "../../feature/teachers/domain/TeacherProfile.repo";
import { AddTeacherUseCase } from "../../feature/teachers/useCases/AddTeacher.usecase";
import { GetTeacherProfileUsecase } from "../../feature/teachers/useCases/GetTeacherProfile.usecase";
import { GetTeachersOfStudentUseCase } from "../../feature/teachers/useCases/GetTeachersOfStudent.usecase";
import { ListTeachersUseCase } from "../../feature/teachers/useCases/ListTeachers.usecase";
import { UpdateTeacherUseCase } from "../../feature/teachers/useCases/UpdateTeacher.usecase";
import { UsersRepo } from "../../feature/users/domain/user.repo";
import { UploadAvatarUseCase } from "../../feature/users/useCases/UploadAvatar.usecase";
import { WeeklyScheduleApplicationService } from "../../feature/weeklySchedule/applications/WeeklySchedule.application.service";
import { GetDraftWeeklyScheduleUseCase } from "../../feature/weeklySchedule/useCases/GetDraftWeeklySchedule.usecase";
import { GetNonDraftWeeklyScheduleUseCase } from "../../feature/weeklySchedule/useCases/GetNonDraftWeeklySchedule.usecase";
import { WeeklySessionApplicationService } from "../../feature/weeklySessions/applicationService/WeeklySession.application.service";
import { WeeklySessionRepo } from "../../feature/weeklySessions/repos/WeeklySession.repo";
import { AddWeeklySessionForClassUseCase } from "../../feature/weeklySessions/useCases/AddWeeklySessionForClass.usecase";
import { AddWeeklySessionForGroupUseCase } from "../../feature/weeklySessions/useCases/AddWeeklySessionForGroup.usecase";
import { DeleteWeeklySessionUseCase } from "../../feature/weeklySessions/useCases/DeleteWeeklySession.usecase";
import { UpdateWeeklySessionForClassUseCase } from "../../feature/weeklySessions/useCases/UpdateWeeklySessionForClass.usecase";
import { UpdateWeeklySessionForGroupUseCase } from "../../feature/weeklySessions/useCases/UpdateWeeklySessionForGroup.usecase";
import { RandomUtils } from "../../helpers/RandomUtils";
import { StringUtils } from "../../helpers/StringUtils";
import { TLanguageEnum } from "../../translation/constants";
import { EventDispatcher } from "../domainEvents/EventDispatcher";
import { HandlerSubscriber } from "../domainEvents/HandlerSubscriber";
import { FileManager } from "../fileManager/FileManager";
import { GroupApplicationService } from "./../../feature/groupManagement/applicationServices/Group.application.service";
import { AddGroupUseCase } from "./../../feature/groupManagement/useCases/AddGroup.usecase";
import { AssignStudentToGroupUseCase } from "./../../feature/groupManagement/useCases/AssignStudentToGroup.usecase";
import { CheckGroupUseCase } from "./../../feature/groupManagement/useCases/CheckGroup.usecase";
import { GetGroupsOfTeacherUseCase } from "./../../feature/groupManagement/useCases/GetGroupsOfTeacher.usecase";
import { GetStudentsOfGroupUseCase } from "./../../feature/groupManagement/useCases/GetStudentsOfGroup.usecase";
import { GetGroupOverviewUseCase } from "./../../feature/groupManagement/useCases/GroupOverview.usecase";
import { ListTeacherGroupUseCase } from "./../../feature/groupManagement/useCases/ListTeacherGroup.usecase";
import { ListUnenrolledStudentsForGroupUseCase } from "./../../feature/groupManagement/useCases/ListUnenrolledStudentsForGroup.usecase";
import { UnassignStudentFromGroupUseCase } from "./../../feature/groupManagement/useCases/UnassignStudentFromGroup.usecase";
import { GetAppVersionUseCase } from "./../../feature/masters/useCases/getAllAppsVersion.usecase";
import { UpdateAppVersionUseCase } from "./../../feature/masters/useCases/updateOsVersion.usecase";
import { AddDirectConversationUseCase } from "./../../feature/messages/useCases/AddDirectConversation.usecase";
import { AddGroupConversationUseCase } from "./../../feature/messages/useCases/AddGroupConversation.usecase";
import { AddParticipantsToConversationUseCase } from "./../../feature/messages/useCases/AddParticipantsToConversation.usecase";
import { DeleteMessageUseCase } from "./../../feature/messages/useCases/DeleteMessage.usecase";
import { GetConversationUseCase } from "./../../feature/messages/useCases/getConversation.usecase";
import { ListConversationAttachmentsUseCase } from "./../../feature/messages/useCases/ListConversationAttachments.usecase";
import { ListConversationLinksUseCase } from "./../../feature/messages/useCases/ListConversationLinks.usecase";
import { ListConversationMessagesUseCase } from "./../../feature/messages/useCases/ListConversationMessages.usecase";
import { ListConversationMultimediaUseCase } from "./../../feature/messages/useCases/ListConversationMultimedia.usecase";
import { FindUsersByFullNameUseCase } from "./../../feature/messages/useCases/ListTargetUsers.usecase";
import { ListTargetUsersForGroupConversationAssignmentUseCase } from "./../../feature/messages/useCases/ListTargetUsersForGroupConversationAssignment.usecase";
import { RemoveParticipantsFromConversationUseCase } from "./../../feature/messages/useCases/RemoveParticipantsFromConversation.usecase";
import { UpdateConversationNameUseCase } from "./../../feature/messages/useCases/UpdateConversationName.usecase";
import { UpdateConversationSeenStatusUseCase } from "./../../feature/messages/useCases/UpdateConversationSeenStatus.usecase";
import { ApplyWeeklyScheduleForGroupUseCase } from "./../../feature/schedules/useCases/ApplyWeeklyScheduleForGroup.usecase";
import { School } from "./../../feature/schools/domain/school.entity";
import { CancelSessionUseCase } from "./../../feature/sessionManagement/useCases/cancelSession.usecase";
import { CloseSessionUseCase } from "./../../feature/sessionManagement/useCases/closeSession.usecase";
import { ConfirmAttendanceUseCase } from "./../../feature/sessionManagement/useCases/confirmAttendance.usecase";
import { StartSessionUseCase } from "./../../feature/sessionManagement/useCases/startSession.usecase";
import { UpdateSessionStatusUseCase } from "./../../feature/sessionManagement/useCases/updateSessionStatus.usecase";
import { VerifyAndFetchUsersUseCase } from "./../../feature/users/useCases/verifyUsersExistence.usecase";
import { SwitchStudentsClassUseCase } from "../../feature/students/useCases/switchStudentsClass.usecase";
import { ListStudentsUseCase } from "../../feature/students/useCases/ListStudents.usecase";

export type containerRegistry = {
  //core
  EmailManager: EmailManager;
  FileManager: FileManager;
  SmsManager: SmsManager;
  RandomUtils: typeof RandomUtils;
  StringUtils: typeof StringUtils;
  Language: TLanguageEnum;
  EventDispatcher: EventDispatcher;
  HandlerSubscriber: HandlerSubscriber;

  // use cases

  GetChildAttendanceStatsUseCase: GetChildAttendanceStatsUseCase;
  ListStudentsUseCase: ListStudentsUseCase;
  SwitchStudentsClassUseCase: SwitchStudentsClassUseCase;
  GetTeacherDashboardUseCase: GetTeacherDashboardUseCase;
  GetParentDashboardUseCase: GetParentDashboardUseCase;
  GetStudentDashboardUseCase: GetStudentDashboardUseCase;
  GetAdminDashboardUseCase: GetAdminDashboardUseCase;
  GetTeachersOfStudentUseCase: GetTeachersOfStudentUseCase;
  GetSubjectTypesOfClassUseCase: GetSubjectTypesOfClassUseCase;
  GetGroupsOfStudentUseCase: GetGroupsOfStudentUseCase;
  UnAssignTeacherFromSubSubjectUseCase: UnAssignTeacherFromSubSubjectUseCase;
  UnAssignTeacherFromSubjectUseCase: UnAssignTeacherFromSubjectUseCase;
  AssignTeacherToSubSubjectInClassUseCase: AssignTeacherToSubSubjectInClassUseCase;
  UnassignStudentFromClassUseCase: UnassignStudentFromClassUseCase;
  GetSubjectsOfClassUseCase: GetSubjectsOfClassUseCase;
  UpdateStudentGroupUseCase: UpdateStudentGroupUseCase;
  AddSessionForGroupUseCase: AddSessionForGroupUseCase;
  UpdateSessionForGroupUseCase: UpdateSessionForGroupUseCase;
  AddWeeklySessionForGroupUseCase: AddWeeklySessionForGroupUseCase;
  UpdateGroupTypeUseCase: UpdateGroupTypeUseCase;
  GetGroupsOfTeacherUseCase: GetGroupsOfTeacherUseCase;
  GetTeacherClassAndGroupsUseCase: GetTeacherClassAndGroupsUseCase;
  GetStudentsCodeBarePdfUseCase: GetStudentsCodeBarePdfUseCase;
  GetClassListUseCase: GetClassListUseCase;
  AddGroupTypeUseCase: AddGroupTypeUseCase;
  GetClassDashboardUseCase: GetClassDashboardUseCase;
  AssignStudentToClassUseCase: AssignStudentToClassUseCase;
  ListGroupTypesUseCase: ListGroupTypesUseCase;
  DeleteGroupTypeUseCase: DeleteGroupTypeUseCase;
  ListClassroomsUseCase: ListClassroomsUseCase;
  UpdateGroupTeacherUseCase: UpdateGroupTeacherUseCase;
  DeleteGroupUseCase: DeleteGroupUseCase;
  UpdateGroupUseCase: UpdateGroupUseCase;
  ListUnenrolledStudentsForGroupUseCase: ListUnenrolledStudentsForGroupUseCase;
  GetGroupListUseCase: GetGroupListUseCase;
  AddGroupUseCase: AddGroupUseCase;
  ApplyWeeklyScheduleForGroupUseCase: ApplyWeeklyScheduleForGroupUseCase;
  CheckGroupUseCase: CheckGroupUseCase;
  AssignStudentToGroupUseCase: AssignStudentToGroupUseCase;
  UpdateWeeklySessionForGroupUseCase: UpdateWeeklySessionForGroupUseCase;
  UnassignStudentFromGroupUseCase: UnassignStudentFromGroupUseCase;
  GetLevelsOverviewUseCase: GetLevelsOverviewUseCase;
  AssignTeachersToSubjectsInClassUseCase: AssignTeachersToSubjectsInClassUseCase;
  AddClassUseCase: AddClassUseCase;
  ResetUserPasswordUseCase: ResetUserPasswordUseCase;
  ListTeachersUseCase: ListTeachersUseCase;
  GetStudentAttendanceCertificateUseCase: GetStudentAttendanceCertificateUseCase;
  GetChildrenOfParentUseCase: GetChildrenOfParentUseCase;
  GetAdminByNewIdUseCase: GetAdminByNewIdUseCase;
  ListAdminsUseCase: ListAdminsUseCase;
  GetParentByNewIdUseCase: GetParentByNewIdUseCase;
  ListParentsUseCase: ListParentsUseCase;
  ToggleUserActivationUseCase: ToggleUserActivationUseCase;
  LoginByMasterUseCase: LoginByMasterUseCase;
  LoginUseCase: LoginUseCase;
  LogoutUseCase: LogoutUseCase;
  ResetPasswordUseCase: ResetPasswordUseCase;
  VerifyCodeUseCase: VerifyCodeUseCase;
  ForgetPasswordUseCase: ForgetPasswordUseCase;
  UpdateCurrentUserPasswordUseCase: UpdateCurrentUserPasswordUseCase;
  AddWeeklySessionForClassUseCase: AddWeeklySessionForClassUseCase;
  UpdateWeeklySessionForClassUseCase: UpdateWeeklySessionForClassUseCase;
  AddSessionForClassUseCase: AddSessionForClassUseCase;
  UpdateSessionForClassUseCase: UpdateSessionForClassUseCase;
  ApplyWeeklyScheduleForClassUseCase: ApplyWeeklyScheduleForClassUseCase;
  DeleteWeeklySessionUseCase: DeleteWeeklySessionUseCase;
  GetAvailableClassroomUseCase: GetAvailableClassroomUseCase;
  GetAvailableClassroomInWeeklySessionUseCase: GetAvailableClassroomInWeeklySessionUseCase;
  GetEntityScheduleUseCase: GetEntityScheduleUseCase;
  DeleteSessionUseCase: DeleteSessionUseCase;
  UploadAvatarUseCase: UploadAvatarUseCase;
  GetDraftWeeklyScheduleUseCase: GetDraftWeeklyScheduleUseCase;
  GetNonDraftWeeklyScheduleUseCase: GetNonDraftWeeklyScheduleUseCase;
  GetScheduleUseCase: GetScheduleUseCase;
  ImportStudentsUseCase: ImportStudentsUseCase;
  AddTeacherUseCase: AddTeacherUseCase;
  AddParentUseCase: AddParentUseCase;
  AddAdminUseCase: AddAdminUseCase;
  AddStudentUseCase: AddStudentUseCase;
  GetClassTypeUseCase: GetClassTypeUseCase;
  ListSessionTypeUseCase: ListSessionTypeUseCase;
  UpdateSchoolYearUseCase: UpdateSchoolYearUseCase;
  AddSchoolYearUseCase: AddSchoolYearUseCase;
  ReorderSubLevelsUseCase: ReorderSubLevelsUseCase;
  DeleteClassroomUseCase: DeleteClassroomUseCase;
  UpdateClassroomUseCase: UpdateClassroomUseCase;
  GetStudentsOfGroupUseCase: GetStudentsOfGroupUseCase;
  GetGroupsOfClassUseCase: GetGroupsOfClassUseCase;
  GetStudentsOfClassUseCase: GetStudentsOfClassUseCase;
  ReorderLevelsUseCase: ReorderLevelsUseCase;
  AddClassroomUseCase: AddClassroomUseCase;
  DeleteSessionTypeUseCase: DeleteSessionTypeUseCase;
  UpdateSessionTypeUseCase: UpdateSessionTypeUseCase;
  AddSessionTypeUseCase: AddSessionTypeUseCase;
  DeleteSubSubjectTypeUseCase: DeleteSubSubjectTypeUseCase;
  UpdateClassUseCase: UpdateClassUseCase;
  DeleteClassUseCase: DeleteClassUseCase;
  GetSessionDetailsUseCase: GetSessionDetailsUseCase;
  AddMessageUseCase: AddMessageUseCase;
  ListConversationsUseCase: ListConversationsUseCase;
  ListConversationMessagesUseCase: ListConversationMessagesUseCase;
  ListConversationLinksUseCase: ListConversationLinksUseCase;
  ListConversationAttachmentsUseCase: ListConversationAttachmentsUseCase;
  ListConversationMultimediaUseCase: ListConversationMultimediaUseCase;
  AddDirectConversationUseCase: AddDirectConversationUseCase;
  ReactToMessageUseCase: ReactToMessageUseCase;
  VerifyAndFetchUsersUseCase: VerifyAndFetchUsersUseCase;
  FindUsersByFullNameUseCase: FindUsersByFullNameUseCase;
  GetConversationUseCase: GetConversationUseCase;
  ListClassTypeUseCase: ListClassTypeUseCase;
  UpdateClassTypeUseCase: UpdateClassTypeUseCase;
  AddClassTypeUseCase: AddClassTypeUseCase;
  GetSubjectsOfClassTypesUseCase: GetSubjectsOfClassTypesUseCase;
  GetFieldsOfClassTypeUseCase: GetFieldsOfClassTypeUseCase;
  ReorderSubjectInClassTypeUseCase: ReorderSubjectInClassTypeUseCase;
  ReorderSubSubjectInClassTypeUseCase: ReorderSubSubjectInClassTypeUseCase;
  ReorderFieldsOfClassTypesUseCase: ReorderFieldsOfClassTypesUseCase;
  AddSubjectToClassTypeUseCase: AddSubjectToClassTypeUseCase;
  AddSubSubjectToClassTypeUseCase: AddSubSubjectToClassTypeUseCase;
  ListNextClassTypesUseCase: ListNextClassTypesUseCase;
  AddFieldToClasstypeUseCase: AddFieldToClasstypeUseCase;
  ListMastersUseCase: ListMastersUseCase;
  ListTargetUsersForGroupConversationAssignmentUseCase: ListTargetUsersForGroupConversationAssignmentUseCase;
  DeleteMessageUseCase: DeleteMessageUseCase;
  DeleteClassTypeUseCase: DeleteClassTypeUseCase;
  DeleteFieldFromClassTypeUseCase: DeleteFieldFromClassTypeUseCase;
  UpdateSubjectFromClassTypeUseCase: UpdateSubjectFromClassTypeUseCase;
  UpdateFieldOfClassTypeUseCase: UpdateFieldOfClassTypeUseCase;
  DeleteLevelUseCase: DeleteLevelUseCase;
  ListRolesUseCase: ListRolesUseCase;
  AddRoleUseCase: AddRoleUseCase;
  UpdateRoleUseCase: UpdateRoleUseCase;
  ConfirmAttendanceUseCase: ConfirmAttendanceUseCase;
  UpdateSubSubjectTypeUsecase: UpdateSubSubjectTypeUsecase;
  AddMasterUseCase: AddMasterUseCase;
  CloseSessionUseCase: CloseSessionUseCase;
  ListSchoolYearUseCase: ListSchoolYearUseCase;
  AddSchoolUseCase: AddSchoolUseCase;
  UpdateSchoolUseCase: UpdateSchoolUseCase;
  ListTeacherGroupUseCase: ListTeacherGroupUseCase;
  UpdateFlagsUseCase: UpdateFlagsUseCase;
  SwitchToSchoolUsecase: SwitchToSchoolUsecase;
  CancelSessionUseCase: CancelSessionUseCase;
  StartSessionUseCase: StartSessionUseCase;
  GetSchoolDetailsUseCase: GetSchoolDetailsUseCase;
  //services
  NotificationSettingsService: NotificationSettingsService;
  SessionService: SessionService;
  ClassService: ClassService;
  AddGroupConversationUseCase: AddGroupConversationUseCase;
  AddParticipantsToConversationUseCase: AddParticipantsToConversationUseCase;
  RemoveParticipantsFromConversationUseCase: RemoveParticipantsFromConversationUseCase;
  UpdateConversationNameUseCase: UpdateConversationNameUseCase;
  UpdateConversationSeenStatusUseCase: UpdateConversationSeenStatusUseCase;
  ListConversationParticipantsUseCase: ListConversationParticipantsUseCase;
  GetMessageReactionsUseCase: GetMessageReactionsUseCase;
  UpdateSubSubjectOfClassTypeUseCase: UpdateSubSubjectOfClassTypeUseCase;
  ListSubSubjectTypeUseCase: ListSubSubjectTypeUseCase;
  AddLevelUseCase: AddLevelUseCase;
  UpdateLevelUseCase: UpdateLevelUseCase;
  DeleteSubjectFromClassTypeUseCase: DeleteSubjectFromClassTypeUseCase;
  DeleteSubSubjectFromClassTypeUseCase: DeleteSubSubjectFromClassTypeUseCase;
  AddSubLevelUseCase: AddSubLevelUseCase;
  UpdateSubLevelUseCase: UpdateSubLevelUseCase;
  DeleteSubLevelUseCase: DeleteSubLevelUseCase;
  GetOneRoleUseCase: GetOneRoleUseCase;
  DeleteRoleUseCase: DeleteRoleUseCase;
  AddSubjectTypeUseCase: AddSubjectTypeUseCase;
  UpdateSubjectTypeUseCase: UpdateSubjectTypeUseCase;
  DeleteSubjectTypeUseCase: DeleteSubjectTypeUseCase;
  AddSubSubjectTypeUseCase: AddSubSubjectTypeUseCase;
  UpdateMasterUseCase: UpdateMasterUseCase;
  DeleteMasterUseCase: DeleteMasterUseCase;
  ListSchoolsUseCase: ListSchoolsUseCase;
  ListClassesUseCase: ListClassesUseCase;
  ListClassesByTeacherUseCase: ListClassesByTeacherUseCase;
  UpdateSessionDetailsUseCase: UpdateSessionDetailsUseCase;
  UpdateAppVersionUseCase: UpdateAppVersionUseCase;
  GetAllAppsVersionUseCase: GetAppVersionUseCase;
  ArchiveStudentUseCase: ArchiveStudentUseCase;
  ArchiveTeacherUseCase: ArchiveTeacherUseCase;
  ArchiveParentUseCase: ArchiveParentUseCase;
  ArchiveAdminUseCase: ArchiveAdminUseCase;
  UnArchiveAdminUseCase: UnArchiveAdminUseCase;
  UnArchiveParentUseCase: UnArchiveParentUseCase;
  UnArchiveStudentUseCase: UnArchiveStudentUseCase;
  UnArchiveTeacherUseCase: UnArchiveTeacherUseCase;
  GetClassOverviewUseCase: GetClassOverviewUseCase;
  GetGroupOverviewUseCase: GetGroupOverviewUseCase;
  UpdateSmsSoldUseCase: UpdateSmsSoldUseCase;
  GetStudentProfileUseCase: GetStudentProfileUseCase;
  GetTeacherProfileUsecase: GetTeacherProfileUsecase;
  UpdateAdminUseCase: UpdateAdminUseCase;
  UpdateStudentUseCase: UpdateStudentUseCase;
  UpdateParentUseCase: UpdateParentUseCase;
  UpdateTeacherUseCase: UpdateTeacherUseCase;
  SwitchToUserUseCase: SwitchToUserUseCase;
  ResendInvitationUseCase: ResendInvitationUseCase;
  // Application services
  SessionApplicationService: SessionApplicationService;
  UpdateSessionStatusUseCase: UpdateSessionStatusUseCase;
  ScheduleApplicationService: ScheduleApplicationService;
  WeeklyScheduleApplicationService: WeeklyScheduleApplicationService;
  WeeklySessionApplicationService: WeeklySessionApplicationService;
  GroupApplicationService: GroupApplicationService;
  StudentApplicationService: StudentApplicationService;
  AdminApplicationService: AdminApplicationService;

  //repos
  VerificationCodeRepo: VerificationCodeRepo;
  SmsSoldHistoryRepo: SmsSoldHistoryRepo;
  AppVersionRepo: AppVersionRepo;
  SchoolYearRepo: SchoolYearRepo;
  MessageLinksRepo: MessageLinksRepo;
  RoleRepo: RoleRepo;
  MasterRepo: MasterRepo;
  ClassGroupRepo: ClassGroupRepo;
  MessageRepo: MessageRepo;
  ConversationRepo: ConversationRepo;
  MessageAttachmentRepo: MessageAttachmentRepo;
  WeeklySessionRepo: WeeklySessionRepo;
  SessionTypeRepo: SessionTypeRepo;
  SessionRepo: SessionRepo;
  NotificationRepo: NotificationRepo;
  ClassRepo: ClassRepo;
  StudentRepo: StudentRepo;
  ParentRepo: ParentRepo;
  AdminRepo: AdminRepo;
  NotificationSettingsRepo: NotificationSettingsRepo;
  LevelRepo: LevelRepo;
  SubLevelRepo: SubLevelRepo;
  StudentProfileRepo: StudentProfileRepo;
  TeacherRepo: TeacherRepo;
  ClassTypeRepo: ClassTypeRepo;
  SubjectTypesRepo: SubjectTypeRepo;
  GroupTypeRepo: GroupTypeRepo;
  SubjectTypeRepo: SubjectTypeRepo;
  TeacherProfileRepo: TeacherProfileRepo;
  SchoolRepo: SchoolRepo;
  ClassroomRepo: ClassroomRepo;
  GroupRepo: GroupRepo;
  SubSubjectTypeRepo: SubSubjectTypesRepo;
  UsersRepo: UsersRepo;

  // request constants
  School: School;
  Connection: Connection;
  Session: ClientSession | undefined;

  // constants
  MasterConnection: Connection;
};
