import "reflect-metadata";
import { ForwardIssueUseCaseUseCase } from "./../../feature/issues/usecases/ForwardIssueUseCase.usecase";
import { UnAssignTeacherFromIssueUseCase } from "./../../feature/issues/usecases/unassignTeacherFromIssue.usecase";
import { AssignTeacherToIssueUseCase } from "./../../feature/issues/usecases/assignTeacherToIssue.usecase";
import { UpdateIssueStatusUseCase } from "./../../feature/issues/usecases/updateIssueStatus.usecase";
import { AddIssueUseCase } from "./../../feature/issues/usecases/addIssue.usecase";
import { AdminApplicationService } from "./../../feature/admins/application/admin.application.service";
import { GetTeacherOfStudentUseCase } from "../../feature/issues/usecases/GetTeacherOfStudent.usecase";
import { SendReplyUseCase } from "../../feature/issues/usecases/SendReply.usecase";
import { GetGroupTypesOfChaptersUseCase } from "../../feature/lms/useCases/GetGroupTypesOfChapters.usecase";
import { ListChapterAttachmentsUseCase } from "../../feature/lms/useCases/ListChapterAttachments.usecase";
import { DeleteChapterUseCase } from "../../feature/lms/useCases/DeleteChapter.usecase";
import { UpdateChapterUseCase } from "../../feature/lms/useCases/UpdateChapter.usecase";
import { AddChapterUseCase } from "../../feature/lms/useCases/AddChapter.usecase";
import { GetTopicsOfChaptersByClassTypeUseCase } from "../../feature/lms/useCases/GetTopicsOfChaptersByClassType.usecase";
import { SignatureRepo } from "../../feature/signatures/domain/Signature.repo";
import { ChapterAttachmentRepo } from "../../feature/lms/domain/ChapterAttachment.repo";
import { DeleteChapterAttachmentUseCase } from "../../feature/lms/useCases/DeleteChapterAttachment.usecase";
import { ChapterRepo } from "../../feature/lms/domain/Chapter.repo";
import { GetChaptersByTopicUseCase } from "../../feature/lms/useCases/GetChaptersByTopic.usecase";
import { GetStudentChaptersUseCase } from "../../feature/lms/useCases/GetStudentChapters.usecase";
import { UpdateChapterAttachmentUseCase } from "../../feature/lms/useCases/UpdateChapterAttachment.usecase";
import { AddChapterAttachmentUseCase } from "../../feature/lms/useCases/AddChapterAttachment.usecase";
import { ClientSession, Connection } from "mongoose";
import { AdminRepo } from "../../feature/admins/domain/Admin.repo";
import { AddAdminUseCase } from "../../feature/admins/useCases/AddAdmin.usecase";
import { GetAdminByNewIdUseCase } from "../../feature/admins/useCases/GetAdminByNewId.usecase";
import { GetDashboardUseCase } from "../../feature/admins/useCases/getDashboard.usecase";
import { ListAdminsUseCase } from "../../feature/admins/useCases/ListAdmins.usecase";
import { UpdateAdminUseCase } from "../../feature/admins/useCases/UpdateAdmin.usecase";
import { AlertRepo } from "../../feature/alertManagement/domain/Alert.repo";
import { AddAlertUseCase } from "../../feature/alertManagement/useCases/AddAlert.usecase";
import { DeleteAlertUseCase } from "../../feature/alertManagement/useCases/DeleteAlert.usecase";
import { GetAlertDetailsUseCase } from "../../feature/alertManagement/useCases/GetAlertDetails.usecase";
import { ListAlertUseCase } from "../../feature/alertManagement/useCases/ListAlert.usecase";
import { ListSmsSoldHistoriesUseCase } from "../../feature/alertManagement/useCases/listSmsSoldHistories.usecase";
import { UpdateAlertUseCase } from "../../feature/alertManagement/useCases/UpdateAlert.usecase";
import { CommentRepo } from "../../feature/announcements/repos/Comment.repo";
import { PostRepo } from "../../feature/announcements/repos/Post.repo";
import { ReactionRepo } from "../../feature/announcements/repos/Reaction.repo";
import { UserPostFeedRepo } from "../../feature/announcements/repos/UserPostFeed.repo";
import { EnrichOneCommentUseCase } from "../../feature/announcements/useCases/EnrichOneComment.usecase";
import { EnrichOnePostUseCase } from "../../feature/announcements/useCases/EnrichOnePost.usecase";
import { EnrichPostsUseCase } from "../../feature/announcements/useCases/EnrichPosts.usecase";
import { ListAllPostsFeedUseCase } from "../../feature/announcements/useCases/ListAllPostsFeed.usecase";
import { ListCommentsOfPostUseCase } from "../../feature/announcements/useCases/ListCommentsOfPost.usecase";
import { ListRepliesOfCommentUseCase } from "../../feature/announcements/useCases/ListRepliesOfComment.usecase";
import { ListUserFeedUseCase } from "../../feature/announcements/useCases/ListUserFeed.usecase";
import { ArchiveAdminUseCase } from "../../feature/archive/useCases/archiveAdmin.usecase";
import { ArchiveParentUseCase } from "../../feature/archive/useCases/archiveParent.usecase";
import { ArchiveStudentUseCase } from "../../feature/archive/useCases/archiveStudent.usecase";
import { ArchiveTeacherUseCase } from "../../feature/archive/useCases/archiveTeacher.usecase";
import { UnArchiveAdminUseCase } from "../../feature/archive/useCases/unarchiveAdmin.usecase";
import { UnArchiveParentUseCase } from "../../feature/archive/useCases/unarchiveParent.usecase";
import { UnArchiveStudentUseCase } from "../../feature/archive/useCases/unarchiveStudent.usecase";
import { UnArchiveTeacherUseCase } from "../../feature/archive/useCases/unarchiveTeacher.usecase";
import { VerificationCodeRepo } from "../../feature/authentication/domain/VerificationCode.repo";
import { ForgetPasswordUseCase } from "../../feature/authentication/useCases/ForgetPassowrd.usecase";
import { LoginUseCase } from "../../feature/authentication/useCases/Login.usecase";
import { LoginByMasterUseCase } from "../../feature/authentication/useCases/LoginByMaster.usecase";
import { LogoutUseCase } from "../../feature/authentication/useCases/Logout.usecase";
import { ResendInvitationUseCase } from "../../feature/authentication/useCases/ResendInvitation.usecase";
import { ResetPasswordUseCase } from "../../feature/authentication/useCases/ResetPassword.usecase";
import { ResetUserPasswordUseCase } from "../../feature/authentication/useCases/ResetUserPassword.usecase";
import { SwitchToUserUseCase } from "../../feature/authentication/useCases/SwitchToUser.usecase";
import { UpdateCurrentUserPasswordUseCase } from "../../feature/authentication/useCases/UpdateCurrentUserPassword.usecase";
import { VerifyCodeUseCase } from "../../feature/authentication/useCases/VerifyCode.usecase";
import { RoleRepo } from "../../feature/authorization/domain/Role.repo";
import { AddRoleUseCase } from "../../feature/authorization/useCases/AddRole.usecase";
import { DeleteRoleUseCase } from "../../feature/authorization/useCases/DeleteRole.usecase";
import { GetOneRoleUseCase } from "../../feature/authorization/useCases/GetOneRole.usecase";
import { ListRolesUseCase } from "../../feature/authorization/useCases/ListRoles.usecase";
import { UpdateRoleUseCase } from "../../feature/authorization/useCases/UpdateRole.usecase";
import { BarCodeConfigRepo } from "../../feature/barCode/domain/BarCodeConfig.repo";
import { AddBarCodeConfigUseCase } from "../../feature/barCode/useCases/AddBarCodeConfig.usecase";
import { DeleteBarCodeConfigUseCase } from "../../feature/barCode/useCases/DeleteBarCodeConfig.usecase";
import { ListBarCodeConfigUseCase } from "../../feature/barCode/useCases/ListBarCodeConfig.usecase";
import { UpdateBarCodeConfigUseCase } from "../../feature/barCode/useCases/UpdateBarCodeConfig.usecase";
import { AddSignatureUseCase } from "../../feature/signatures/useCases/AddSignature.usecase";
import { DeleteSignatureUseCase } from "../../feature/signatures/useCases/DeleteSignature.usecase";
import { ListSignaturesUseCase } from "../../feature/signatures/useCases/ListSignatures.usecase";
import { UpdateSignatureUseCase } from "../../feature/signatures/useCases/UpdateSignature.usecase";
import { ClassRepo } from "../../feature/classes/domain/Class.repo";
import { ClassService } from "../../feature/classes/domain/Class.service";
import { ClassGroupRepo } from "../../feature/classes/domain/classGroup.repo";
import { AddClassUseCase } from "../../feature/classes/useCases/AddClass.usecase";
import { AssignStudentToClassUseCase } from "../../feature/classes/useCases/AssignStudentToClass.usecase";
import { AssignTeachersToSubjectsInClassUseCase } from "../../feature/classes/useCases/AssignTeacherToSubjectInClass.usecase";
import { AssignTeacherToSubSubjectInClassUseCase } from "../../feature/classes/useCases/AssignTeacherToSubSubjectInClass.usecase";
import { DeleteClassUseCase } from "../../feature/classes/useCases/DeleteClass.usecase";
import { GetClassDashboardUseCase } from "../../feature/classes/useCases/GetClassDashboard.usecase";
import { GetClassListUseCase } from "../../feature/classes/useCases/GetClassList.usecase";
import { GetClassOverviewUseCase } from "../../feature/classes/useCases/GetClassOverview.usecase";
import { GetGroupsOfClassUseCase } from "../../feature/classes/useCases/GetGroupsOfClass.usecase";
import { GetStudentsCodeBarePdfUseCase } from "../../feature/classes/useCases/GetStudentsCodeBarePdf.usecase";
import { GetStudentsOfClassUseCase } from "../../feature/classes/useCases/GetStudentsOfClass.usecase";
import { GetSubjectTypesOfClassUseCase } from "../../feature/classes/useCases/GetSubjectTypesOfClass.usecase";
import { GetSubjectsOfClassUseCase } from "../../feature/classes/useCases/GetSubjectsOfClass.usecase";
import { GetTeacherClassAndGroupsUseCase } from "../../feature/classes/useCases/GetTeacherClassAndGroups.usecase";
import { ListClassesUseCase } from "../../feature/classes/useCases/ListClasses.usecase";
import { ListClassesByTeacherUseCase } from "../../feature/classes/useCases/ListClassesByTeacher.usecase";
import { UnassignStudentFromClassUseCase } from "../../feature/classes/useCases/UnassignStudentFromClass.usecase";
import { UnAssignTeacherFromSubjectUseCase } from "../../feature/classes/useCases/UnAssignTeacherFromSubject.usecase";
import { UnAssignTeacherFromSubSubjectUseCase } from "../../feature/classes/useCases/UnAssignTeacherFromSubSubject.usecase";
import { UpdateClassUseCase } from "../../feature/classes/useCases/UpdateClass.usecase";
import { UpdateStudentGroupUseCase } from "../../feature/classes/useCases/UpdateStudentGroup.usecase";
import { ClassroomRepo } from "../../feature/classrooms/domains/classroom.repo";
import { AddClassroomUseCase } from "../../feature/classrooms/useCases/AddClassroom.usecase";
import { DeleteClassroomUseCase } from "../../feature/classrooms/useCases/DeleteClassroom.usecase";
import { GetAvailableClassroomUseCase } from "../../feature/classrooms/useCases/GetAvailableClassroom.usecase";
import { GetAvailableClassroomInWeeklySessionUseCase } from "../../feature/classrooms/useCases/GetAvailableClassroomInWeeklySession.usecase";
import { ListClassroomsUseCase } from "../../feature/classrooms/useCases/ListClassrooms.usecase";
import { UpdateClassroomUseCase } from "../../feature/classrooms/useCases/UpdateClassroom.usecase";
import { ClassTypeRepo } from "../../feature/classTypes/repo/ClassType.repo";
import { AddClassTypeUseCase } from "../../feature/classTypes/useCases/addClassTypes.usecase";
import { AddFieldToClasstypeUseCase } from "../../feature/classTypes/useCases/AddFieldToClasstype.usecase";
import { AddSubjectToClassTypeUseCase } from "../../feature/classTypes/useCases/AddSubjectToClassType.usecase";
import { AddSubSubjectToClassTypeUseCase } from "../../feature/classTypes/useCases/AddSubSubjectToClassType.usecase";
import { DeleteClassTypeUseCase } from "../../feature/classTypes/useCases/DeleteClassType.usecase";
import { DeleteFieldFromClassTypeUseCase } from "../../feature/classTypes/useCases/DeleteFieldFromClassType.usecase";
import { DeleteSubjectFromClassTypeUseCase } from "../../feature/classTypes/useCases/DeleteSubjectFromClassType.usecase";
import { DeleteSubSubjectFromClassTypeUseCase } from "../../feature/classTypes/useCases/DeleteSubSubjectFromClassType.usecase";
import { GetClassTypeUseCase } from "../../feature/classTypes/useCases/GetClassType.usecase";
import { GetFieldsOfClassTypeUseCase } from "../../feature/classTypes/useCases/GetFieldsOfClassTypes.usecase";
import { GetSubjectsOfClassTypesUseCase } from "../../feature/classTypes/useCases/GetSubjectsOfClassTypes.usecase";
import { ListClassTypeUseCase } from "../../feature/classTypes/useCases/ListClassTypes.usecase";
import { ListNextClassTypesUseCase } from "../../feature/classTypes/useCases/ListNextClassTypes.usecase";
import { ReorderFieldsOfClassTypesUseCase } from "../../feature/classTypes/useCases/ReorderFieldsOfClassType.usecase";
import { ReorderSubjectInClassTypeUseCase } from "../../feature/classTypes/useCases/ReorderSubjectInClassType.usecase";
import { ReorderSubSubjectInClassTypeUseCase } from "../../feature/classTypes/useCases/ReorderSubSubjectInClassType.usecase";
import { UpdateClassTypeUseCase } from "../../feature/classTypes/useCases/updateClassTypes.usecase";
import { UpdateFieldOfClassTypeUseCase } from "../../feature/classTypes/useCases/UpdateFieldOfClassType.usecase";
import { UpdateSubjectFromClassTypeUseCase } from "../../feature/classTypes/useCases/UpdateSubjectOfClassType.usecase";
import { UpdateSubSubjectOfClassTypeUseCase } from "../../feature/classTypes/useCases/UpdateSubSubjectOfClassType.usecase";
import { DiplomaRepo } from "../../feature/diploma/Diploma.repo";
import { DiplomaService } from "../../feature/diploma/Diploma.service";
import { GetStudentDocumentsQueryUseCase } from "../../feature/documents/useCases/GetStudentDocumentsQuery.usecase";
import { ListDocumentsOfStudentsUseCase } from "../../feature/documents/useCases/ListDocumentsOfStudents.usecase";
import { EmailManager } from "../../feature/emailManager/domain/EmailManager";
import { AutomaticPromotionGradesRepo } from "../../feature/examGrade/domain/automaticPromotion/AutomaticPromotionGrades.repo";
import { CambridgeClassGradesRepo } from "../../feature/examGrade/domain/cambridge/CambridgeClassGrades.repo";
import { IBClassGradesRepo } from "../../feature/examGrade/domain/ib/IBClassGrades.repo";
import { ExamGradeRepo } from "../../feature/examGrade/domain/tunisian/ExamGrade.repo";
import { PrimaryClassGradesRepo } from "../../feature/examGrade/domain/tunisian/primary/PrimaryClassGrades.repo";
import { SecondaryClassGradesRepo } from "../../feature/examGrade/domain/tunisian/secondary/SecondaryClassGrades.repo";
import { ClassGradeFactory } from "../../feature/examGrade/factories/classGrade.factory";
import { GetAllCambridgeGradeReportsOfClassUseCase } from "../../feature/examGrade/useCases/cambridge/GetAllCambridgeGradeReportsOfClass.usecase";
import { GetCambridgeAveragesOfClassUsecase } from "../../feature/examGrade/useCases/cambridge/GetCambridgeAveragesOfClass.usecase";
import { GetCambridgeBlankExamPageUsecase } from "../../feature/examGrade/useCases/cambridge/GetCambridgeBlankExamPage.usecase";
import { GetCambridgeChildGradeReportUseCase } from "../../feature/examGrade/useCases/cambridge/GetCambridgeChildGradeReport.usecase";
import { GetCambridgeStudentGradeReportUseCase } from "../../feature/examGrade/useCases/cambridge/GetCambridgeStudentGradeReport.usecase";
import { GetCambridgeSubjectsOfClassUseCase } from "../../feature/examGrade/useCases/cambridge/GetCambridgeSubjectsOfClass.usecase";
import { GetGradesOfCambridgeGroupUsecase } from "../../feature/examGrade/useCases/cambridge/GetGradesOfCambridgeGroup.usecase";
import { GetGradesOfCambridgeSubjectUseCase } from "../../feature/examGrade/useCases/cambridge/GetGradesOfCambridgeSubject.usecase";
import { UpdateCambridgeGradesUseCase } from "../../feature/examGrade/useCases/cambridge/UpdateCambridgeGrades.usecase";
import { UpdateCambridgeGradesOfGroupUseCase } from "../../feature/examGrade/useCases/cambridge/UpdateCambridgeGradesOfGroup.usecase";
import { CompleteTermUseCase } from "../../feature/examGrade/useCases/CompleteTerm.usecase";
import { GetAnnualAveragesOfClassUseCase } from "../../feature/examGrade/useCases/GetAnnualAveragesOfClass.usecase";
import { GetClassDiplomasUseCase } from "../../feature/examGrade/useCases/GetClassDiplomas.usecase";
import { GetLevelDegreesCoverageUsecase } from "../../feature/examGrade/useCases/GetLevelDegreesCoverage.usecase";
import { GetNotPromotedStudentsUsecase } from "../../feature/examGrade/useCases/getNotPromotedStudentsOfLevel.usecase";
import { GetStudentDiplomaUseCase } from "../../feature/examGrade/useCases/GetStudentDiploma.usecase";
import { HideTermUseCase } from "../../feature/examGrade/useCases/HideTerm.usecase";
import { GetAllIBGradeReportsOfClassUseCase } from "../../feature/examGrade/useCases/ib/GetAllIBGradeReportsOfClass.usecase";
import { GetGradesOfIBGroupUsecase } from "../../feature/examGrade/useCases/ib/GetGradesOfIBGroup.usecase";
import { GetGradesOfIBSubjectUseCase } from "../../feature/examGrade/useCases/ib/GetGradesOfIBSubject.usecase";
import { GetIBAdminObservationsUseCase } from "../../feature/examGrade/useCases/ib/GetIBAdminObservations.usecase";
import { GetIBAveragesOfClassUsecase } from "../../feature/examGrade/useCases/ib/GetIBAveragesOfClass.usecase";
import { GetIBBlankExamPageUsecase } from "../../feature/examGrade/useCases/ib/GetIBBlankExamPage.usecase";
import { GetIBChildGradeReportUseCase } from "../../feature/examGrade/useCases/ib/GetIBChildGradeReport.usecase";
import { GetIBStudentGradeReportUseCase } from "../../feature/examGrade/useCases/ib/GetIBStudentGradeReport.usecase";
import { GetIBSubjectsOfClassUseCase } from "../../feature/examGrade/useCases/ib/GetIBSubjectsOfClass.usecase";
import { UpdateAdminObservationsUseCase } from "../../feature/examGrade/useCases/UpdateAdminObservations.usecase";
import { UpdateIBGradesOfClassUseCase } from "../../feature/examGrade/useCases/ib/UpdateIBGradesOfClass.usecase";
import { UpdateIBGradesOfGroupUseCase } from "../../feature/examGrade/useCases/ib/UpdateIBGradesOfGroup.usecase";
import { IncompleteTermUseCase } from "../../feature/examGrade/useCases/IncompleteTerm.usecase";
import { GetAllPrimaryAnnualGradeReportOfClassUsecase } from "../../feature/examGrade/useCases/primary/GetAllPrimaryAnnualGradeReportOfClass.usecase";
import { GetAllPrimaryGradeReportsOfClassUseCase } from "../../feature/examGrade/useCases/primary/GetAllPrimaryGradeReportsOfClass.usecase";
import { GetFieldsOfClassUseCase } from "../../feature/examGrade/useCases/primary/GetFieldsOfClass.usecase";
import { GetGradesOfFieldUseCase } from "../../feature/examGrade/useCases/primary/GetGradesOfField.usecase";
import { GetPrimaryAnnualGradeReportOfStudentUsecase } from "../../feature/examGrade/useCases/primary/GetPrimaryAnnualGradeReportOfStudent.usecase";
import { GetPrimaryAveragesOfClassUsecase } from "../../feature/examGrade/useCases/primary/GetPrimaryAveragesOfClass.usecase";
import { GetPrimaryBlankExamPageUsecase } from "../../feature/examGrade/useCases/primary/GetPrimaryBlankExamPage.usecase";
import { GetPrimaryChildGradeReportUseCase } from "../../feature/examGrade/useCases/primary/GetPrimaryChildGradeReport.usecase";
import { GetPrimaryGradeReportStatsUseCase } from "../../feature/examGrade/useCases/primary/GetPrimaryGradeReportStats.usecase";
import { GetPrimaryStudentGradeReportUseCase } from "../../feature/examGrade/useCases/primary/GetPrimaryStudentGradeReport.usecase";
import { UpdatePrimaryGradesUseCase } from "../../feature/examGrade/useCases/primary/UpdatePrimaryGrades.usecase";
import { PublishTermUseCase } from "../../feature/examGrade/useCases/PublishTerm.usecase";
import { GetAllSecondaryGradeReportsOfClassUseCase } from "../../feature/examGrade/useCases/secondary/GetAllSecondaryGradeReportsOfClass.usecase";
import { GetGradesOfSecondaryGroupUseCase } from "../../feature/examGrade/useCases/secondary/GetGradesOfSecondaryGroup.usecase";
import { GetGradesOfSecondarySubjectUseCase } from "../../feature/examGrade/useCases/secondary/GetGradesOfSecondarySubject.usecase";
import { GetSecondaryAveragesOfClassUsecase } from "../../feature/examGrade/useCases/secondary/GetSecondaryAveragesOfClass.usecase";
import { GetSecondaryBlankExamPageUsecase } from "../../feature/examGrade/useCases/secondary/GetSecondaryBlankExamPage.usecase";
import { GetSecondaryChildGradeReportUseCase } from "../../feature/examGrade/useCases/secondary/GetSecondaryChildGradeReport.usecase";
import { GetSecondaryGradeReportStatsUseCase } from "../../feature/examGrade/useCases/secondary/GetSecondaryGradeReportStats.usecase";
import { GetSecondaryStudentGradeReportUseCase } from "../../feature/examGrade/useCases/secondary/GetSecondaryStudentGradeReport.usecase";
import { GetSecondarySubjectsOfClassUseCase } from "../../feature/examGrade/useCases/secondary/GetSecondarySubjectsOfClass.usecase";
import { UpdateSecondaryGradesUseCase } from "../../feature/examGrade/useCases/secondary/UpdateSecondaryGrades.usecase";
import { SwitchLevelToNextSchoolYearUseCase } from "../../feature/examGrade/useCases/SwitchLevelToNextSchoolYear.usecase";
import { UpdateStudentPromotionStatusUsecase } from "../../feature/examGrade/useCases/UpdateStudentPromotionStatus.usecase";
import { ExamTypeRepo } from "../../feature/examTypes/repos/examType.repo";
import { AddExamTypeUseCase } from "../../feature/examTypes/useCases/AddExamType.usecase";
import { DeleteExamTypeUseCase } from "../../feature/examTypes/useCases/DeleteExamType.usecase";
import { ListExamTypeUseCase } from "../../feature/examTypes/useCases/listExamType.usecase";
import { ReorderExamTypeUseCase } from "../../feature/examTypes/useCases/ReorderExamType.usecase";
import { UpdateExamTypeUseCase } from "../../feature/examTypes/useCases/UpdateExamType.usecase";
import { ExpenseRepo } from "../../feature/expenses/domain/Expense.repo";
import { AddExpenseUseCase } from "../../feature/expenses/useCases/AddExpense.usecase";
import { DeleteExpenseUseCase } from "../../feature/expenses/useCases/DeleteExpense.usecase";
import { UpdateExpenseUseCase } from "../../feature/expenses/useCases/UpdateExpense.usecase";
import { GradeBookObservationRepo } from "../../feature/gradeBookObservation/GradeBookObservation.repo";
import { GradeReportTemplateRepo } from "../../feature/gradeReportTemplate/domain/GradeReportTemplate.repo";
import { AddGradeReportTemplateUseCase } from "../../feature/gradeReportTemplate/useCases/AddGradeReportTemplate.usecase";
import { DeleteGradeReportTemplateUseCase } from "../../feature/gradeReportTemplate/useCases/DeleteGradeReportTemplate.usecase";
import { ListGradeReportTemplateUseCase } from "../../feature/gradeReportTemplate/useCases/ListGradeReportTemplate.usecase";
import { UpdateGradeReportTemplateUseCase } from "../../feature/gradeReportTemplate/useCases/UpdateGradeReportTemplate.usecase";
import { GroupRepo } from "../../feature/groupManagement/repos/Group.repo";
import { GroupTypeRepo } from "../../feature/groupManagement/repos/GroupType.repo";
import { DeleteGroupUseCase } from "../../feature/groupManagement/useCases/DeleteGroup.usecase";
import { GetGroupListUseCase } from "../../feature/groupManagement/useCases/GetGroupList.usecase";
import { GetGroupsOfStudentUseCase } from "../../feature/groupManagement/useCases/GetGroupsOfStudent.usecase";
import { UpdateGroupUseCase } from "../../feature/groupManagement/useCases/UpdateGroup.usecase";
import { UpdateGroupTeacherUseCase } from "../../feature/groupManagement/useCases/UpdateGroupTeacher.usecase";
import { AddGroupTypeUseCase } from "../../feature/groupType/useCases/AddGroupType.usecase";
import { DeleteGroupTypeUseCase } from "../../feature/groupType/useCases/DeleteGroupType.usecase";
import { ListGroupTypesUseCase } from "../../feature/groupType/useCases/ListGroupTypes.usecase";
import { UpdateGroupTypeUseCase } from "../../feature/groupType/useCases/UpdateGroupType.usecase";
import { HolidayRepo } from "../../feature/holidays/domain/Holiday.repo";
import { AddHolidayUseCase } from "../../feature/holidays/useCases/AddHoliday.usecase";
import { DeleteHolidayUseCase } from "../../feature/holidays/useCases/DeleteHoliday.usecase";
import { ListHolidayUseCase } from "../../feature/holidays/useCases/ListHoliday.usecase";
import { UpdateHolidayUseCase } from "../../feature/holidays/useCases/UpdateHoliday.usecase";
import { HomeworkApplicationService } from "../../feature/homeworks/applicationServices/homework.application.service";
import { HomeworkRepo } from "../../feature/homeworks/domain/Homework.repo";
import { HomeworkService } from "../../feature/homeworks/domain/Homework.service";
import { GetOneHomeworkUseCase } from "../../feature/homeworks/useCases/GetOneHomework.usecase";
import { ListHomeworkUseCase } from "../../feature/homeworks/useCases/ListHomeworks.usecase";
import { InteractionRepo } from "../../feature/issues/domain/Interaction.repo";
import { IssueRepo } from "../../feature/issues/domain/Issue.repo";
import { IssueReasonRepo } from "../../feature/issues/domain/IssueReason.repo";
import { GetOneIssueUseCase } from "../../feature/issues/usecases/getOneIssue.usecase";
import { ListInteractionsOfIssueUseCase } from "../../feature/issues/usecases/listInteractionsOfIssue.usecase";
import { ListIssuesOfAdminUseCase } from "../../feature/issues/usecases/listIssuesOfAdmin.usecase";
import { ListIssuesOfParentUseCase } from "../../feature/issues/usecases/listIssuesOfParent.usecase";
import { ListIssuesOfTeacherUseCase } from "../../feature/issues/usecases/listIssuesOfTeacher.usecase";
import { LevelRepo } from "../../feature/levels/repos/Level.repo";
import { AddLevelUseCase } from "../../feature/levels/useCases/AddLevel.usecase";
import { DeleteLevelUseCase } from "../../feature/levels/useCases/DeleteLevel.usecase";
import { GetLevelsOverviewUseCase } from "../../feature/levels/useCases/GetLevelsOverview.usecase";
import { ReorderLevelsUseCase } from "../../feature/levels/useCases/ReorderLevels.usecase";
import { UpdateLevelUseCase } from "../../feature/levels/useCases/UpdateLevel.usecase";
import { AppVersionRepo } from "../../feature/masters/domain/AppVersion.repo";
import { MasterRepo } from "../../feature/masters/domain/Master.repo";
import { AddMasterUseCase } from "../../feature/masters/useCases/AddMaster.usecase";
import { DeleteMasterUseCase } from "../../feature/masters/useCases/DeleteMaster.usecase";
import { ListMastersUseCase } from "../../feature/masters/useCases/ListMasters.usecase";
import { UpdateMasterUseCase } from "../../feature/masters/useCases/UpdateMaster.usecase";
import { ConversationRepo } from "../../feature/messages/domain/Conversation.repo";
import { MessageRepo } from "../../feature/messages/domain/Message.repo";
import { MessageAttachmentRepo } from "../../feature/messages/domain/MessageAttachment.repo";
import { MessageLinksRepo } from "../../feature/messages/domain/MessageLinks.repo";
import { AddMessageUseCase } from "../../feature/messages/useCases/AddMessage.usecase";
import { GetMessageReactionsUseCase } from "../../feature/messages/useCases/GetMessageReactions.usercase";
import { ListConversationParticipantsUseCase } from "../../feature/messages/useCases/ListConversationParticipants.usecase";
import { ListConversationsUseCase } from "../../feature/messages/useCases/ListConversations.usecase";
import { ReactToMessageUseCase } from "../../feature/messages/useCases/ReactToMessage.usecase";
import { NotificationRepo } from "../../feature/notifications/Notification.repo";
import { NotificationSettingsRepo } from "../../feature/notifications/NotificationSettings.repo";
import { NotificationSettingsService } from "../../feature/notifications/NotificationSettings.service";
import { ObservationRepo } from "../../feature/observations/domain/Observation.repo";
import { AddObservationForClassUseCase } from "../../feature/observations/useCases/AddObservationForClass.usecase";
import { AddObservationForGroupUseCase } from "../../feature/observations/useCases/AddObservationForGroup.usecase";
import { DeleteObservationUseCase } from "../../feature/observations/useCases/DeleteObservation.usecase";
import { GetOneObservationUseCase } from "../../feature/observations/useCases/GetOneObservation.usecase";
import { ListObservationsUseCase } from "../../feature/observations/useCases/ListObservations.usecase";
import { UpdateObservationUseCase } from "../../feature/observations/useCases/UpdateObservation.usecase";
import { ObservationReasonRepo } from "../../feature/observationsReason/domains/ObservationReason.repo";
import { AddObservationReasonUsecase } from "../../feature/observationsReason/usecases/AddObservationReason.usecase";
import { DeleteObservationReasonUseCase } from "../../feature/observationsReason/usecases/DeleteObservationReason.usecase";
import { ListObservationReasonsUseCase } from "../../feature/observationsReason/usecases/ListObservationReasons.usecase";
import { UpdateObservationReasonUseCase } from "../../feature/observationsReason/usecases/UpdateObservationReason.usecase";
import { ParentRepo } from "../../feature/parents/domain/Parent.repo";
import { AddParentUseCase } from "../../feature/parents/useCases/AddParent.usecase";
import { GetChildrenOfParentUseCase } from "../../feature/parents/useCases/GetChildrenOfParent.usecase";
import { GetParentByNewIdUseCase } from "../../feature/parents/useCases/GetParentByNewId.usecase";
import { ListParentsUseCase } from "../../feature/parents/useCases/ListParents.usecase";
import { UpdateParentUseCase } from "../../feature/parents/useCases/UpdateParent.usecase";
import { BankTransferRepo } from "../../feature/payment/domain/BankTransfer.repo";
import { PaymentStrategyFactory } from "../../feature/payment/strategies/paymentStrategy.factory";
import { DeletePaymentTemplateUseCase } from "../../feature/paymentTemplate/usecases/deletePaymentTemplate.usecase";
import { PreRegistrationRepo } from "../../feature/preRegistration/domains/PreRegistration.repo";
import { DeletePreRegistrationUseCase } from "../../feature/preRegistration/useCases/DeletePreRegistration.usecase";
import { GetOnePreRegistrationUseCase } from "../../feature/preRegistration/useCases/GetOnePreRegistration.usecase";
import { ListPreRegistrationsUseCase } from "../../feature/preRegistration/useCases/ListPreRegistrations.usecase";
import { RegisterStudentUseCase } from "../../feature/preRegistration/useCases/RegisterStudent.usecase";
import { UpdatePreRegistrationUseCase } from "../../feature/preRegistration/useCases/UpdatePreRegistration.usecase";
import { ScheduleApplicationService } from "../../feature/schedules/applications/Schedule.application.service";
import { ApplyWeeklyScheduleForClassUseCase } from "../../feature/schedules/useCases/ApplyWeeklyScheduleForClass.usecase";
import { DeleteSessionUseCase } from "../../feature/schedules/useCases/DeleteSession.usecase";
import { GetEntityScheduleUseCase } from "../../feature/schedules/useCases/GetEntitySchedule.usecase";
import { GetScheduleUseCase } from "../../feature/schedules/useCases/GetSchedule.usecase";
import { SchoolRepo } from "../../feature/schools/domain/School.repo";
import { SmsSoldHistoryRepo } from "../../feature/schools/domain/SmsSoldHistory.repo";
import { AddSchoolUseCase } from "../../feature/schools/useCases/AddSchool.usecase";
import { GetSchoolDetailsUseCase } from "../../feature/schools/useCases/GetSchoolInformation.usecase";
import { ListSchoolsUseCase } from "../../feature/schools/useCases/ListSchools.usecase";
import { SwitchToSchoolUsecase } from "../../feature/schools/useCases/SwitchToSchool.usecase";
import { UpdateFlagsUseCase } from "../../feature/schools/useCases/UpdateFlags.usecase";
import { UpdateSchoolUseCase } from "../../feature/schools/useCases/UpdateSchool.usecase";
import { UpdateSmsSoldUseCase } from "../../feature/schools/useCases/UpdateSmsSold.usecase";
import { SchoolYearRepo } from "../../feature/schoolYears/domain/SchoolYear.repo";
import { AddSchoolYearUseCase } from "../../feature/schoolYears/useCases/AddSchoolYear.usecase";
import { ListSchoolYearUseCase } from "../../feature/schoolYears/useCases/ListSchoolYear.usecase";
import { UpdateSchoolYearUseCase } from "../../feature/schoolYears/useCases/UpdateSchoolYear.usecase";
import { SectionRepo } from "../../feature/sections/repos/Section.repo";
import { AddSectionUseCase } from "../../feature/sections/useCases/AddSection.usecase";
import { DeleteSectionUseCase } from "../../feature/sections/useCases/DeleteSection.usecase";
import { ListSectionsUseCase } from "../../feature/sections/useCases/ListSections.usecase";
import { UpdateSectionUseCase } from "../../feature/sections/useCases/UpdateSection.usecase";
import { SessionApplicationService } from "../../feature/sessionManagement/applicationServices/Session.application.service";
import { SessionRepo } from "../../feature/sessionManagement/domain/Session.repo";
import { SessionService } from "../../feature/sessionManagement/domain/Session.service";
import { AddSessionForClassUseCase } from "../../feature/sessionManagement/useCases/AddSessionForClass.usecase";
import { AddSessionForGroupUseCase } from "../../feature/sessionManagement/useCases/AddSessionForGroup.usecase";
import { GetSessionDetailsUseCase } from "../../feature/sessionManagement/useCases/getSessionDetails.usecase";
import { UpdateSessionDetailsUseCase } from "../../feature/sessionManagement/useCases/updateSessionDetails.usecase";
import { UpdateSessionForClassUseCase } from "../../feature/sessionManagement/useCases/UpdateSessionForClass.usecase";
import { UpdateSessionForGroupUseCase } from "../../feature/sessionManagement/useCases/UpdateSessionForGroup.usecase";
import { SessionTypeRepo } from "../../feature/sessionTypes/repos/SessionType.repo";
import { AddSessionTypeUseCase } from "../../feature/sessionTypes/usecases/AddSessionType.usecase";
import { DeleteSessionTypeUseCase } from "../../feature/sessionTypes/usecases/DeleteSessionType.usecase";
import { ListSessionTypeUseCase } from "../../feature/sessionTypes/usecases/ListSessionType.usecase";
import { UpdateSessionTypeUseCase } from "../../feature/sessionTypes/usecases/UpdateSessionType.usecase";
import { SmartCalendarScheduleRepo } from "../../feature/smartCalendar/domain/SmartCalendarSchedule.repo";
import { SmartCalendarSessionRepo } from "../../feature/smartCalendar/domain/SmartCalendarSession.repo";
import { SmartCalendarConfigFactory } from "../../feature/smartCalendar/factories/SmartCalendarConfig.factory";
import { ApplySmartCalendarScheduleUseCase } from "../../feature/smartCalendar/useCases/ApplySmartCalendarSchedule.usecase";
import { CancelSmartCalendarScheduleUseCase } from "../../feature/smartCalendar/useCases/CancelSmartCalendarSchedule.usecase";
import { CompleteScheduleGenerationUseCase } from "../../feature/smartCalendar/useCases/CompleteScheduleGeneration.usecase";
import { DeleteClassTypeActivityUseCase } from "../../feature/smartCalendar/useCases/DeleteClassTypeActivity.usecase";
import { DeleteSmartCalendarScheduleUseCase } from "../../feature/smartCalendar/useCases/DeleteSmartCalendarSchedule.usecase";
import { GenerateScheduleUseCase } from "../../feature/smartCalendar/useCases/GenerateSchedule.usecase";
import { GetActivitiesOfClassTypeUseCase } from "../../feature/smartCalendar/useCases/GetActivitiesOfClassType.usecase";
import { GetSchoolAvailableTimeConstraintsUseCase } from "../../feature/smartCalendar/useCases/getSchoolAvailableTimeConstraint.usecase";
import { GetSmartSchedulePDFUseCase } from "../../feature/smartCalendar/useCases/GetSmartSchedulePDF.usecase";
import { ListSmartCalendarSchedulesUseCase } from "../../feature/smartCalendar/useCases/ListSmartCalendarSchedules.usecase";
import { MarkSmartScheduleAsErroredUseCase } from "../../feature/smartCalendar/useCases/MarkSmartScheduleAsErrored.usecase";
import { UpdateClassConstraintsUseCase } from "../../feature/smartCalendar/useCases/updateClassConstraints.usecase";
import { UpdateClassTypeActivityUseCase } from "../../feature/smartCalendar/useCases/UpdateClassTypeActivity.usecase";
import { UpdateSmartCalendarScheduleUseCase } from "../../feature/smartCalendar/useCases/UpdateSmartCalendarSchedule.usecase";
import { UpdateTeacherConstraintsUseCase } from "../../feature/smartCalendar/useCases/updateTeacherConstraints.usecase";
import { SmsManager } from "../../feature/smsManager/domain/SmsManager";
import { BankCheckRepo } from "../../feature/studentPayments/BankCheck.repo";
import { InvoiceRepo } from "../../feature/studentPayments/Invoice.repo";
import { PaymentTemplateRepo } from "../../feature/studentPayments/PaymentTemplate.repo";
import { ServiceRepo } from "../../feature/studentPayments/Service.repo";
import { StudentPaymentConfigurationRepo } from "../../feature/studentPayments/StudentPaymentConfiguration.repo";
import { UpdateBankCheckUseCase } from "../../feature/studentPayments/useCases/UpdateBankCheck.usecase";
import { StudentApplicationService } from "../../feature/students/application/Student.application.service";
import { StudentRepo } from "../../feature/students/domain/Student.repo";
import { StudentProfileRepo } from "../../feature/students/domain/StudentProfile.repo";
import { AddStudentUseCase } from "../../feature/students/useCases/AddStudent.usecase";
import { GetStudentAttendanceCertificateUseCase } from "../../feature/students/useCases/GetStudentAttendanceCertificate.usecase";
import { GetStudentProfileUseCase } from "../../feature/students/useCases/GetStudentProfile.usecase";
import { ImportStudentsUseCase } from "../../feature/students/useCases/ImportStudents.usecase";
import { ToggleUserActivationUseCase } from "../../feature/students/useCases/ToggleUserActivation.usecase";
import { UpdateStudentUseCase } from "../../feature/students/useCases/UpdateStudent.usecase";
import { SubjectTypeRepo } from "../../feature/subjectTypes/domains/SubjectType.repo";
import { AddSubjectTypeUseCase } from "../../feature/subjectTypes/useCases/AddSubjectType.usecase";
import { DeleteSubjectTypeUseCase } from "../../feature/subjectTypes/useCases/DeleteSubjectType.usecase";
import { UpdateSubjectTypeUseCase } from "../../feature/subjectTypes/useCases/UpdateSubjectType.usecase";
import { SubLevelRepo } from "../../feature/subLevels/domains/SubLevel.repo";
import { AddSubLevelUseCase } from "../../feature/subLevels/useCases/AddSubLevel.usecase";
import { DeleteSubLevelUseCase } from "../../feature/subLevels/useCases/DeleteSubLevel.usecase";
import { ReorderSubLevelsUseCase } from "../../feature/subLevels/useCases/ReorderSubLevels.usecase";
import { UpdateSubLevelUseCase } from "../../feature/subLevels/useCases/UpdateSubLevel.usecase";
import { SubSubjectTypesRepo } from "../../feature/subSubjectTypes/repos/SubSubjectTypes.repo";
import { AddSubSubjectTypeUseCase } from "../../feature/subSubjectTypes/usecases/AddSubSubjectType.usecase";
import { DeleteSubSubjectTypeUseCase } from "../../feature/subSubjectTypes/usecases/DeleteSubSubjectType.usecase";
import { ListSubSubjectTypeUseCase } from "../../feature/subSubjectTypes/usecases/ListSubSubjectType.usecase";
import { UpdateSubSubjectTypeUsecase } from "../../feature/subSubjectTypes/usecases/UpdateSubSubjectType.usecase";
import { SupplierRepo } from "../../feature/supplier/Supplier.repo";
import { SupplierService } from "../../feature/supplier/Supplier.service";
import { TeacherPaymentConfigurationRepo } from "../../feature/teacherPayment/domain/TeacherPaymentConfiguration.repo";
import { TeacherPaymentHistoryRepo } from "../../feature/teacherPayment/domain/TeacherPaymentHistory.repo";
import { GetTeacherPaymentDashboardUseCase } from "../../feature/teacherPayment/usecases/getTeacherPaymentDashboard.usecase";
import { UnPayTeacherUseCase } from "../../feature/teacherPayment/usecases/unPayTeacher.usecase";
import { UpdateTeacherPaymentConfigurationUseCase } from "../../feature/teacherPayment/usecases/updateTeacherPaymentConfiguration.usecase";
import { TeacherRepo } from "../../feature/teachers/domain/Teacher.repo";
import { TeacherProfileRepo } from "../../feature/teachers/domain/TeacherProfile.repo";
import { AddTeacherUseCase } from "../../feature/teachers/useCases/AddTeacher.usecase";
import { GetTeacherProfileUsecase } from "../../feature/teachers/useCases/GetTeacherProfile.usecase";
import { GetTeachersOfStudentUseCase } from "../../feature/teachers/useCases/GetTeachersOfStudent.usecase";
import { ListTeachersUseCase } from "../../feature/teachers/useCases/ListTeachers.usecase";
import { UpdateTeacherUseCase } from "../../feature/teachers/useCases/UpdateTeacher.usecase";
import { TermRepo } from "../../feature/terms/repos/Term.repo";
import { AddTermUseCase } from "../../feature/terms/usecases/AddTerm.usecase";
import { DeleteTermUseCase } from "../../feature/terms/usecases/DeleteTerm.usecase";
import { ListTermUseCase } from "../../feature/terms/usecases/ListTerm.usecase";
import { UpdateTermUseCase } from "../../feature/terms/usecases/UpdateTerm.usecase";
import { TransactionRepo } from "../../feature/transactions/transaction.repo";
import { TutorialRepo } from "../../feature/tutorial/domain/Tutorial.repo";
import { AddTutorialUseCase } from "../../feature/tutorial/useCases/AddTutorial.usecase";
import { DeleteTutorialUseCase } from "../../feature/tutorial/useCases/DeleteTutorial.usecase";
import { ListTutorialUseCase } from "../../feature/tutorial/useCases/ListTutorial.usecase";
import { UpdateTutorialUseCase } from "../../feature/tutorial/useCases/UpdateTutorial.usecase";
import { CentralUserRepo } from "../../feature/users/domain/CentralUser.repo";
import { UsersRepo } from "../../feature/users/domain/user.repo";
import { ListUsersUseCase } from "../../feature/users/useCases/ListUsers.usecase";
import { UploadAvatarUseCase } from "../../feature/users/useCases/UploadAvatar.usecase";
import { WeeklyScheduleApplicationService } from "../../feature/weeklySchedule/applications/WeeklySchedule.application.service";
import { GetDraftWeeklyScheduleUseCase } from "../../feature/weeklySchedule/useCases/GetDraftWeeklySchedule.usecase";
import { GetNonDraftWeeklyScheduleUseCase } from "../../feature/weeklySchedule/useCases/GetNonDraftWeeklySchedule.usecase";
import { WeeklySessionApplicationService } from "../../feature/weeklySessions/applicationService/WeeklySession.application.service";
import { WeeklySessionRepo } from "../../feature/weeklySessions/repos/WeeklySession.repo";
import { AddWeeklySessionForClassUseCase } from "../../feature/weeklySessions/useCases/AddWeeklySessionForClass.usecase";
import { AddWeeklySessionForGroupUseCase } from "../../feature/weeklySessions/useCases/AddWeeklySessionForGroup.usecase";
import { DeleteWeeklySessionUseCase } from "../../feature/weeklySessions/useCases/DeleteWeeklySession.usecase";
import { UpdateWeeklySessionForClassUseCase } from "../../feature/weeklySessions/useCases/UpdateWeeklySessionForClass.usecase";
import { UpdateWeeklySessionForGroupUseCase } from "../../feature/weeklySessions/useCases/UpdateWeeklySessionForGroup.usecase";
import { RandomUtils } from "../../helpers/RandomUtils";
import { StringUtils } from "../../helpers/StringUtils";
import { TLanguageEnum } from "../../translation/constants";
import { EventDispatcher } from "../domainEvents/EventDispatcher";
import { HandlerSubscriber } from "../domainEvents/HandlerSubscriber";
import { FileManager } from "../fileManager/FileManager";
import { AlertManagementApplicationService } from "./../../feature/alertManagement/application/alertManagement.application.service";
import { ListUsersForAlertUseCase } from "./../../feature/alertManagement/useCases/listUsersForAlert.usecase";
import { UpdateSecondaryGradesOfGroupUseCase } from "./../../feature/examGrade/useCases/secondary/UpdateSecondaryGradesOfGroup.usecase";
import { GroupApplicationService } from "./../../feature/groupManagement/applicationServices/Group.application.service";
import { AddGroupUseCase } from "./../../feature/groupManagement/useCases/AddGroup.usecase";
import { AssignStudentToGroupUseCase } from "./../../feature/groupManagement/useCases/AssignStudentToGroup.usecase";
import { CheckGroupUseCase } from "./../../feature/groupManagement/useCases/CheckGroup.usecase";
import { GetGroupsOfTeacherUseCase } from "./../../feature/groupManagement/useCases/GetGroupsOfTeacher.usecase";
import { GetStudentsOfGroupUseCase } from "./../../feature/groupManagement/useCases/GetStudentsOfGroup.usecase";
import { GetGroupOverviewUseCase } from "./../../feature/groupManagement/useCases/GroupOverview.usecase";
import { ListTeacherGroupUseCase } from "./../../feature/groupManagement/useCases/ListTeacherGroup.usecase";
import { ListUnenrolledStudentsForGroupUseCase } from "./../../feature/groupManagement/useCases/ListUnenrolledStudentsForGroup.usecase";
import { UnassignStudentFromGroupUseCase } from "./../../feature/groupManagement/useCases/UnassignStudentFromGroup.usecase";
import { ListInvoicesUseCase } from "../../feature/invoices/useCases/listInvoices.usecase";
import { GetAppVersionUseCase } from "./../../feature/masters/useCases/getAllAppsVersion.usecase";
import { UpdateAppVersionUseCase } from "./../../feature/masters/useCases/updateOsVersion.usecase";
import { AddDirectConversationUseCase } from "./../../feature/messages/useCases/AddDirectConversation.usecase";
import { AddGroupConversationUseCase } from "./../../feature/messages/useCases/AddGroupConversation.usecase";
import { AddParticipantsToConversationUseCase } from "./../../feature/messages/useCases/AddParticipantsToConversation.usecase";
import { DeleteMessageUseCase } from "./../../feature/messages/useCases/DeleteMessage.usecase";
import { GetConversationUseCase } from "./../../feature/messages/useCases/getConversation.usecase";
import { ListConversationAttachmentsUseCase } from "./../../feature/messages/useCases/ListConversationAttachments.usecase";
import { ListConversationLinksUseCase } from "./../../feature/messages/useCases/ListConversationLinks.usecase";
import { ListConversationMessagesUseCase } from "./../../feature/messages/useCases/ListConversationMessages.usecase";
import { ListConversationMultimediaUseCase } from "./../../feature/messages/useCases/ListConversationMultimedia.usecase";
import { FindUsersByFullNameUseCase } from "./../../feature/messages/useCases/ListTargetUsers.usecase";
import { ListTargetUsersForGroupConversationAssignmentUseCase } from "./../../feature/messages/useCases/ListTargetUsersForGroupConversationAssignment.usecase";
import { RemoveParticipantsFromConversationUseCase } from "./../../feature/messages/useCases/RemoveParticipantsFromConversation.usecase";
import { UpdateConversationNameUseCase } from "./../../feature/messages/useCases/UpdateConversationName.usecase";
import { UpdateConversationSeenStatusUseCase } from "./../../feature/messages/useCases/UpdateConversationSeenStatus.usecase";
import { BankCheckStrategy } from "./../../feature/payment/strategies/bankCheckStrategy";
import { BankTransferStrategy } from "./../../feature/payment/strategies/bankTransferStrategy";
import { CashPaymentStrategy } from "./../../feature/payment/strategies/cashPaymentStrategy";
import { PayInvoiceUseCase } from "./../../feature/payment/useCases/payInvoice.usecase";
import { UpdateBankTransferUseCase } from "./../../feature/payment/useCases/updateBankTransfer.usecase";
import { AddPaymentTemplateUseCase } from "./../../feature/paymentTemplate/usecases/addPaymentTemplate.usecase";
import { GetPaymentTemplateUseCase } from "./../../feature/paymentTemplate/usecases/getPaymentTemplate.usecase";
import { UpdatePaymentTemplateUseCase } from "./../../feature/paymentTemplate/usecases/updatePaymentTemplate.usecase";
import { ApplyWeeklyScheduleForGroupUseCase } from "./../../feature/schedules/useCases/ApplyWeeklyScheduleForGroup.usecase";
import { School } from "./../../feature/schools/domain/school.entity";
import { CancelSessionUseCase } from "./../../feature/sessionManagement/useCases/cancelSession.usecase";
import { CloseSessionUseCase } from "./../../feature/sessionManagement/useCases/closeSession.usecase";
import { ConfirmAttendanceUseCase } from "./../../feature/sessionManagement/useCases/confirmAttendance.usecase";
import { StartSessionUseCase } from "./../../feature/sessionManagement/useCases/startSession.usecase";
import { UpdateSessionStatusUseCase } from "./../../feature/sessionManagement/useCases/updateSessionStatus.usecase";
import { ScheduleGenerator } from "./../../feature/smartCalendar/domain/ScheduleGenerator.interface";
import { AddClassTypeActivityUseCase } from "./../../feature/smartCalendar/useCases/AddClassTypeActivity.usecase";
import { UpdateNotAvailableTimesUseCase } from "./../../feature/smartCalendar/useCases/updateNotAvailableTimes.usecase";
import { SwitchStudentsClassUseCase } from "./../../feature/students/useCases/switchStudentsClass.usecase";
import { AddTeacherPaymentConfigurationUseCase } from "./../../feature/teacherPayment/usecases/addTeacherPaymentConfiguration.usecase";
import { AddTeacherPaymentTransactionUseCase } from "./../../feature/teacherPayment/usecases/addTeacherPaymentTransaction.usecase";
import { DeleteTeacherPaymentTransactionUseCase } from "./../../feature/teacherPayment/usecases/deleteTeacherPaymentTransaction.usecase";
import { GetTeacherPaymentConfigurationUseCase } from "./../../feature/teacherPayment/usecases/getTeacherPaymentConfiguration.usecase";
import { PayTeacherUseCase } from "./../../feature/teacherPayment/usecases/payTeacher.usecase";
import { VerifyAndFetchUsersUseCase } from "./../../feature/users/useCases/verifyUsersExistence.usecase";
import { GetAllCambridgeAnnualGradeReportsOfClassUseCase } from "../../feature/examGrade/useCases/cambridge/GetAllCambridgeAnnualGradeReportsOfClass.usecase";
import { GetStudentCambridgeAnnualGradeReportUseCase } from "../../feature/examGrade/useCases/cambridge/GetStudentCambridgeAnnualGradeReport.usecase";
import { GetIBAnnualAveragesOfClassUseCase } from "../../feature/examGrade/useCases/ib/GetIBAnnualAveragesOfClass.usecase";
import { GetCambridgeAnnualAveragesOfClassUseCase } from "../../feature/examGrade/useCases/cambridge/GetCambridgeAnnualAveragesOfClass.usecase";

export type containerRegistry = {
  //core
  EmailManager: EmailManager;
  FileManager: FileManager;
  SmsManager: SmsManager;
  ScheduleGenerator: ScheduleGenerator;
  RandomUtils: typeof RandomUtils;
  StringUtils: typeof StringUtils;
  Language: TLanguageEnum;
  EventDispatcher: EventDispatcher;
  HandlerSubscriber: HandlerSubscriber;

  // use cases
  GetTeacherOfStudentUseCase: GetTeacherOfStudentUseCase;
  SendReplyUseCase: SendReplyUseCase;
  ForwardIssueUseCaseUseCase: ForwardIssueUseCaseUseCase;
  // use cases
  GetGroupTypesOfChaptersUseCase: GetGroupTypesOfChaptersUseCase;
  ListChapterAttachmentsUseCase: ListChapterAttachmentsUseCase;
  DeleteChapterUseCase: DeleteChapterUseCase;
  UpdateChapterUseCase: UpdateChapterUseCase;
  AddChapterUseCase: AddChapterUseCase;
  GetTopicsOfChaptersByClassTypeUseCase: GetTopicsOfChaptersByClassTypeUseCase;
  GetChaptersByTopicUseCase: GetChaptersByTopicUseCase;
  GetStudentChaptersUseCase: GetStudentChaptersUseCase;
  DeleteChapterAttachmentUseCase: DeleteChapterAttachmentUseCase;
  UpdateChapterAttachmentUseCase: UpdateChapterAttachmentUseCase;
  AddChapterAttachmentUseCase: AddChapterAttachmentUseCase;
  ListObservationReasonsUseCase: ListObservationReasonsUseCase;
  DeleteObservationUseCase: DeleteObservationUseCase;
  UpdateObservationUseCase: UpdateObservationUseCase;
  AddObservationForGroupUseCase: AddObservationForGroupUseCase;
  AddObservationForClassUseCase: AddObservationForClassUseCase;
  ListDocumentsOfStudentsUseCase: ListDocumentsOfStudentsUseCase;
  GetStudentDocumentsQueryUseCase: GetStudentDocumentsQueryUseCase;
  GetTeachersOfStudentUseCase: GetTeachersOfStudentUseCase;
  GetSubjectTypesOfClassUseCase: GetSubjectTypesOfClassUseCase;
  GetGroupsOfStudentUseCase: GetGroupsOfStudentUseCase;
  GetTeacherPaymentDashboardUseCase: GetTeacherPaymentDashboardUseCase;
  AddPaymentTemplateUseCase: AddPaymentTemplateUseCase;
  UnAssignTeacherFromSubSubjectUseCase: UnAssignTeacherFromSubSubjectUseCase;
  UnAssignTeacherFromSubjectUseCase: UnAssignTeacherFromSubjectUseCase;
  AssignTeacherToSubSubjectInClassUseCase: AssignTeacherToSubSubjectInClassUseCase;
  UnassignStudentFromClassUseCase: UnassignStudentFromClassUseCase;
  GetSubjectsOfClassUseCase: GetSubjectsOfClassUseCase;
  UpdateStudentGroupUseCase: UpdateStudentGroupUseCase;
  UpdatePaymentTemplateUseCase: UpdatePaymentTemplateUseCase;
  UnPayTeacherUseCase: UnPayTeacherUseCase;
  PayTeacherUseCase: PayTeacherUseCase;
  GetTeacherPaymentConfigurationUseCase: GetTeacherPaymentConfigurationUseCase;
  AddSessionForGroupUseCase: AddSessionForGroupUseCase;
  UpdateSessionForGroupUseCase: UpdateSessionForGroupUseCase;
  AddWeeklySessionForGroupUseCase: AddWeeklySessionForGroupUseCase;
  DeleteTeacherPaymentTransactionUseCase: DeleteTeacherPaymentTransactionUseCase;
  addTeacherPaymentTransactionUseCase: AddTeacherPaymentTransactionUseCase;
  AddTeacherPaymentConfigurationUseCase: AddTeacherPaymentConfigurationUseCase;
  UpdateGroupTypeUseCase: UpdateGroupTypeUseCase;
  GetGroupsOfTeacherUseCase: GetGroupsOfTeacherUseCase;
  GetTeacherClassAndGroupsUseCase: GetTeacherClassAndGroupsUseCase;
  GetStudentsCodeBarePdfUseCase: GetStudentsCodeBarePdfUseCase;
  GetClassListUseCase: GetClassListUseCase;
  AddGroupTypeUseCase: AddGroupTypeUseCase;
  GetClassDashboardUseCase: GetClassDashboardUseCase;
  AssignStudentToClassUseCase: AssignStudentToClassUseCase;
  ListGroupTypesUseCase: ListGroupTypesUseCase;
  DeleteGroupTypeUseCase: DeleteGroupTypeUseCase;
  MarkSmartScheduleAsErroredUseCase: MarkSmartScheduleAsErroredUseCase;
  ListClassroomsUseCase: ListClassroomsUseCase;
  UpdateTutorialUseCase: UpdateTutorialUseCase;
  DeleteTutorialUseCase: DeleteTutorialUseCase;
  AddTutorialUseCase: AddTutorialUseCase;
  ListTutorialUseCase: ListTutorialUseCase;
  GetSmartSchedulePDFUseCase: GetSmartSchedulePDFUseCase;
  CompleteScheduleGenerationUseCase: CompleteScheduleGenerationUseCase;
  UpdateGroupTeacherUseCase: UpdateGroupTeacherUseCase;
  DeleteGroupUseCase: DeleteGroupUseCase;
  UpdateGroupUseCase: UpdateGroupUseCase;
  ListUnenrolledStudentsForGroupUseCase: ListUnenrolledStudentsForGroupUseCase;
  GetGroupListUseCase: GetGroupListUseCase;
  AddGroupUseCase: AddGroupUseCase;
  UpdateSmartCalendarScheduleUseCase: UpdateSmartCalendarScheduleUseCase;
  ApplySmartCalendarScheduleUseCase: ApplySmartCalendarScheduleUseCase;
  ListSmartCalendarSchedulesUseCase: ListSmartCalendarSchedulesUseCase;
  ApplyWeeklyScheduleForGroupUseCase: ApplyWeeklyScheduleForGroupUseCase;
  CheckGroupUseCase: CheckGroupUseCase;
  GenerateScheduleUseCase: GenerateScheduleUseCase;
  DeleteSmartCalendarScheduleUseCase: DeleteSmartCalendarScheduleUseCase;
  CancelSmartCalendarScheduleUseCase: CancelSmartCalendarScheduleUseCase;
  AssignStudentToGroupUseCase: AssignStudentToGroupUseCase;
  UpdateWeeklySessionForGroupUseCase: UpdateWeeklySessionForGroupUseCase;
  UnassignStudentFromGroupUseCase: UnassignStudentFromGroupUseCase;
  GetLevelsOverviewUseCase: GetLevelsOverviewUseCase;
  AssignTeachersToSubjectsInClassUseCase: AssignTeachersToSubjectsInClassUseCase;
  AddClassUseCase: AddClassUseCase;
  DeleteClassTypeActivityUseCase: DeleteClassTypeActivityUseCase;
  AddClassTypeActivityUseCase: AddClassTypeActivityUseCase;
  GetActivitiesOfClassTypeUseCase: GetActivitiesOfClassTypeUseCase;
  ResetUserPasswordUseCase: ResetUserPasswordUseCase;
  GetOnePreRegistrationUseCase: GetOnePreRegistrationUseCase;
  ListPreRegistrationsUseCase: ListPreRegistrationsUseCase;
  RegisterStudentUseCase: RegisterStudentUseCase;
  DeletePreRegistrationUseCase: DeletePreRegistrationUseCase;
  DeleteExpenseUseCase: DeleteExpenseUseCase;
  UpdateExpenseUseCase: UpdateExpenseUseCase;
  AddExpenseUseCase: AddExpenseUseCase;
  ListTeachersUseCase: ListTeachersUseCase;
  GetStudentAttendanceCertificateUseCase: GetStudentAttendanceCertificateUseCase;
  GetChildrenOfParentUseCase: GetChildrenOfParentUseCase;
  GetAdminByNewIdUseCase: GetAdminByNewIdUseCase;
  ListAdminsUseCase: ListAdminsUseCase;
  GetParentByNewIdUseCase: GetParentByNewIdUseCase;
  ListParentsUseCase: ListParentsUseCase;
  ToggleUserActivationUseCase: ToggleUserActivationUseCase;
  LoginByMasterUseCase: LoginByMasterUseCase;
  LoginUseCase: LoginUseCase;
  LogoutUseCase: LogoutUseCase;
  ResetPasswordUseCase: ResetPasswordUseCase;
  VerifyCodeUseCase: VerifyCodeUseCase;
  ForgetPasswordUseCase: ForgetPasswordUseCase;
  UpdateCurrentUserPasswordUseCase: UpdateCurrentUserPasswordUseCase;
  GetClassDiplomasUseCase: GetClassDiplomasUseCase;
  GetStudentDiplomaUseCase: GetStudentDiplomaUseCase;
  GetCambridgeStudentGradeReportUseCase: GetCambridgeStudentGradeReportUseCase;
  GetPrimaryStudentGradeReportUseCase: GetPrimaryStudentGradeReportUseCase;
  GetSecondaryStudentGradeReportUseCase: GetSecondaryStudentGradeReportUseCase;
  UpdatePreRegistrationUseCase: UpdatePreRegistrationUseCase;
  ListUsersUseCase: ListUsersUseCase;
  AddAlertUseCase: AddAlertUseCase;
  DeleteAlertUseCase: DeleteAlertUseCase;
  ListAlertUseCase: ListAlertUseCase;
  AddWeeklySessionForClassUseCase: AddWeeklySessionForClassUseCase;
  UpdateWeeklySessionForClassUseCase: UpdateWeeklySessionForClassUseCase;
  AddSessionForClassUseCase: AddSessionForClassUseCase;
  UpdateSessionForClassUseCase: UpdateSessionForClassUseCase;
  ApplyWeeklyScheduleForClassUseCase: ApplyWeeklyScheduleForClassUseCase;
  DeleteWeeklySessionUseCase: DeleteWeeklySessionUseCase;
  GetAvailableClassroomUseCase: GetAvailableClassroomUseCase;
  GetAvailableClassroomInWeeklySessionUseCase: GetAvailableClassroomInWeeklySessionUseCase;
  GetEntityScheduleUseCase: GetEntityScheduleUseCase;
  DeleteSessionUseCase: DeleteSessionUseCase;
  UploadAvatarUseCase: UploadAvatarUseCase;
  GetDraftWeeklyScheduleUseCase: GetDraftWeeklyScheduleUseCase;
  GetNonDraftWeeklyScheduleUseCase: GetNonDraftWeeklyScheduleUseCase;
  GetScheduleUseCase: GetScheduleUseCase;
  ImportStudentsUseCase: ImportStudentsUseCase;
  AddTeacherUseCase: AddTeacherUseCase;
  AddParentUseCase: AddParentUseCase;
  AddAdminUseCase: AddAdminUseCase;
  AddStudentUseCase: AddStudentUseCase;
  GetClassTypeUseCase: GetClassTypeUseCase;
  ListSessionTypeUseCase: ListSessionTypeUseCase;
  UpdateSchoolYearUseCase: UpdateSchoolYearUseCase;
  AddSchoolYearUseCase: AddSchoolYearUseCase;
  ReorderExamTypeUseCase: ReorderExamTypeUseCase;
  UpdateExamTypeUseCase: UpdateExamTypeUseCase;
  ReorderSubLevelsUseCase: ReorderSubLevelsUseCase;
  DeleteExamTypeUseCase: DeleteExamTypeUseCase;
  ListSectionsUseCase: ListSectionsUseCase;
  AddExamTypeUseCase: AddExamTypeUseCase;
  DeleteClassroomUseCase: DeleteClassroomUseCase;
  UpdateClassroomUseCase: UpdateClassroomUseCase;
  GetStudentsOfGroupUseCase: GetStudentsOfGroupUseCase;
  GetGroupsOfClassUseCase: GetGroupsOfClassUseCase;
  GetStudentsOfClassUseCase: GetStudentsOfClassUseCase;
  ReorderLevelsUseCase: ReorderLevelsUseCase;
  AddClassroomUseCase: AddClassroomUseCase;
  DeleteSessionTypeUseCase: DeleteSessionTypeUseCase;
  UpdateSessionTypeUseCase: UpdateSessionTypeUseCase;
  AddSessionTypeUseCase: AddSessionTypeUseCase;
  ListTermUseCase: ListTermUseCase;
  DeleteTermUseCase: DeleteTermUseCase;
  UpdateTermUseCase: UpdateTermUseCase;
  DeleteSubSubjectTypeUseCase: DeleteSubSubjectTypeUseCase;
  AddTermUseCase: AddTermUseCase;
  EnrichPostsUseCase: EnrichPostsUseCase;
  GetAllPostsUseCase: ListAllPostsFeedUseCase;
  GetUserFeedUseCase: ListUserFeedUseCase;
  EnrichOnePostUseCase: EnrichOnePostUseCase;
  EnrichOneCommentUseCase: EnrichOneCommentUseCase;
  ListCommentsOfPostUseCase: ListCommentsOfPostUseCase;
  ListRepliesOfCommentUseCase: ListRepliesOfCommentUseCase;
  ListIssuesOfAdminUseCase: ListIssuesOfAdminUseCase;
  ListIssuesOfTeacherUseCase: ListIssuesOfTeacherUseCase;
  ListIssuesOfParentUseCase: ListIssuesOfParentUseCase;
  ListInteractionsOfIssueUseCase: ListInteractionsOfIssueUseCase;
  ListHomeworkUseCase: ListHomeworkUseCase;
  IncompleteTermUseCase: IncompleteTermUseCase;
  UpdateClassUseCase: UpdateClassUseCase;
  DeleteClassUseCase: DeleteClassUseCase;
  ListObservationsUseCase: ListObservationsUseCase;
  GetSessionDetailsUseCase: GetSessionDetailsUseCase;
  AddMessageUseCase: AddMessageUseCase;
  ListConversationsUseCase: ListConversationsUseCase;
  ListConversationMessagesUseCase: ListConversationMessagesUseCase;
  ListConversationLinksUseCase: ListConversationLinksUseCase;
  ListConversationAttachmentsUseCase: ListConversationAttachmentsUseCase;
  ListConversationMultimediaUseCase: ListConversationMultimediaUseCase;
  AddDirectConversationUseCase: AddDirectConversationUseCase;
  ReactToMessageUseCase: ReactToMessageUseCase;
  VerifyAndFetchUsersUseCase: VerifyAndFetchUsersUseCase;
  FindUsersByFullNameUseCase: FindUsersByFullNameUseCase;
  GetConversationUseCase: GetConversationUseCase;
  GetOneObservationUseCase: GetOneObservationUseCase;
  ListClassTypeUseCase: ListClassTypeUseCase;
  UpdateClassTypeUseCase: UpdateClassTypeUseCase;
  AddClassTypeUseCase: AddClassTypeUseCase;
  GetSubjectsOfClassTypesUseCase: GetSubjectsOfClassTypesUseCase;
  GetFieldsOfClassTypeUseCase: GetFieldsOfClassTypeUseCase;
  ReorderSubjectInClassTypeUseCase: ReorderSubjectInClassTypeUseCase;
  ReorderSubSubjectInClassTypeUseCase: ReorderSubSubjectInClassTypeUseCase;
  ReorderFieldsOfClassTypesUseCase: ReorderFieldsOfClassTypesUseCase;
  AddSubjectToClassTypeUseCase: AddSubjectToClassTypeUseCase;
  AddSubSubjectToClassTypeUseCase: AddSubSubjectToClassTypeUseCase;
  ListNextClassTypesUseCase: ListNextClassTypesUseCase;
  AddFieldToClasstypeUseCase: AddFieldToClasstypeUseCase;
  ListMastersUseCase: ListMastersUseCase;
  ListTargetUsersForGroupConversationAssignmentUseCase: ListTargetUsersForGroupConversationAssignmentUseCase;
  DeleteMessageUseCase: DeleteMessageUseCase;
  DeleteClassTypeUseCase: DeleteClassTypeUseCase;
  DeleteFieldFromClassTypeUseCase: DeleteFieldFromClassTypeUseCase;
  ListExamTypeUseCase: ListExamTypeUseCase;
  UpdateSubjectFromClassTypeUseCase: UpdateSubjectFromClassTypeUseCase;
  UpdateFieldOfClassTypeUseCase: UpdateFieldOfClassTypeUseCase;
  DeleteLevelUseCase: DeleteLevelUseCase;
  ListRolesUseCase: ListRolesUseCase;
  AddRoleUseCase: AddRoleUseCase;
  UpdateRoleUseCase: UpdateRoleUseCase;
  DeleteSectionUseCase: DeleteSectionUseCase;
  ConfirmAttendanceUseCase: ConfirmAttendanceUseCase;
  AddObservationReasonUsecase: AddObservationReasonUsecase;
  UpdateSubSubjectTypeUsecase: UpdateSubSubjectTypeUsecase;
  AddMasterUseCase: AddMasterUseCase;
  CloseSessionUseCase: CloseSessionUseCase;
  ListSchoolYearUseCase: ListSchoolYearUseCase;
  DeleteHolidayUseCase: DeleteHolidayUseCase;
  ListHolidayUseCase: ListHolidayUseCase;
  AddSchoolUseCase: AddSchoolUseCase;
  UpdateSchoolUseCase: UpdateSchoolUseCase;
  ListTeacherGroupUseCase: ListTeacherGroupUseCase;
  UpdateFlagsUseCase: UpdateFlagsUseCase;
  SwitchToSchoolUsecase: SwitchToSchoolUsecase;
  CancelSessionUseCase: CancelSessionUseCase;
  StartSessionUseCase: StartSessionUseCase;
  AddBarCodeConfigUseCase: AddBarCodeConfigUseCase;
  UpdateBarCodeConfigUseCase: UpdateBarCodeConfigUseCase;
  DeleteBarCodeConfigUseCase: DeleteBarCodeConfigUseCase;
  ListBarCodeConfigUseCase: ListBarCodeConfigUseCase;
  AddSignatureUseCase: AddSignatureUseCase;
  UpdateSignatureUseCase: UpdateSignatureUseCase;
  DeleteSignatureUseCase: DeleteSignatureUseCase;
  ListSignaturesUseCase: ListSignaturesUseCase;
  GetSchoolDetailsUseCase: GetSchoolDetailsUseCase;
  ListInvoicesUseCase: ListInvoicesUseCase;
  SwitchStudentsClassUseCase: SwitchStudentsClassUseCase;
  GetGradesOfFieldUseCase: GetGradesOfFieldUseCase;
  UpdateAlertUseCase: UpdateAlertUseCase;
  UpdateBankTransferUseCase: UpdateBankTransferUseCase;
  GetDashboardUseCase: GetDashboardUseCase;
  SwitchLevelToNextSchoolYearUseCase: SwitchLevelToNextSchoolYearUseCase;
  AddGradeReportTemplateUseCase: AddGradeReportTemplateUseCase;
  ListGradeReportTemplateUseCase: ListGradeReportTemplateUseCase;
  UpdateGradeReportTemplateUseCase: UpdateGradeReportTemplateUseCase;
  DeleteGradeReportTemplateUseCase: DeleteGradeReportTemplateUseCase;
  UpdateTeacherConstraintsUseCase: UpdateTeacherConstraintsUseCase;
  UpdateClassTypeActivityUseCase: UpdateClassTypeActivityUseCase;
  UpdateIBGradesOfGroupUseCase: UpdateIBGradesOfGroupUseCase;
  updateTeacherPaymentConfigurationUseCase: UpdateTeacherPaymentConfigurationUseCase;
  UpdateIssueStatusUseCase: UpdateIssueStatusUseCase;
  AssignTeacherToIssueUseCase: AssignTeacherToIssueUseCase;
  UnAssignTeacherFromIssueUseCase: UnAssignTeacherFromIssueUseCase;
  //services
  NotificationSettingsService: NotificationSettingsService;
  SupplierService: SupplierService;
  SessionService: SessionService;
  HomeworkService: HomeworkService;
  ClassService: ClassService;
  DiplomaService: DiplomaService;
  GetOneHomeworkUseCase: GetOneHomeworkUseCase;
  GetOneIssueUseCase: GetOneIssueUseCase;
  AddGroupConversationUseCase: AddGroupConversationUseCase;
  AddParticipantsToConversationUseCase: AddParticipantsToConversationUseCase;
  RemoveParticipantsFromConversationUseCase: RemoveParticipantsFromConversationUseCase;
  UpdateConversationNameUseCase: UpdateConversationNameUseCase;
  UpdateConversationSeenStatusUseCase: UpdateConversationSeenStatusUseCase;
  ListConversationParticipantsUseCase: ListConversationParticipantsUseCase;
  GetMessageReactionsUseCase: GetMessageReactionsUseCase;
  UpdateSubSubjectOfClassTypeUseCase: UpdateSubSubjectOfClassTypeUseCase;
  ListSubSubjectTypeUseCase: ListSubSubjectTypeUseCase;
  AddSectionUseCase: AddSectionUseCase;
  AddLevelUseCase: AddLevelUseCase;
  UpdateLevelUseCase: UpdateLevelUseCase;
  DeleteSubjectFromClassTypeUseCase: DeleteSubjectFromClassTypeUseCase;
  DeleteSubSubjectFromClassTypeUseCase: DeleteSubSubjectFromClassTypeUseCase;
  UpdateSectionUseCase: UpdateSectionUseCase;
  AddSubLevelUseCase: AddSubLevelUseCase;
  UpdateSubLevelUseCase: UpdateSubLevelUseCase;
  DeleteSubLevelUseCase: DeleteSubLevelUseCase;
  UpdateObservationReasonUseCase: UpdateObservationReasonUseCase;
  GetOneRoleUseCase: GetOneRoleUseCase;
  DeleteRoleUseCase: DeleteRoleUseCase;
  DeleteObservationReasonUseCase: DeleteObservationReasonUseCase;
  AddSubjectTypeUseCase: AddSubjectTypeUseCase;
  UpdateSubjectTypeUseCase: UpdateSubjectTypeUseCase;
  DeleteSubjectTypeUseCase: DeleteSubjectTypeUseCase;
  AddSubSubjectTypeUseCase: AddSubSubjectTypeUseCase;
  AddHolidayUseCase: AddHolidayUseCase;
  UpdateHolidayUseCase: UpdateHolidayUseCase;
  UpdateMasterUseCase: UpdateMasterUseCase;
  DeleteMasterUseCase: DeleteMasterUseCase;
  ListSchoolsUseCase: ListSchoolsUseCase;
  ListClassesUseCase: ListClassesUseCase;
  ListClassesByTeacherUseCase: ListClassesByTeacherUseCase;
  UpdateSessionDetailsUseCase: UpdateSessionDetailsUseCase;
  UpdateAppVersionUseCase: UpdateAppVersionUseCase;
  GetAllAppsVersionUseCase: GetAppVersionUseCase;
  ArchiveStudentUseCase: ArchiveStudentUseCase;
  ArchiveTeacherUseCase: ArchiveTeacherUseCase;
  ArchiveParentUseCase: ArchiveParentUseCase;
  ArchiveAdminUseCase: ArchiveAdminUseCase;
  UnArchiveAdminUseCase: UnArchiveAdminUseCase;
  UnArchiveParentUseCase: UnArchiveParentUseCase;
  UnArchiveStudentUseCase: UnArchiveStudentUseCase;
  UnArchiveTeacherUseCase: UnArchiveTeacherUseCase;
  GetFieldsOfClassUseCase: GetFieldsOfClassUseCase;
  PayInvoiceUseCase: PayInvoiceUseCase;
  GetSecondarySubjectsOfClassUseCase: GetSecondarySubjectsOfClassUseCase;
  GetGradesOfSecondarySubjectUseCase: GetGradesOfSecondarySubjectUseCase;
  GetCambridgeSubjectsOfClassUseCase: GetCambridgeSubjectsOfClassUseCase;
  GetGradesOfCambridgeSubjectUseCase: GetGradesOfCambridgeSubjectUseCase;
  GetGradesOfSecondaryGroupUseCase: GetGradesOfSecondaryGroupUseCase;
  GetGradesOfCambridgeGroupUsecase: GetGradesOfCambridgeGroupUsecase;
  GetPrimaryAveragesOfClassUsecase: GetPrimaryAveragesOfClassUsecase;
  GetSecondaryAveragesOfClassUsecase: GetSecondaryAveragesOfClassUsecase;
  GetCambridgeAveragesOfClassUsecase: GetCambridgeAveragesOfClassUsecase;
  GetPrimaryBlankExamPageUsecase: GetPrimaryBlankExamPageUsecase;
  GetCambridgeBlankExamPageUsecase: GetCambridgeBlankExamPageUsecase;
  GetSecondaryBlankExamPageUsecase: GetSecondaryBlankExamPageUsecase;
  GetAllPrimaryGradeReportsOfClassUseCase: GetAllPrimaryGradeReportsOfClassUseCase;
  GetAllSecondaryGradeReportsOfClassUseCase: GetAllSecondaryGradeReportsOfClassUseCase;
  GetAllCambridgeGradeReportsOfClassUseCase: GetAllCambridgeGradeReportsOfClassUseCase;
  GetPrimaryGradeReportStatsUseCase: GetPrimaryGradeReportStatsUseCase;
  GetSecondaryGradeReportStatsUseCase: GetSecondaryGradeReportStatsUseCase;
  CompleteTermUseCase: CompleteTermUseCase;
  UpdatePrimaryGradesUseCase: UpdatePrimaryGradesUseCase;
  UpdateSecondaryGradesUseCase: UpdateSecondaryGradesUseCase;
  UpdateCambridgeGradesUseCase: UpdateCambridgeGradesUseCase;
  UpdateSecondaryGradesOfGroupUseCase: UpdateSecondaryGradesOfGroupUseCase;
  UpdateCambridgeGradesOfGroupUseCase: UpdateCambridgeGradesOfGroupUseCase;
  GetPrimaryChildGradeReportUseCase: GetPrimaryChildGradeReportUseCase;
  GetSecondaryChildGradeReportUseCase: GetSecondaryChildGradeReportUseCase;
  GetCambridgeChildGradeReportUseCase: GetCambridgeChildGradeReportUseCase;
  GetClassOverviewUseCase: GetClassOverviewUseCase;
  GetGroupOverviewUseCase: GetGroupOverviewUseCase;
  PublishTermUseCase: PublishTermUseCase;
  HideTermUseCase: HideTermUseCase;
  GetAnnualAveragesOfClassUseCase: GetAnnualAveragesOfClassUseCase;
  UpdateSmsSoldUseCase: UpdateSmsSoldUseCase;
  ListUsersForAlertUseCase: ListUsersForAlertUseCase;
  GetAlertDetailsUseCase: GetAlertDetailsUseCase;
  GetPrimaryAnnualGradeReportOfStudentUsecase: GetPrimaryAnnualGradeReportOfStudentUsecase;
  GetAllPrimaryAnnualGradeReportOfClassUsecase: GetAllPrimaryAnnualGradeReportOfClassUsecase;
  UpdateStudentPromotionStatusUsecase: UpdateStudentPromotionStatusUsecase;
  ListSmsSoldHistoriesUseCase: ListSmsSoldHistoriesUseCase;
  GetLevelDegreesCoverageUsecase: GetLevelDegreesCoverageUsecase;
  GetNotPromotedStudentsUsecase: GetNotPromotedStudentsUsecase;
  GetStudentProfileUseCase: GetStudentProfileUseCase;
  GetTeacherProfileUsecase: GetTeacherProfileUsecase;
  GetSchoolAvailableTimeConstraintsUseCase: GetSchoolAvailableTimeConstraintsUseCase;
  UpdateNotAvailableTimesUseCase: UpdateNotAvailableTimesUseCase;
  UpdateAdminUseCase: UpdateAdminUseCase;
  UpdateStudentUseCase: UpdateStudentUseCase;
  UpdateParentUseCase: UpdateParentUseCase;
  UpdateTeacherUseCase: UpdateTeacherUseCase;
  UpdateBankCheckUseCase: UpdateBankCheckUseCase;
  UpdateClassConstraintsUseCase: UpdateClassConstraintsUseCase;
  SwitchToUserUseCase: SwitchToUserUseCase;
  ResendInvitationUseCase: ResendInvitationUseCase;
  DeletePaymentTemplateUseCase: DeletePaymentTemplateUseCase;
  GetPaymentTemplateUseCase: GetPaymentTemplateUseCase;
  GetIBSubjectsOfClassUseCase: GetIBSubjectsOfClassUseCase;
  GetGradesOfIBSubjectUseCase: GetGradesOfIBSubjectUseCase;
  GetGradesOfIBGroupUseCase: GetGradesOfIBGroupUsecase;
  GetIBBlankExamPageUsecase: GetIBBlankExamPageUsecase;
  GetIBAveragesOfClassUsecase: GetIBAveragesOfClassUsecase;
  GetIBStudentGradeReportUseCase: GetIBStudentGradeReportUseCase;
  GetAllIBGradeReportsOfClassUseCase: GetAllIBGradeReportsOfClassUseCase;
  GetIBChildGradeReportUseCase: GetIBChildGradeReportUseCase;
  UpdateIBGradesOfClassUseCase: UpdateIBGradesOfClassUseCase;
  GetIBAdminObservationsUseCase: GetIBAdminObservationsUseCase;
  AddIssueUseCase: AddIssueUseCase;
  UpdateAdminObservationsUseCase: UpdateAdminObservationsUseCase;
  GetAllCambridgeAnnualGradeReportsOfClassUseCase: GetAllCambridgeAnnualGradeReportsOfClassUseCase;
  GetStudentCambridgeAnnualGradeReportUseCase: GetStudentCambridgeAnnualGradeReportUseCase;
  GetIBAnnualAveragesOfClassUseCase: GetIBAnnualAveragesOfClassUseCase;
  GetCambridgeAnnualAveragesOfClassUseCase: GetCambridgeAnnualAveragesOfClassUseCase;

  // Application services
  SessionApplicationService: SessionApplicationService;
  HomeworkApplicationService: HomeworkApplicationService;
  UpdateSessionStatusUseCase: UpdateSessionStatusUseCase;
  ScheduleApplicationService: ScheduleApplicationService;
  WeeklyScheduleApplicationService: WeeklyScheduleApplicationService;
  WeeklySessionApplicationService: WeeklySessionApplicationService;
  GroupApplicationService: GroupApplicationService;
  StudentApplicationService: StudentApplicationService;
  AlertManagementApplicationService: AlertManagementApplicationService;
  AdminApplicationService: AdminApplicationService;

  //factories
  PaymentStrategyFactory: PaymentStrategyFactory;
  SmartCalendarConfigFactory: SmartCalendarConfigFactory;

  //repos
  SignatureRepo: SignatureRepo;
  ChapterRepo: ChapterRepo;
  ChapterAttachmentRepo: ChapterAttachmentRepo;
  TutorialRepo: TutorialRepo;
  SmartCalendarSessionRepo: SmartCalendarSessionRepo;
  SmartCalendarScheduleRepo: SmartCalendarScheduleRepo;
  TeacherPaymentConfigurationRepo: TeacherPaymentConfigurationRepo;
  VerificationCodeRepo: VerificationCodeRepo;
  SmsSoldHistoryRepo: SmsSoldHistoryRepo;
  AlertRepo: AlertRepo;
  BankTransferRepo: BankTransferRepo;
  AppVersionRepo: AppVersionRepo;
  BarCodeRepo: BarCodeConfigRepo;
  HolidayRepo: HolidayRepo;
  TeacherPaymentHistoryRepo: TeacherPaymentHistoryRepo;
  SchoolYearRepo: SchoolYearRepo;
  MessageLinksRepo: MessageLinksRepo;
  SectionRepo: SectionRepo;
  RoleRepo: RoleRepo;
  MasterRepo: MasterRepo;
  ClassGroupRepo: ClassGroupRepo;
  MessageRepo: MessageRepo;
  ConversationRepo: ConversationRepo;
  MessageAttachmentRepo: MessageAttachmentRepo;
  GradeBookObservationRepo: GradeBookObservationRepo;
  WeeklySessionRepo: WeeklySessionRepo;
  ObservationRepo: ObservationRepo;
  TermRepo: TermRepo;
  PostRepo: PostRepo;
  SessionTypeRepo: SessionTypeRepo;
  HomeworkRepo: HomeworkRepo;
  SessionRepo: SessionRepo;
  NotificationRepo: NotificationRepo;
  ClassRepo: ClassRepo;
  ObservationReasonRepo: ObservationReasonRepo;
  PreRegistrationRepo: PreRegistrationRepo;
  PaymentTemplateRepo: PaymentTemplateRepo;
  IssueReasonRepo: IssueReasonRepo;
  DiplomaRepo: DiplomaRepo;
  StudentRepo: StudentRepo;
  ParentRepo: ParentRepo;
  AdminRepo: AdminRepo;
  NotificationSettingsRepo: NotificationSettingsRepo;
  LevelRepo: LevelRepo;
  SubLevelRepo: SubLevelRepo;
  StudentProfileRepo: StudentProfileRepo;
  TeacherRepo: TeacherRepo;
  TransactionRepo: TransactionRepo;
  ClassTypeRepo: ClassTypeRepo;
  CentralUserRepo: CentralUserRepo;
  StudentPaymentConfigurationRepo: StudentPaymentConfigurationRepo;
  UserPostFeedRepo: UserPostFeedRepo;
  SubjectTypesRepo: SubjectTypeRepo;
  GroupTypeRepo: GroupTypeRepo;
  SubjectTypeRepo: SubjectTypeRepo;
  TeacherProfileRepo: TeacherProfileRepo;
  SchoolRepo: SchoolRepo;
  SupplierRepo: SupplierRepo;
  BankCheckRepo: BankCheckRepo;
  ClassroomRepo: ClassroomRepo;
  ServiceRepo: ServiceRepo;
  GroupRepo: GroupRepo;
  ExpenseRepo: ExpenseRepo;
  SubSubjectTypeRepo: SubSubjectTypesRepo;
  InteractionRepo: InteractionRepo;
  IssueRepo: IssueRepo;
  ReactionRepo: ReactionRepo;
  CommentRepo: CommentRepo;
  UsersRepo: UsersRepo;
  ExamGradeRepo: ExamGradeRepo;
  ExamTypeRepo: ExamTypeRepo;
  InvoiceRepo: InvoiceRepo;
  SecondaryClassGradesRepo: SecondaryClassGradesRepo;
  PrimaryClassGradesRepo: PrimaryClassGradesRepo;
  CambridgeClassGradesRepo: CambridgeClassGradesRepo;
  IBClassGradesRepo: IBClassGradesRepo;
  GradeReportTemplateRepo: GradeReportTemplateRepo;
  AutomaticPromotionGradesRepo: AutomaticPromotionGradesRepo;

  // factories
  ClassGradeFactory: ClassGradeFactory;

  // payment strategies
  CashPaymentStrategy: CashPaymentStrategy;
  BankCheckStrategy: BankCheckStrategy;
  BankTransferStrategy: BankTransferStrategy;

  // request constants
  School: School;
  Connection: Connection;
  Session: ClientSession | undefined;

  // constants
  MasterConnection: Connection;
};
