import { GetTeacherOfStudentUseCase } from './../../feature/issues/usecases/GetTeacherOfStudent.usecase';
import { SendReplyUseCase } from './../../feature/issues/usecases/SendReply.usecase';
import { AddAdminUseCase } from "../../feature/admins/useCases/AddAdmin.usecase";
import { GetAdminByNewIdUseCase } from "../../feature/admins/useCases/GetAdminByNewId.usecase";
import { GetDashboardUseCase } from "../../feature/admins/useCases/getDashboard.usecase";
import { ListAdminsUseCase } from "../../feature/admins/useCases/ListAdmins.usecase";
import { UpdateAdminUseCase } from "../../feature/admins/useCases/UpdateAdmin.usecase";
import { AddAlertUseCase } from "../../feature/alertManagement/useCases/AddAlert.usecase";
import { DeleteAlertUseCase } from "../../feature/alertManagement/useCases/DeleteAlert.usecase";
import { GetAlertDetailsUseCase } from "../../feature/alertManagement/useCases/GetAlertDetails.usecase";
import { ListAlertUseCase } from "../../feature/alertManagement/useCases/ListAlert.usecase";
import { ListSmsSoldHistoriesUseCase } from "../../feature/alertManagement/useCases/listSmsSoldHistories.usecase";
import { UpdateAlertUseCase } from "../../feature/alertManagement/useCases/UpdateAlert.usecase";
import { EnrichOneCommentUseCase } from "../../feature/announcements/useCases/EnrichOneComment.usecase";
import { EnrichOnePostUseCase } from "../../feature/announcements/useCases/EnrichOnePost.usecase";
import { EnrichPostsUseCase } from "../../feature/announcements/useCases/EnrichPosts.usecase";
import { ListAllPostsFeedUseCase } from "../../feature/announcements/useCases/ListAllPostsFeed.usecase";
import { ListCommentsOfPostUseCase } from "../../feature/announcements/useCases/ListCommentsOfPost.usecase";
import { ListRepliesOfCommentUseCase } from "../../feature/announcements/useCases/ListRepliesOfComment.usecase";
import { ListUserFeedUseCase } from "../../feature/announcements/useCases/ListUserFeed.usecase";
import { ArchiveAdminUseCase } from "../../feature/archive/useCases/archiveAdmin.usecase";
import { ArchiveParentUseCase } from "../../feature/archive/useCases/archiveParent.usecase";
import { ArchiveStudentUseCase } from "../../feature/archive/useCases/archiveStudent.usecase";
import { ArchiveTeacherUseCase } from "../../feature/archive/useCases/archiveTeacher.usecase";
import { UnArchiveAdminUseCase } from "../../feature/archive/useCases/unarchiveAdmin.usecase";
import { UnArchiveParentUseCase } from "../../feature/archive/useCases/unarchiveParent.usecase";
import { UnArchiveStudentUseCase } from "../../feature/archive/useCases/unarchiveStudent.usecase";
import { UnArchiveTeacherUseCase } from "../../feature/archive/useCases/unarchiveTeacher.usecase";
import { ForgetPasswordUseCase } from "../../feature/authentication/useCases/ForgetPassowrd.usecase";
import { LoginUseCase } from "../../feature/authentication/useCases/Login.usecase";
import { LoginByMasterUseCase } from "../../feature/authentication/useCases/LoginByMaster.usecase";
import { LogoutUseCase } from "../../feature/authentication/useCases/Logout.usecase";
import { ResendInvitationUseCase } from "../../feature/authentication/useCases/ResendInvitation.usecase";
import { ResetPasswordUseCase } from "../../feature/authentication/useCases/ResetPassword.usecase";
import { ResetUserPasswordUseCase } from "../../feature/authentication/useCases/ResetUserPassword.usecase";
import { SwitchToUserUseCase } from "../../feature/authentication/useCases/SwitchToUser.usecase";
import { UpdateCurrentUserPasswordUseCase } from "../../feature/authentication/useCases/UpdateCurrentUserPassword.usecase";
import { VerifyCodeUseCase } from "../../feature/authentication/useCases/VerifyCode.usecase";
import { AddRoleUseCase } from "../../feature/authorization/useCases/AddRole.usecase";
import { DeleteRoleUseCase } from "../../feature/authorization/useCases/DeleteRole.usecase";
import { GetOneRoleUseCase } from "../../feature/authorization/useCases/GetOneRole.usecase";
import { ListRolesUseCase } from "../../feature/authorization/useCases/ListRoles.usecase";
import { UpdateRoleUseCase } from "../../feature/authorization/useCases/UpdateRole.usecase";
import { AddBarCodeConfigUseCase } from "../../feature/barCode/useCases/AddBarCodeConfig.usecase";
import { DeleteBarCodeConfigUseCase } from "../../feature/barCode/useCases/DeleteBarCodeConfig.usecase";
import { ListBarCodeConfigUseCase } from "../../feature/barCode/useCases/ListBarCodeConfig.usecase";
import { UpdateBarCodeConfigUseCase } from "../../feature/barCode/useCases/UpdateBarCodeConfig.usecase";
import { DeleteSignatureUseCase } from "../../feature/signatures/useCases/DeleteSignature.usecase";
import { AddClassUseCase } from "../../feature/classes/useCases/AddClass.usecase";
import { AssignStudentToClassUseCase } from "../../feature/classes/useCases/AssignStudentToClass.usecase";
import { AssignTeachersToSubjectsInClassUseCase } from "../../feature/classes/useCases/AssignTeacherToSubjectInClass.usecase";
import { AssignTeacherToSubSubjectInClassUseCase } from "../../feature/classes/useCases/AssignTeacherToSubSubjectInClass.usecase";
import { DeleteClassUseCase } from "../../feature/classes/useCases/DeleteClass.usecase";
import { GetClassDashboardUseCase } from "../../feature/classes/useCases/GetClassDashboard.usecase";
import { GetClassListUseCase } from "../../feature/classes/useCases/GetClassList.usecase";
import { GetClassOverviewUseCase } from "../../feature/classes/useCases/GetClassOverview.usecase";
import { GetGroupsOfClassUseCase } from "../../feature/classes/useCases/GetGroupsOfClass.usecase";
import { GetStudentsCodeBarePdfUseCase } from "../../feature/classes/useCases/GetStudentsCodeBarePdf.usecase";
import { GetStudentsOfClassUseCase } from "../../feature/classes/useCases/GetStudentsOfClass.usecase";
import { GetSubjectTypesOfClassUseCase } from "../../feature/classes/useCases/GetSubjectTypesOfClass.usecase";
import { GetTeacherClassAndGroupsUseCase } from "../../feature/classes/useCases/GetTeacherClassAndGroups.usecase";
import { ListClassesUseCase } from "../../feature/classes/useCases/ListClasses.usecase";
import { ListClassesByTeacherUseCase } from "../../feature/classes/useCases/ListClassesByTeacher.usecase";
import { UpdateClassUseCase } from "../../feature/classes/useCases/UpdateClass.usecase";
import { DeleteClassroomUseCase } from "../../feature/classrooms/useCases/DeleteClassroom.usecase";
import { GetAvailableClassroomUseCase } from "../../feature/classrooms/useCases/GetAvailableClassroom.usecase";
import { GetAvailableClassroomInWeeklySessionUseCase } from "../../feature/classrooms/useCases/GetAvailableClassroomInWeeklySession.usecase";
import { ListClassroomsUseCase } from "../../feature/classrooms/useCases/ListClassrooms.usecase";
import { UpdateClassroomUseCase } from "../../feature/classrooms/useCases/UpdateClassroom.usecase";
import { AddClassTypeUseCase } from "../../feature/classTypes/useCases/addClassTypes.usecase";
import { AddFieldToClasstypeUseCase } from "../../feature/classTypes/useCases/AddFieldToClasstype.usecase";
import { AddSubjectToClassTypeUseCase } from "../../feature/classTypes/useCases/AddSubjectToClassType.usecase";
import { AddSubSubjectToClassTypeUseCase } from "../../feature/classTypes/useCases/AddSubSubjectToClassType.usecase";
import { DeleteClassTypeUseCase } from "../../feature/classTypes/useCases/DeleteClassType.usecase";
import { DeleteFieldFromClassTypeUseCase } from "../../feature/classTypes/useCases/DeleteFieldFromClassType.usecase";
import { DeleteSubjectFromClassTypeUseCase } from "../../feature/classTypes/useCases/DeleteSubjectFromClassType.usecase";
import { DeleteSubSubjectFromClassTypeUseCase } from "../../feature/classTypes/useCases/DeleteSubSubjectFromClassType.usecase";
import { GetClassTypeUseCase } from "../../feature/classTypes/useCases/GetClassType.usecase";
import { GetFieldsOfClassTypeUseCase } from "../../feature/classTypes/useCases/GetFieldsOfClassTypes.usecase";
import { GetSubjectsOfClassTypesUseCase } from "../../feature/classTypes/useCases/GetSubjectsOfClassTypes.usecase";
import { ListClassTypeUseCase } from "../../feature/classTypes/useCases/ListClassTypes.usecase";
import { ListNextClassTypesUseCase } from "../../feature/classTypes/useCases/ListNextClassTypes.usecase";
import { ReorderFieldsOfClassTypesUseCase } from "../../feature/classTypes/useCases/ReorderFieldsOfClassType.usecase";
import { ReorderSubjectInClassTypeUseCase } from "../../feature/classTypes/useCases/ReorderSubjectInClassType.usecase";
import { ReorderSubSubjectInClassTypeUseCase } from "../../feature/classTypes/useCases/ReorderSubSubjectInClassType.usecase";
import { UpdateClassTypeUseCase } from "../../feature/classTypes/useCases/updateClassTypes.usecase";
import { UpdateFieldOfClassTypeUseCase } from "../../feature/classTypes/useCases/UpdateFieldOfClassType.usecase";
import { UpdateSubjectFromClassTypeUseCase } from "../../feature/classTypes/useCases/UpdateSubjectOfClassType.usecase";
import { UpdateSubSubjectOfClassTypeUseCase } from "../../feature/classTypes/useCases/UpdateSubSubjectOfClassType.usecase";
import { GetStudentDocumentsQueryUseCase } from "../../feature/documents/useCases/GetStudentDocumentsQuery.usecase";
import { ListDocumentsOfStudentsUseCase } from "../../feature/documents/useCases/ListDocumentsOfStudents.usecase";
import { GetAllCambridgeGradeReportsOfClassUseCase } from "../../feature/examGrade/useCases/cambridge/GetAllCambridgeGradeReportsOfClass.usecase";
import { GetCambridgeAveragesOfClassUsecase } from "../../feature/examGrade/useCases/cambridge/GetCambridgeAveragesOfClass.usecase";
import { GetCambridgeBlankExamPageUsecase } from "../../feature/examGrade/useCases/cambridge/GetCambridgeBlankExamPage.usecase";
import { GetCambridgeChildGradeReportUseCase } from "../../feature/examGrade/useCases/cambridge/GetCambridgeChildGradeReport.usecase";
import { GetCambridgeStudentGradeReportUseCase } from "../../feature/examGrade/useCases/cambridge/GetCambridgeStudentGradeReport.usecase";
import { GetCambridgeSubjectsOfClassUseCase } from "../../feature/examGrade/useCases/cambridge/GetCambridgeSubjectsOfClass.usecase";
import { GetGradesOfCambridgeGroupUsecase } from "../../feature/examGrade/useCases/cambridge/GetGradesOfCambridgeGroup.usecase";
import { GetGradesOfCambridgeSubjectUseCase } from "../../feature/examGrade/useCases/cambridge/GetGradesOfCambridgeSubject.usecase";
import { UpdateCambridgeGradesUseCase } from "../../feature/examGrade/useCases/cambridge/UpdateCambridgeGrades.usecase";
import { UpdateCambridgeGradesOfGroupUseCase } from "../../feature/examGrade/useCases/cambridge/UpdateCambridgeGradesOfGroup.usecase";
import { CompleteTermUseCase } from "../../feature/examGrade/useCases/CompleteTerm.usecase";
import { GetAnnualAveragesOfClassUseCase } from "../../feature/examGrade/useCases/GetAnnualAveragesOfClass.usecase";
import { GetClassDiplomasUseCase } from "../../feature/examGrade/useCases/GetClassDiplomas.usecase";
import { GetLevelDegreesCoverageUsecase } from "../../feature/examGrade/useCases/GetLevelDegreesCoverage.usecase";
import { GetNotPromotedStudentsUsecase } from "../../feature/examGrade/useCases/getNotPromotedStudentsOfLevel.usecase";
import { GetStudentDiplomaUseCase } from "../../feature/examGrade/useCases/GetStudentDiploma.usecase";
import { HideTermUseCase } from "../../feature/examGrade/useCases/HideTerm.usecase";
import { GetAllIBGradeReportsOfClassUseCase } from "../../feature/examGrade/useCases/ib/GetAllIBGradeReportsOfClass.usecase";
import { GetGradesOfIBGroupUsecase } from "../../feature/examGrade/useCases/ib/GetGradesOfIBGroup.usecase";
import { GetGradesOfIBSubjectUseCase } from "../../feature/examGrade/useCases/ib/GetGradesOfIBSubject.usecase";
import { GetIBAdminObservationsUseCase } from "../../feature/examGrade/useCases/ib/GetIBAdminObservations.usecase";
import { GetIBAveragesOfClassUsecase } from "../../feature/examGrade/useCases/ib/GetIBAveragesOfClass.usecase";
import { GetIBBlankExamPageUsecase } from "../../feature/examGrade/useCases/ib/GetIBBlankExamPage.usecase";
import { GetIBChildGradeReportUseCase } from "../../feature/examGrade/useCases/ib/GetIBChildGradeReport.usecase";
import { GetIBStudentGradeReportUseCase } from "../../feature/examGrade/useCases/ib/GetIBStudentGradeReport.usecase";
import { GetIBSubjectsOfClassUseCase } from "../../feature/examGrade/useCases/ib/GetIBSubjectsOfClass.usecase";
import { UpdateAdminObservationsUseCase } from "../../feature/examGrade/useCases/UpdateAdminObservations.usecase";
import { UpdateIBGradesOfClassUseCase } from "../../feature/examGrade/useCases/ib/UpdateIBGradesOfClass.usecase";
import { UpdateIBGradesOfGroupUseCase } from "../../feature/examGrade/useCases/ib/UpdateIBGradesOfGroup.usecase";
import { IncompleteTermUseCase } from "../../feature/examGrade/useCases/IncompleteTerm.usecase";
import { GetAllPrimaryAnnualGradeReportOfClassUsecase } from "../../feature/examGrade/useCases/primary/GetAllPrimaryAnnualGradeReportOfClass.usecase";
import { GetAllPrimaryGradeReportsOfClassUseCase } from "../../feature/examGrade/useCases/primary/GetAllPrimaryGradeReportsOfClass.usecase";
import { GetFieldsOfClassUseCase } from "../../feature/examGrade/useCases/primary/GetFieldsOfClass.usecase";
import { GetGradesOfFieldUseCase } from "../../feature/examGrade/useCases/primary/GetGradesOfField.usecase";
import { GetPrimaryAnnualGradeReportOfStudentUsecase } from "../../feature/examGrade/useCases/primary/GetPrimaryAnnualGradeReportOfStudent.usecase";
import { GetPrimaryAveragesOfClassUsecase } from "../../feature/examGrade/useCases/primary/GetPrimaryAveragesOfClass.usecase";
import { GetPrimaryBlankExamPageUsecase } from "../../feature/examGrade/useCases/primary/GetPrimaryBlankExamPage.usecase";
import { GetPrimaryChildGradeReportUseCase } from "../../feature/examGrade/useCases/primary/GetPrimaryChildGradeReport.usecase";
import { GetPrimaryGradeReportStatsUseCase } from "../../feature/examGrade/useCases/primary/GetPrimaryGradeReportStats.usecase";
import { GetPrimaryStudentGradeReportUseCase } from "../../feature/examGrade/useCases/primary/GetPrimaryStudentGradeReport.usecase";
import { UpdatePrimaryGradesUseCase } from "../../feature/examGrade/useCases/primary/UpdatePrimaryGrades.usecase";
import { PublishTermUseCase } from "../../feature/examGrade/useCases/PublishTerm.usecase";
import { GetAllSecondaryGradeReportsOfClassUseCase } from "../../feature/examGrade/useCases/secondary/GetAllSecondaryGradeReportsOfClass.usecase";
import { GetGradesOfSecondaryGroupUseCase } from "../../feature/examGrade/useCases/secondary/GetGradesOfSecondaryGroup.usecase";
import { GetGradesOfSecondarySubjectUseCase } from "../../feature/examGrade/useCases/secondary/GetGradesOfSecondarySubject.usecase";
import { GetSecondaryAveragesOfClassUsecase } from "../../feature/examGrade/useCases/secondary/GetSecondaryAveragesOfClass.usecase";
import { GetSecondaryBlankExamPageUsecase } from "../../feature/examGrade/useCases/secondary/GetSecondaryBlankExamPage.usecase";
import { GetSecondaryChildGradeReportUseCase } from "../../feature/examGrade/useCases/secondary/GetSecondaryChildGradeReport.usecase";
import { GetSecondaryGradeReportStatsUseCase } from "../../feature/examGrade/useCases/secondary/GetSecondaryGradeReportStats.usecase";
import { GetSecondaryStudentGradeReportUseCase } from "../../feature/examGrade/useCases/secondary/GetSecondaryStudentGradeReport.usecase";
import { GetSecondarySubjectsOfClassUseCase } from "../../feature/examGrade/useCases/secondary/GetSecondarySubjectsOfClass.usecase";
import { UpdateSecondaryGradesUseCase } from "../../feature/examGrade/useCases/secondary/UpdateSecondaryGrades.usecase";
import { UpdateSecondaryGradesOfGroupUseCase } from "../../feature/examGrade/useCases/secondary/UpdateSecondaryGradesOfGroup.usecase";
import { SwitchLevelToNextSchoolYearUseCase } from "../../feature/examGrade/useCases/SwitchLevelToNextSchoolYear.usecase";
import { UpdateStudentPromotionStatusUsecase } from "../../feature/examGrade/useCases/UpdateStudentPromotionStatus.usecase";
import { AddExamTypeUseCase } from "../../feature/examTypes/useCases/AddExamType.usecase";
import { DeleteExamTypeUseCase } from "../../feature/examTypes/useCases/DeleteExamType.usecase";
import { ListExamTypeUseCase } from "../../feature/examTypes/useCases/listExamType.usecase";
import { ReorderExamTypeUseCase } from "../../feature/examTypes/useCases/ReorderExamType.usecase";
import { UpdateExamTypeUseCase } from "../../feature/examTypes/useCases/UpdateExamType.usecase";
import { AddExpenseUseCase } from "../../feature/expenses/useCases/AddExpense.usecase";
import { DeleteExpenseUseCase } from "../../feature/expenses/useCases/DeleteExpense.usecase";
import { UpdateExpenseUseCase } from "../../feature/expenses/useCases/UpdateExpense.usecase";
import { AddGradeReportTemplateUseCase } from "../../feature/gradeReportTemplate/useCases/AddGradeReportTemplate.usecase";
import { DeleteGradeReportTemplateUseCase } from "../../feature/gradeReportTemplate/useCases/DeleteGradeReportTemplate.usecase";
import { ListGradeReportTemplateUseCase } from "../../feature/gradeReportTemplate/useCases/ListGradeReportTemplate.usecase";
import { UpdateGradeReportTemplateUseCase } from "../../feature/gradeReportTemplate/useCases/UpdateGradeReportTemplate.usecase";
import { AddGroupUseCase } from "../../feature/groupManagement/useCases/AddGroup.usecase";
import { AssignStudentToGroupUseCase } from "../../feature/groupManagement/useCases/AssignStudentToGroup.usecase";
import { CheckGroupUseCase } from "../../feature/groupManagement/useCases/CheckGroup.usecase";
import { DeleteGroupUseCase } from "../../feature/groupManagement/useCases/DeleteGroup.usecase";
import { GetGroupListUseCase } from "../../feature/groupManagement/useCases/GetGroupList.usecase";
import { GetGroupsOfStudentUseCase } from "../../feature/groupManagement/useCases/GetGroupsOfStudent.usecase";
import { GetGroupsOfTeacherUseCase } from "../../feature/groupManagement/useCases/GetGroupsOfTeacher.usecase";
import { GetStudentsOfGroupUseCase } from "../../feature/groupManagement/useCases/GetStudentsOfGroup.usecase";
import { GetGroupOverviewUseCase } from "../../feature/groupManagement/useCases/GroupOverview.usecase";
import { ListTeacherGroupUseCase } from "../../feature/groupManagement/useCases/ListTeacherGroup.usecase";
import { ListUnenrolledStudentsForGroupUseCase } from "../../feature/groupManagement/useCases/ListUnenrolledStudentsForGroup.usecase";
import { UnassignStudentFromGroupUseCase } from "../../feature/groupManagement/useCases/UnassignStudentFromGroup.usecase";
import { UpdateGroupUseCase } from "../../feature/groupManagement/useCases/UpdateGroup.usecase";
import { UpdateGroupTeacherUseCase } from "../../feature/groupManagement/useCases/UpdateGroupTeacher.usecase";
import { AddGroupTypeUseCase } from "../../feature/groupType/useCases/AddGroupType.usecase";
import { DeleteGroupTypeUseCase } from "../../feature/groupType/useCases/DeleteGroupType.usecase";
import { ListGroupTypesUseCase } from "../../feature/groupType/useCases/ListGroupTypes.usecase";
import { UpdateGroupTypeUseCase } from "../../feature/groupType/useCases/UpdateGroupType.usecase";
import { AddHolidayUseCase } from "../../feature/holidays/useCases/AddHoliday.usecase";
import { DeleteHolidayUseCase } from "../../feature/holidays/useCases/DeleteHoliday.usecase";
import { ListHolidayUseCase } from "../../feature/holidays/useCases/ListHoliday.usecase";
import { UpdateHolidayUseCase } from "../../feature/holidays/useCases/UpdateHoliday.usecase";
import { GetOneHomeworkUseCase } from "../../feature/homeworks/useCases/GetOneHomework.usecase";
import { ListHomeworkUseCase } from "../../feature/homeworks/useCases/ListHomeworks.usecase";
import { GetOneIssueUseCase } from "../../feature/issues/usecases/getOneIssue.usecase";
import { ListInteractionsOfIssueUseCase } from "../../feature/issues/usecases/listInteractionsOfIssue.usecase";
import { ListIssuesOfAdminUseCase } from "../../feature/issues/usecases/listIssuesOfAdmin.usecase";
import { ListIssuesOfParentUseCase } from "../../feature/issues/usecases/listIssuesOfParent.usecase";
import { ListIssuesOfTeacherUseCase } from "../../feature/issues/usecases/listIssuesOfTeacher.usecase";
import { AddLevelUseCase } from "../../feature/levels/useCases/AddLevel.usecase";
import { DeleteLevelUseCase } from "../../feature/levels/useCases/DeleteLevel.usecase";
import { GetLevelsOverviewUseCase } from "../../feature/levels/useCases/GetLevelsOverview.usecase";
import { ReorderLevelsUseCase } from "../../feature/levels/useCases/ReorderLevels.usecase";
import { UpdateLevelUseCase } from "../../feature/levels/useCases/UpdateLevel.usecase";
import { AddMasterUseCase } from "../../feature/masters/useCases/AddMaster.usecase";
import { DeleteMasterUseCase } from "../../feature/masters/useCases/DeleteMaster.usecase";
import { ListMastersUseCase } from "../../feature/masters/useCases/ListMasters.usecase";
import { UpdateMasterUseCase } from "../../feature/masters/useCases/UpdateMaster.usecase";
import { UpdateAppVersionUseCase } from "../../feature/masters/useCases/updateOsVersion.usecase";
import { AddMessageUseCase } from "../../feature/messages/useCases/AddMessage.usecase";
import { GetMessageReactionsUseCase } from "../../feature/messages/useCases/GetMessageReactions.usercase";
import { ListConversationParticipantsUseCase } from "../../feature/messages/useCases/ListConversationParticipants.usecase";
import { ListConversationsUseCase } from "../../feature/messages/useCases/ListConversations.usecase";
import { ReactToMessageUseCase } from "../../feature/messages/useCases/ReactToMessage.usecase";
import { AddObservationForClassUseCase } from '../../feature/observations/useCases/AddObservationForClass.usecase';
import { AddObservationForGroupUseCase } from '../../feature/observations/useCases/AddObservationForGroup.usecase';
import { DeleteObservationUseCase } from '../../feature/observations/useCases/DeleteObservation.usecase';
import { GetOneObservationUseCase } from '../../feature/observations/useCases/GetOneObservation.usecase';
import { ListObservationsUseCase } from '../../feature/observations/useCases/ListObservations.usecase';
import { UpdateObservationUseCase } from '../../feature/observations/useCases/UpdateObservation.usecase';
import { AddObservationReasonUsecase } from '../../feature/observationsReason/usecases/AddObservationReason.usecase';
import { DeleteObservationReasonUseCase } from '../../feature/observationsReason/usecases/DeleteObservationReason.usecase';
import { ListObservationReasonsUseCase } from '../../feature/observationsReason/usecases/ListObservationReasons.usecase';
import { UpdateObservationReasonUseCase } from '../../feature/observationsReason/usecases/UpdateObservationReason.usecase';
import { AddParentUseCase } from "../../feature/parents/useCases/AddParent.usecase";
import { GetChildrenOfParentUseCase } from "../../feature/parents/useCases/GetChildrenOfParent.usecase";
import { GetParentByNewIdUseCase } from "../../feature/parents/useCases/GetParentByNewId.usecase";
import { ListParentsUseCase } from "../../feature/parents/useCases/ListParents.usecase";
import { UpdateParentUseCase } from "../../feature/parents/useCases/UpdateParent.usecase";
import { UpdateBankTransferUseCase } from "../../feature/payment/useCases/updateBankTransfer.usecase";
import { DeletePreRegistrationUseCase } from "../../feature/preRegistration/useCases/DeletePreRegistration.usecase";
import { GetOnePreRegistrationUseCase } from "../../feature/preRegistration/useCases/GetOnePreRegistration.usecase";
import { ListPreRegistrationsUseCase } from "../../feature/preRegistration/useCases/ListPreRegistrations.usecase";
import { RegisterStudentUseCase } from "../../feature/preRegistration/useCases/RegisterStudent.usecase";
import { UpdatePreRegistrationUseCase } from "../../feature/preRegistration/useCases/UpdatePreRegistration.usecase";
import { ApplyWeeklyScheduleForClassUseCase } from "../../feature/schedules/useCases/ApplyWeeklyScheduleForClass.usecase";
import { ApplyWeeklyScheduleForGroupUseCase } from "../../feature/schedules/useCases/ApplyWeeklyScheduleForGroup.usecase";
import { DeleteSessionUseCase } from "../../feature/schedules/useCases/DeleteSession.usecase";
import { GetEntityScheduleUseCase } from "../../feature/schedules/useCases/GetEntitySchedule.usecase";
import { GetScheduleUseCase } from "../../feature/schedules/useCases/GetSchedule.usecase";
import { AddSchoolUseCase } from "../../feature/schools/useCases/AddSchool.usecase";
import { GetSchoolDetailsUseCase } from "../../feature/schools/useCases/GetSchoolInformation.usecase";
import { ListSchoolsUseCase } from "../../feature/schools/useCases/ListSchools.usecase";
import { SwitchToSchoolUsecase } from "../../feature/schools/useCases/SwitchToSchool.usecase";
import { UpdateFlagsUseCase } from "../../feature/schools/useCases/UpdateFlags.usecase";
import { UpdateSchoolUseCase } from "../../feature/schools/useCases/UpdateSchool.usecase";
import { AddSchoolYearUseCase } from "../../feature/schoolYears/useCases/AddSchoolYear.usecase";
import { ListSchoolYearUseCase } from "../../feature/schoolYears/useCases/ListSchoolYear.usecase";
import { UpdateSchoolYearUseCase } from "../../feature/schoolYears/useCases/UpdateSchoolYear.usecase";
import { AddSectionUseCase } from "../../feature/sections/useCases/AddSection.usecase";
import { DeleteSectionUseCase } from "../../feature/sections/useCases/DeleteSection.usecase";
import { ListSectionsUseCase } from "../../feature/sections/useCases/ListSections.usecase";
import { UpdateSectionUseCase } from "../../feature/sections/useCases/UpdateSection.usecase";
import { AddSessionForClassUseCase } from "../../feature/sessionManagement/useCases/AddSessionForClass.usecase";
import { AddSessionForGroupUseCase } from "../../feature/sessionManagement/useCases/AddSessionForGroup.usecase";
import { GetSessionDetailsUseCase } from "../../feature/sessionManagement/useCases/getSessionDetails.usecase";
import { UpdateSessionDetailsUseCase } from "../../feature/sessionManagement/useCases/updateSessionDetails.usecase";
import { UpdateSessionForClassUseCase } from "../../feature/sessionManagement/useCases/UpdateSessionForClass.usecase";
import { UpdateSessionForGroupUseCase } from "../../feature/sessionManagement/useCases/UpdateSessionForGroup.usecase";
import { AddSessionTypeUseCase } from "../../feature/sessionTypes/usecases/AddSessionType.usecase";
import { DeleteSessionTypeUseCase } from "../../feature/sessionTypes/usecases/DeleteSessionType.usecase";
import { ListSessionTypeUseCase } from "../../feature/sessionTypes/usecases/ListSessionType.usecase";
import { UpdateSessionTypeUseCase } from "../../feature/sessionTypes/usecases/UpdateSessionType.usecase";
import { AddClassTypeActivityUseCase } from "../../feature/smartCalendar/useCases/AddClassTypeActivity.usecase";
import { ApplySmartCalendarScheduleUseCase } from "../../feature/smartCalendar/useCases/ApplySmartCalendarSchedule.usecase";
import { CancelSmartCalendarScheduleUseCase } from "../../feature/smartCalendar/useCases/CancelSmartCalendarSchedule.usecase";
import { CompleteScheduleGenerationUseCase } from "../../feature/smartCalendar/useCases/CompleteScheduleGeneration.usecase";
import { DeleteClassTypeActivityUseCase } from "../../feature/smartCalendar/useCases/DeleteClassTypeActivity.usecase";
import { DeleteSmartCalendarScheduleUseCase } from "../../feature/smartCalendar/useCases/DeleteSmartCalendarSchedule.usecase";
import { GenerateScheduleUseCase } from "../../feature/smartCalendar/useCases/GenerateSchedule.usecase";
import { GetActivitiesOfClassTypeUseCase } from "../../feature/smartCalendar/useCases/GetActivitiesOfClassType.usecase";
import { GetSchoolAvailableTimeConstraintsUseCase } from "../../feature/smartCalendar/useCases/getSchoolAvailableTimeConstraint.usecase";
import { GetSmartSchedulePDFUseCase } from "../../feature/smartCalendar/useCases/GetSmartSchedulePDF.usecase";
import { ListSmartCalendarSchedulesUseCase } from "../../feature/smartCalendar/useCases/ListSmartCalendarSchedules.usecase";
import { MarkSmartScheduleAsErroredUseCase } from "../../feature/smartCalendar/useCases/MarkSmartScheduleAsErrored.usecase";
import { UpdateClassConstraintsUseCase } from '../../feature/smartCalendar/useCases/updateClassConstraints.usecase';
import { UpdateClassTypeActivityUseCase } from "../../feature/smartCalendar/useCases/UpdateClassTypeActivity.usecase";
import { UpdateNotAvailableTimesUseCase } from '../../feature/smartCalendar/useCases/updateNotAvailableTimes.usecase';
import { UpdateSmartCalendarScheduleUseCase } from "../../feature/smartCalendar/useCases/UpdateSmartCalendarSchedule.usecase";
import { UpdateTeacherConstraintsUseCase } from '../../feature/smartCalendar/useCases/updateTeacherConstraints.usecase';
import { UpdateBankCheckUseCase } from "../../feature/studentPayments/useCases/UpdateBankCheck.usecase";
import { AddStudentUseCase } from "../../feature/students/useCases/AddStudent.usecase";
import { GetStudentAttendanceCertificateUseCase } from "../../feature/students/useCases/GetStudentAttendanceCertificate.usecase";
import { GetStudentProfileUseCase } from "../../feature/students/useCases/GetStudentProfile.usecase";
import { ImportStudentsUseCase } from "../../feature/students/useCases/ImportStudents.usecase";
import { ToggleUserActivationUseCase } from "../../feature/students/useCases/ToggleUserActivation.usecase";
import { UpdateStudentUseCase } from "../../feature/students/useCases/UpdateStudent.usecase";
import { AddSubjectTypeUseCase } from "../../feature/subjectTypes/useCases/AddSubjectType.usecase";
import { DeleteSubjectTypeUseCase } from "../../feature/subjectTypes/useCases/DeleteSubjectType.usecase";
import { UpdateSubjectTypeUseCase } from "../../feature/subjectTypes/useCases/UpdateSubjectType.usecase";
import { AddSubLevelUseCase } from "../../feature/subLevels/useCases/AddSubLevel.usecase";
import { DeleteSubLevelUseCase } from "../../feature/subLevels/useCases/DeleteSubLevel.usecase";
import { ReorderSubLevelsUseCase } from "../../feature/subLevels/useCases/ReorderSubLevels.usecase";
import { UpdateSubLevelUseCase } from "../../feature/subLevels/useCases/UpdateSubLevel.usecase";
import { AddSubSubjectTypeUseCase } from "../../feature/subSubjectTypes/usecases/AddSubSubjectType.usecase";
import { DeleteSubSubjectTypeUseCase } from "../../feature/subSubjectTypes/usecases/DeleteSubSubjectType.usecase";
import { ListSubSubjectTypeUseCase } from "../../feature/subSubjectTypes/usecases/ListSubSubjectType.usecase";
import { UpdateSubSubjectTypeUsecase } from "../../feature/subSubjectTypes/usecases/UpdateSubSubjectType.usecase";
import { AddTeacherPaymentConfigurationUseCase } from "../../feature/teacherPayment/usecases/addTeacherPaymentConfiguration.usecase";
import { AddTeacherPaymentTransactionUseCase } from "../../feature/teacherPayment/usecases/addTeacherPaymentTransaction.usecase";
import { DeleteTeacherPaymentTransactionUseCase } from "../../feature/teacherPayment/usecases/deleteTeacherPaymentTransaction.usecase";
import { GetTeacherPaymentConfigurationUseCase } from "../../feature/teacherPayment/usecases/getTeacherPaymentConfiguration.usecase";
import { GetTeacherPaymentDashboardUseCase } from '../../feature/teacherPayment/usecases/getTeacherPaymentDashboard.usecase';
import { UnPayTeacherUseCase } from '../../feature/teacherPayment/usecases/unPayTeacher.usecase';
import { UpdateTeacherPaymentConfigurationUseCase } from "../../feature/teacherPayment/usecases/updateTeacherPaymentConfiguration.usecase";
import { AddTeacherUseCase } from "../../feature/teachers/useCases/AddTeacher.usecase";
import { GetTeacherProfileUsecase } from "../../feature/teachers/useCases/GetTeacherProfile.usecase";
import { GetTeachersOfStudentUseCase } from "../../feature/teachers/useCases/GetTeachersOfStudent.usecase";
import { ListTeachersUseCase } from "../../feature/teachers/useCases/ListTeachers.usecase";
import { UpdateTeacherUseCase } from "../../feature/teachers/useCases/UpdateTeacher.usecase";
import { AddTermUseCase } from "../../feature/terms/usecases/AddTerm.usecase";
import { DeleteTermUseCase } from "../../feature/terms/usecases/DeleteTerm.usecase";
import { ListTermUseCase } from "../../feature/terms/usecases/ListTerm.usecase";
import { UpdateTermUseCase } from "../../feature/terms/usecases/UpdateTerm.usecase";
import { AddTutorialUseCase } from "../../feature/tutorial/useCases/AddTutorial.usecase";
import { DeleteTutorialUseCase } from "../../feature/tutorial/useCases/DeleteTutorial.usecase";
import { ListTutorialUseCase } from "../../feature/tutorial/useCases/ListTutorial.usecase";
import { UpdateTutorialUseCase } from "../../feature/tutorial/useCases/UpdateTutorial.usecase";
import { ListUsersUseCase } from "../../feature/users/useCases/ListUsers.usecase";
import { UploadAvatarUseCase } from "../../feature/users/useCases/UploadAvatar.usecase";
import { GetDraftWeeklyScheduleUseCase } from "../../feature/weeklySchedule/useCases/GetDraftWeeklySchedule.usecase";
import { GetNonDraftWeeklyScheduleUseCase } from "../../feature/weeklySchedule/useCases/GetNonDraftWeeklySchedule.usecase";
import { AddWeeklySessionForClassUseCase } from "../../feature/weeklySessions/useCases/AddWeeklySessionForClass.usecase";
import { AddWeeklySessionForGroupUseCase } from "../../feature/weeklySessions/useCases/AddWeeklySessionForGroup.usecase";
import { DeleteWeeklySessionUseCase } from "../../feature/weeklySessions/useCases/DeleteWeeklySession.usecase";
import { UpdateWeeklySessionForClassUseCase } from "../../feature/weeklySessions/useCases/UpdateWeeklySessionForClass.usecase";
import { UpdateWeeklySessionForGroupUseCase } from "../../feature/weeklySessions/useCases/UpdateWeeklySessionForGroup.usecase";
import { ListUsersForAlertUseCase } from "./../../feature/alertManagement/useCases/listUsersForAlert.usecase";
import { AddClassroomUseCase } from "./../../feature/classrooms/useCases/AddClassroom.usecase";
import { ListInvoicesUseCase } from "../../feature/invoices/useCases/listInvoices.usecase";
import { AssignTeacherToIssueUseCase } from './../../feature/issues/usecases/assignTeacherToIssue.usecase';
import { UnAssignTeacherFromIssueUseCase } from './../../feature/issues/usecases/unassignTeacherFromIssue.usecase';
import { UpdateIssueStatusUseCase } from './../../feature/issues/usecases/updateIssueStatus.usecase';
import { GetAppVersionUseCase } from "./../../feature/masters/useCases/getAllAppsVersion.usecase";
import { AddDirectConversationUseCase } from "./../../feature/messages/useCases/AddDirectConversation.usecase";
import { AddGroupConversationUseCase } from "./../../feature/messages/useCases/AddGroupConversation.usecase";
import { AddParticipantsToConversationUseCase } from "./../../feature/messages/useCases/AddParticipantsToConversation.usecase";
import { DeleteMessageUseCase } from "./../../feature/messages/useCases/DeleteMessage.usecase";
import { GetConversationUseCase } from "./../../feature/messages/useCases/getConversation.usecase";
import { ListConversationAttachmentsUseCase } from "./../../feature/messages/useCases/ListConversationAttachments.usecase";
import { ListConversationLinksUseCase } from "./../../feature/messages/useCases/ListConversationLinks.usecase";
import { ListConversationMessagesUseCase } from "./../../feature/messages/useCases/ListConversationMessages.usecase";
import { ListConversationMultimediaUseCase } from "./../../feature/messages/useCases/ListConversationMultimedia.usecase";
import { FindUsersByFullNameUseCase } from "./../../feature/messages/useCases/ListTargetUsers.usecase";
import { ListTargetUsersForGroupConversationAssignmentUseCase } from "./../../feature/messages/useCases/ListTargetUsersForGroupConversationAssignment.usecase";
import { RemoveParticipantsFromConversationUseCase } from "./../../feature/messages/useCases/RemoveParticipantsFromConversation.usecase";
import { UpdateConversationNameUseCase } from "./../../feature/messages/useCases/UpdateConversationName.usecase";
import { UpdateConversationSeenStatusUseCase } from "./../../feature/messages/useCases/UpdateConversationSeenStatus.usecase";
import { PayInvoiceUseCase } from "./../../feature/payment/useCases/payInvoice.usecase";
import { AddPaymentTemplateUseCase } from './../../feature/paymentTemplate/usecases/addPaymentTemplate.usecase';
import { DeletePaymentTemplateUseCase } from './../../feature/paymentTemplate/usecases/deletePaymentTemplate.usecase';
import { GetPaymentTemplateUseCase } from './../../feature/paymentTemplate/usecases/getPaymentTemplate.usecase';
import { UpdatePaymentTemplateUseCase } from './../../feature/paymentTemplate/usecases/updatePaymentTemplate.usecase';
import { UpdateSmsSoldUseCase } from "./../../feature/schools/useCases/UpdateSmsSold.usecase";
import { CancelSessionUseCase } from "./../../feature/sessionManagement/useCases/cancelSession.usecase";
import { CloseSessionUseCase } from "./../../feature/sessionManagement/useCases/closeSession.usecase";
import { ConfirmAttendanceUseCase } from "./../../feature/sessionManagement/useCases/confirmAttendance.usecase";
import { StartSessionUseCase } from "./../../feature/sessionManagement/useCases/startSession.usecase";
import { UpdateSessionStatusUseCase } from "./../../feature/sessionManagement/useCases/updateSessionStatus.usecase";
import { SwitchStudentsClassUseCase } from "./../../feature/students/useCases/switchStudentsClass.usecase";
import { PayTeacherUseCase } from './../../feature/teacherPayment/usecases/payTeacher.usecase';
import { VerifyAndFetchUsersUseCase } from "./../../feature/users/useCases/verifyUsersExistence.usecase";
import { container } from './container';
import { GetGroupTypesOfChaptersUseCase } from "../../feature/lms/useCases/GetGroupTypesOfChapters.usecase"
import { ListChapterAttachmentsUseCase } from "../../feature/lms/useCases/ListChapterAttachments.usecase"
import { DeleteChapterUseCase } from "../../feature/lms/useCases/DeleteChapter.usecase"
import { UpdateChapterUseCase } from "../../feature/lms/useCases/UpdateChapter.usecase"
import { AddChapterUseCase } from "../../feature/lms/useCases/AddChapter.usecase"
import { GetTopicsOfChaptersByClassTypeUseCase } from "../../feature/lms/useCases/GetTopicsOfChaptersByClassType.usecase"
import { GetChaptersByTopicUseCase } from "../../feature/lms/useCases/GetChaptersByTopic.usecase"
import { GetStudentChaptersUseCase } from "../../feature/lms/useCases/GetStudentChapters.usecase"
import { DeleteChapterAttachmentUseCase } from "../../feature/lms/useCases/DeleteChapterAttachment.usecase"
import { UpdateChapterAttachmentUseCase } from "../../feature/lms/useCases/UpdateChapterAttachment.usecase"
import { AddChapterAttachmentUseCase } from "../../feature/lms/useCases/AddChapterAttachment.usecase"
import { UnAssignTeacherFromSubSubjectUseCase } from '../../feature/classes/useCases/UnAssignTeacherFromSubSubject.usecase';
import { UnAssignTeacherFromSubjectUseCase } from '../../feature/classes/useCases/UnAssignTeacherFromSubject.usecase';
import { UnassignStudentFromClassUseCase } from '../../feature/classes/useCases/UnassignStudentFromClass.usecase';
import { GetSubjectsOfClassUseCase } from '../../feature/classes/useCases/GetSubjectsOfClass.usecase';
import { UpdateStudentGroupUseCase } from '../../feature/classes/useCases/UpdateStudentGroup.usecase';
import { AddSignatureUseCase } from "../../feature/signatures/useCases/AddSignature.usecase";
import { ListSignaturesUseCase } from "../../feature/signatures/useCases/ListSignatures.usecase";
import { UpdateSignatureUseCase } from "../../feature/signatures/useCases/UpdateSignature.usecase";
import { GetAllCambridgeAnnualGradeReportsOfClassUseCase } from "../../feature/examGrade/useCases/cambridge/GetAllCambridgeAnnualGradeReportsOfClass.usecase";
import { GetStudentCambridgeAnnualGradeReportUseCase } from "../../feature/examGrade/useCases/cambridge/GetStudentCambridgeAnnualGradeReport.usecase";
import { GetIBAnnualAveragesOfClassUseCase } from "../../feature/examGrade/useCases/ib/GetIBAnnualAveragesOfClass.usecase";
import { GetCambridgeAnnualAveragesOfClassUseCase } from "../../feature/examGrade/useCases/cambridge/GetCambridgeAnnualAveragesOfClass.usecase";
import { AddIssueUseCase } from '../../feature/issues/usecases/addIssue.usecase';
import { ForwardIssueUseCaseUseCase } from '../../feature/issues/usecases/ForwardIssueUseCase.usecase';

export const registerUseCases = (): void => {  
  container.bind("GetGroupTypesOfChaptersUseCase").to(GetGroupTypesOfChaptersUseCase);  
  container.bind("ListChapterAttachmentsUseCase").to(ListChapterAttachmentsUseCase);  
  container.bind("DeleteChapterUseCase").to(DeleteChapterUseCase);  
  container.bind("UpdateChapterUseCase").to(UpdateChapterUseCase);  
  container.bind("AddChapterUseCase").to(AddChapterUseCase);  
  container.bind("GetTopicsOfChaptersByClassTypeUseCase").to(GetTopicsOfChaptersByClassTypeUseCase);  
  container.bind("GetChaptersByTopicUseCase").to(GetChaptersByTopicUseCase);  
  container.bind("GetStudentChaptersUseCase").to(GetStudentChaptersUseCase);  
  container.bind("ForwardIssueUseCaseUseCase").to(ForwardIssueUseCaseUseCase);  
  container.bind("AddIssueUseCase").to(AddIssueUseCase);
  container.bind("DeleteChapterAttachmentUseCase").to(DeleteChapterAttachmentUseCase);  
  container.bind("UpdateChapterAttachmentUseCase").to(UpdateChapterAttachmentUseCase);  
  container.bind("AddChapterAttachmentUseCase").to(AddChapterAttachmentUseCase);  
  container.bind("ListObservationReasonsUseCase").to(ListObservationReasonsUseCase);  
  container.bind("UpdateObservationReasonUseCase").to(UpdateObservationReasonUseCase);  
  container.bind("DeleteObservationReasonUseCase").to(DeleteObservationReasonUseCase);  
  container.bind("AddObservationReasonUsecase").to(AddObservationReasonUsecase);  
  container.bind("GetOneObservationUseCase").to(GetOneObservationUseCase);  
  container.bind("ListObservationsUseCase").to(ListObservationsUseCase);  
  container.bind("AddObservationForClassUseCase").to(AddObservationForClassUseCase);  
  container.bind("AddObservationForGroupUseCase").to(AddObservationForGroupUseCase);  
  container.bind("UpdateObservationUseCase").to(UpdateObservationUseCase);  
  container.bind("DeleteObservationUseCase").to(DeleteObservationUseCase);  
  container.bind("ListDocumentsOfStudentsUseCase").to(ListDocumentsOfStudentsUseCase);  
  container.bind("GetStudentDocumentsQueryUseCase").to(GetStudentDocumentsQueryUseCase);  
  container.bind("GetTeachersOfStudentUseCase").to(GetTeachersOfStudentUseCase);  
  container.bind("GetSubjectTypesOfClassUseCase").to(GetSubjectTypesOfClassUseCase);  
  container.bind("GetGroupsOfStudentUseCase").to(GetGroupsOfStudentUseCase);
  container.bind("GetPaymentTemplateUseCase").to(GetPaymentTemplateUseCase);  
  container.bind("UnAssignTeacherFromSubSubjectUseCase").to(UnAssignTeacherFromSubSubjectUseCase);  
  container.bind("UnAssignTeacherFromSubjectUseCase").to(UnAssignTeacherFromSubjectUseCase);  
  container.bind("UnassignStudentFromClassUseCase").to(UnassignStudentFromClassUseCase);  
  container.bind("GetSubjectsOfClassUseCase").to(GetSubjectsOfClassUseCase);  
  container.bind("UpdateStudentGroupUseCase").to(UpdateStudentGroupUseCase);  
  container.bind("DeletePaymentTemplateUseCase").to(DeletePaymentTemplateUseCase);  
  container.bind("AddPaymentTemplateUseCase").to(AddPaymentTemplateUseCase);  
  container.bind("GetTeacherPaymentDashboardUseCase").to(GetTeacherPaymentDashboardUseCase);  
  container.bind("UpdatePaymentTemplateUseCase").to(UpdatePaymentTemplateUseCase);  
  container.bind("UnPayTeacherUseCase").to(UnPayTeacherUseCase);  
  container.bind("PayTeacherUseCase").to(PayTeacherUseCase);  
  container.bind("GetTeacherPaymentConfigurationUseCase").to(GetTeacherPaymentConfigurationUseCase);  
  container.bind("DeleteTeacherPaymentTransactionUseCase").to(DeleteTeacherPaymentTransactionUseCase);  
  container.bind("addTeacherPaymentTransactionUseCase").to(AddTeacherPaymentTransactionUseCase);  
  container.bind("updateTeacherPaymentConfigurationUseCase").to(UpdateTeacherPaymentConfigurationUseCase);  
  container.bind("AddTeacherPaymentConfigurationUseCase").to(AddTeacherPaymentConfigurationUseCase);  
  container.bind("UpdateGroupTypeUseCase").to(UpdateGroupTypeUseCase);  
  container.bind("GetTeacherClassAndGroupsUseCase").to(GetTeacherClassAndGroupsUseCase);  
  container.bind("GetStudentsCodeBarePdfUseCase").to(GetStudentsCodeBarePdfUseCase);  
  container.bind("GetClassListUseCase").to(GetClassListUseCase);  
  container.bind("GetClassDashboardUseCase").to(GetClassDashboardUseCase);  
  container.bind("AssignTeacherToSubSubjectInClassUseCase").to(AssignTeacherToSubSubjectInClassUseCase);  
  container.bind("AssignTeachersToSubjectsInClassUseCase").to(AssignTeachersToSubjectsInClassUseCase);  
  container.bind("AddClassUseCase").to(AddClassUseCase);  
  container.bind("AssignStudentToClassUseCase").to(AssignStudentToClassUseCase);  
  container.bind("ListGroupTypesUseCase").to(ListGroupTypesUseCase);  
  container.bind("DeleteGroupTypeUseCase").to(DeleteGroupTypeUseCase);  
  container.bind("AddGroupTypeUseCase").to(AddGroupTypeUseCase);  
  container.bind("MarkSmartScheduleAsErroredUseCase").to(MarkSmartScheduleAsErroredUseCase);  
  container.bind("ListClassroomsUseCase").to(ListClassroomsUseCase);  
  container.bind("UpdateTutorialUseCase").to(UpdateTutorialUseCase);  
  container.bind("DeleteTutorialUseCase").to(DeleteTutorialUseCase);  
  container.bind("AddTutorialUseCase").to(AddTutorialUseCase);  
  container.bind("ListTutorialUseCase").to(ListTutorialUseCase);  
  container.bind("GetSmartSchedulePDFUseCase").to(GetSmartSchedulePDFUseCase);  
  container.bind("CompleteScheduleGenerationUseCase").to(CompleteScheduleGenerationUseCase);  
  container.bind("UpdateGroupTeacherUseCase").to(UpdateGroupTeacherUseCase);  
  container.bind("DeleteGroupUseCase").to(DeleteGroupUseCase);  
  container.bind("UpdateGroupUseCase").to(UpdateGroupUseCase);  
  container.bind("GetGroupsOfTeacherUseCase").to(GetGroupsOfTeacherUseCase);  
  container.bind("UnassignStudentFromGroupUseCase").to(UnassignStudentFromGroupUseCase);  
  container.bind("ListUnenrolledStudentsForGroupUseCase").to(ListUnenrolledStudentsForGroupUseCase);  
  container.bind("GetGroupListUseCase").to(GetGroupListUseCase);  
  container.bind("AddGroupUseCase").to(AddGroupUseCase);  
  container.bind("CheckGroupUseCase").to(CheckGroupUseCase);  
  container.bind("AssignStudentToGroupUseCase").to(AssignStudentToGroupUseCase);  
  container.bind("UpdateWeeklySessionForGroupUseCase").to(UpdateWeeklySessionForGroupUseCase);  
  container.bind("AddWeeklySessionForGroupUseCase").to(AddWeeklySessionForGroupUseCase);  
  container.bind("UpdateSessionForGroupUseCase").to(UpdateSessionForGroupUseCase);  
  container.bind("AddSessionForGroupUseCase").to(AddSessionForGroupUseCase);  
  container.bind("ApplyWeeklyScheduleForGroupUseCase").to(ApplyWeeklyScheduleForGroupUseCase);
  container.bind("GetLevelsOverviewUseCase").to(GetLevelsOverviewUseCase);  
  container.bind("ListSmartCalendarSchedulesUseCase").to(ListSmartCalendarSchedulesUseCase);  
  container.bind("CancelSmartCalendarScheduleUseCase").to(CancelSmartCalendarScheduleUseCase);  
  container.bind("ApplySmartCalendarScheduleUseCase").to(ApplySmartCalendarScheduleUseCase);  
  container.bind("DeleteSmartCalendarScheduleUseCase").to(DeleteSmartCalendarScheduleUseCase);  
  container.bind("UpdateSmartCalendarScheduleUseCase").to(UpdateSmartCalendarScheduleUseCase);  
  container.bind("GenerateScheduleUseCase").to(GenerateScheduleUseCase);  
  container.bind("DeleteClassTypeActivityUseCase").to(DeleteClassTypeActivityUseCase);  
  container.bind("AddClassTypeActivityUseCase").to(AddClassTypeActivityUseCase);  
  container.bind("GetActivitiesOfClassTypeUseCase").to(GetActivitiesOfClassTypeUseCase);  
  container.bind("ResetUserPasswordUseCase").to(ResetUserPasswordUseCase);  
  container.bind("GetOnePreRegistrationUseCase").to(GetOnePreRegistrationUseCase);  
  container.bind("ListPreRegistrationsUseCase").to(ListPreRegistrationsUseCase);  
  container.bind("RegisterStudentUseCase").to(RegisterStudentUseCase);  
  container.bind("DeletePreRegistrationUseCase").to(DeletePreRegistrationUseCase);  
  container.bind("DeleteExpenseUseCase").to(DeleteExpenseUseCase);  
  container.bind("UpdateExpenseUseCase").to(UpdateExpenseUseCase);  
  container.bind("AddExpenseUseCase").to(AddExpenseUseCase);  
  container.bind("ListTeachersUseCase").to(ListTeachersUseCase);  
  container.bind("GetStudentAttendanceCertificateUseCase").to(GetStudentAttendanceCertificateUseCase);  
  container.bind("GetChildrenOfParentUseCase").to(GetChildrenOfParentUseCase);  
  container.bind("GetAdminByNewIdUseCase").to(GetAdminByNewIdUseCase);  
  container.bind("ListAdminsUseCase").to(ListAdminsUseCase);  
  container.bind("GetParentByNewIdUseCase").to(GetParentByNewIdUseCase);  
  container.bind("ListParentsUseCase").to(ListParentsUseCase);
  container.bind("GetClassDiplomasUseCase").to(GetClassDiplomasUseCase);
  container.bind("GetStudentDiplomaUseCase").to(GetStudentDiplomaUseCase);
  container.bind("GetCambridgeStudentGradeReportUseCase").to(GetCambridgeStudentGradeReportUseCase);
  container.bind("GetPrimaryStudentGradeReportUseCase").to(GetPrimaryStudentGradeReportUseCase);
  container.bind("GetSecondaryStudentGradeReportUseCase").to(GetSecondaryStudentGradeReportUseCase);
  container.bind("ToggleUserActivationUseCase").to(ToggleUserActivationUseCase);
  container.bind("LoginByMasterUseCase").to(LoginByMasterUseCase);
  container.bind("LoginUseCase").to(LoginUseCase);
  container.bind("LogoutUseCase").to(LogoutUseCase);
  container.bind("ResetPasswordUseCase").to(ResetPasswordUseCase);
  container.bind("VerifyCodeUseCase").to(VerifyCodeUseCase);
  container.bind("ForgetPasswordUseCase").to(ForgetPasswordUseCase);
  container.bind("UpdateCurrentUserPasswordUseCase").to(UpdateCurrentUserPasswordUseCase);
  container.bind("UpdatePreRegistrationUseCase").to(UpdatePreRegistrationUseCase);
  container.bind("UploadAvatarUseCase").to(UploadAvatarUseCase);
  container.bind("ListUsersUseCase").to(ListUsersUseCase);
  container.bind("DeleteAlertUseCase").to(DeleteAlertUseCase);
  container.bind("AddAlertUseCase").to(AddAlertUseCase);
  container.bind("ListAlertUseCase").to(ListAlertUseCase);
  container.bind("GetNonDraftWeeklyScheduleUseCase").to(GetNonDraftWeeklyScheduleUseCase);
  container.bind("AddTeacherUseCase").to(AddTeacherUseCase);
  container.bind("ListSessionTypeUseCase").to(ListSessionTypeUseCase);
  container.bind("UpdateWeeklySessionForClassUseCase").to(UpdateWeeklySessionForClassUseCase);
  container.bind("AddWeeklySessionForClassUseCase").to(AddWeeklySessionForClassUseCase);
  container.bind("UpdateSessionForClassUseCase").to(UpdateSessionForClassUseCase);
  container.bind("AddSessionForClassUseCase").to(AddSessionForClassUseCase);
  container.bind("ApplyWeeklyScheduleForClassUseCase").to(ApplyWeeklyScheduleForClassUseCase);
  container.bind("GetEntityScheduleUseCase").to(GetEntityScheduleUseCase);
  container.bind("GetAvailableClassroomInWeeklySessionUseCase").to(GetAvailableClassroomInWeeklySessionUseCase);
  container.bind("GetAvailableClassroomUseCase").to(GetAvailableClassroomUseCase);
  container.bind("DeleteWeeklySessionUseCase").to(DeleteWeeklySessionUseCase);
  container.bind("DeleteSessionUseCase").to(DeleteSessionUseCase);
  container.bind("GetDraftWeeklyScheduleUseCase").to(GetDraftWeeklyScheduleUseCase);
  container.bind("GetScheduleUseCase").to(GetScheduleUseCase);
  container.bind("ImportStudentsUseCase").to(ImportStudentsUseCase);
  container.bind("AddParentUseCase").to(AddParentUseCase);
  container.bind("AddAdminUseCase").to(AddAdminUseCase);
  container.bind("AddStudentUseCase").to(AddStudentUseCase);
  container.bind("GetClassTypeUseCase").to(GetClassTypeUseCase);
  container.bind("UpdateSchoolYearUseCase").to(UpdateSchoolYearUseCase);
  container.bind("AddSchoolYearUseCase").to(AddSchoolYearUseCase);
  container.bind("ReorderExamTypeUseCase").to(ReorderExamTypeUseCase);
  container.bind("UpdateExamTypeUseCase").to(UpdateExamTypeUseCase);
  container.bind("ReorderSubLevelsUseCase").to(ReorderSubLevelsUseCase);
  container.bind("DeleteExamTypeUseCase").to(DeleteExamTypeUseCase);
  container.bind("ListSectionsUseCase").to(ListSectionsUseCase);
  container.bind("AddExamTypeUseCase").to(AddExamTypeUseCase);
  container.bind("DeleteClassroomUseCase").to(DeleteClassroomUseCase);
  container.bind("UpdateClassroomUseCase").to(UpdateClassroomUseCase);
  container.bind("GetStudentsOfGroupUseCase").to(GetStudentsOfGroupUseCase);
  container.bind("GetGroupsOfClassUseCase").to(GetGroupsOfClassUseCase);
  container.bind("GetStudentsOfClassUseCase").to(GetStudentsOfClassUseCase);
  container.bind("ReorderLevelsUseCase").to(ReorderLevelsUseCase);
  container.bind("AddClassroomUseCase").to(AddClassroomUseCase);
  container.bind("DeleteSessionTypeUseCase").to(DeleteSessionTypeUseCase);
  container.bind("UpdateSessionTypeUseCase").to(UpdateSessionTypeUseCase);
  container.bind("AddSessionTypeUseCase").to(AddSessionTypeUseCase);
  container.bind("ListTermUseCase").to(ListTermUseCase);
  container.bind("DeleteTermUseCase").to(DeleteTermUseCase);
  container.bind("UpdateTermUseCase").to(UpdateTermUseCase);
  container.bind("DeleteSubSubjectTypeUseCase").to(DeleteSubSubjectTypeUseCase);
  container.bind("AddTermUseCase").to(AddTermUseCase);
  container.bind("EnrichPostsUseCase").to(EnrichPostsUseCase);
  container.bind("GetAllPostsUseCase").to(ListAllPostsFeedUseCase);
  container.bind("GetUserFeedUseCase").to(ListUserFeedUseCase);
  container.bind("EnrichOnePostUseCase").to(EnrichOnePostUseCase);
  container.bind("EnrichOneCommentUseCase").to(EnrichOneCommentUseCase);
  container.bind("ListCommentsOfPostUseCase").to(ListCommentsOfPostUseCase);
  container.bind("ListRepliesOfCommentUseCase").to(ListRepliesOfCommentUseCase);
  container.bind("ListIssuesOfAdminUseCase").to(ListIssuesOfAdminUseCase);
  container.bind("ListIssuesOfTeacherUseCase").to(ListIssuesOfTeacherUseCase);
  container.bind("ListIssuesOfParentUseCase").to(ListIssuesOfParentUseCase);
  container.bind("ListInteractionsOfIssueUseCase").to(ListInteractionsOfIssueUseCase);
  container.bind("UpdateClassUseCase").to(UpdateClassUseCase);
  container.bind("DeleteClassUseCase").to(DeleteClassUseCase);
  container.bind("AddMessageUseCase").to(AddMessageUseCase);
  container.bind("ListConversationsUseCase").to(ListConversationsUseCase);
  container.bind("ListConversationMessagesUseCase").to(ListConversationMessagesUseCase);
  container.bind("ListConversationLinksUseCase").to(ListConversationLinksUseCase);
  container.bind("ListConversationAttachmentsUseCase").to(ListConversationAttachmentsUseCase);
  container.bind("ListConversationMultimediaUseCase").to(ListConversationMultimediaUseCase);
  container.bind("AddDirectConversationUseCase").to(AddDirectConversationUseCase);
  container.bind("ListHomeworkUseCase").to(ListHomeworkUseCase);
  container.bind("GetSessionDetailsUseCase").to(GetSessionDetailsUseCase);
  container.bind("ReactToMessageUseCase").to(ReactToMessageUseCase);
  container.bind("VerifyAndFetchUsersUseCase").to(VerifyAndFetchUsersUseCase);
  container.bind("FindUsersByFullNameUseCase").to(FindUsersByFullNameUseCase);
  container.bind("GetConversationUseCase").to(GetConversationUseCase);
  container.bind("ListClassTypeUseCase").to(ListClassTypeUseCase);
  container.bind("AddFieldToClasstypeUseCase").to(AddFieldToClasstypeUseCase);
  container.bind("AddSubSubjectToClassTypeUseCase").to(AddSubSubjectToClassTypeUseCase);
  container.bind("AddSubjectToClassTypeUseCase").to(AddSubjectToClassTypeUseCase);
  container.bind("GetFieldsOfClassTypeUseCase").to(GetFieldsOfClassTypeUseCase);
  container.bind("GetSubjectsOfClassTypesUseCase").to(GetSubjectsOfClassTypesUseCase);
  container.bind("ListNextClassTypesUseCase").to(ListNextClassTypesUseCase);
  container.bind("ReorderFieldsOfClassTypesUseCase").to(ReorderFieldsOfClassTypesUseCase);
  container.bind("ReorderSubSubjectInClassTypeUseCase").to(ReorderSubSubjectInClassTypeUseCase);
  container.bind("ReorderSubjectInClassTypeUseCase").to(ReorderSubjectInClassTypeUseCase);
  container.bind("UpdateClassTypeUseCase").to(UpdateClassTypeUseCase);
  container.bind("DeleteMessageUseCase").to(DeleteMessageUseCase);
  container.bind("DeleteFieldFromClassTypeUseCase").to(DeleteFieldFromClassTypeUseCase);
  container.bind("ListExamTypeUseCase").to(ListExamTypeUseCase);
  container.bind("DeleteSubSubjectFromClassTypeUseCase").to(DeleteSubSubjectFromClassTypeUseCase);
  container.bind("DeleteSubjectFromClassTypeUseCase").to(DeleteSubjectFromClassTypeUseCase);
  container.bind("GetOneIssueUseCase").to(GetOneIssueUseCase);
  container.bind("AddGroupConversationUseCase").to(AddGroupConversationUseCase);
  container.bind("AddParticipantsToConversationUseCase").to(AddParticipantsToConversationUseCase);
  container.bind("ListMastersUseCase").to(ListMastersUseCase);
  container.bind("ListTargetUsersForGroupConversationAssignmentUseCase").to(ListTargetUsersForGroupConversationAssignmentUseCase);
  container.bind("ListRolesUseCase").to(ListRolesUseCase);
  container.bind("UpdateSubSubjectOfClassTypeUseCase").to(UpdateSubSubjectOfClassTypeUseCase);
  container.bind("ListSubSubjectTypeUseCase").to(ListSubSubjectTypeUseCase);
  container.bind("UpdateFieldOfClassTypeUseCase").to(UpdateFieldOfClassTypeUseCase);
  container.bind("UpdateLevelUseCase").to(UpdateLevelUseCase);
  container.bind("AddRoleUseCase").to(AddRoleUseCase);
  container.bind("UpdateRoleUseCase").to(UpdateRoleUseCase);
  container.bind("UpdateSectionUseCase").to(UpdateSectionUseCase);
  container.bind("DeleteSectionUseCase").to(DeleteSectionUseCase);
  container.bind("AddSubLevelUseCase").to(AddSubLevelUseCase);
  container.bind("UpdateSubLevelUseCase").to(UpdateSubLevelUseCase);
  container.bind("DeleteSubLevelUseCase").to(DeleteSubLevelUseCase);
  container.bind("GetOneRoleUseCase").to(GetOneRoleUseCase);
  container.bind("DeleteRoleUseCase").to(DeleteRoleUseCase);
  container.bind("ConfirmAttendanceUseCase").to(ConfirmAttendanceUseCase);
  container.bind("AddSubjectTypeUseCase").to(AddSubjectTypeUseCase);
  container.bind("UpdateSubjectTypeUseCase").to(UpdateSubjectTypeUseCase);
  container.bind("AddMasterUseCase").to(AddMasterUseCase);
  container.bind("DeleteSubjectTypeUseCase").to(DeleteSubjectTypeUseCase);
  container.bind("AddSubSubjectTypeUseCase").to(AddSubSubjectTypeUseCase);
  container.bind("DeleteClassTypeUseCase").to(DeleteClassTypeUseCase);
  container.bind("UpdateSubSubjectTypeUsecase").to(UpdateSubSubjectTypeUsecase);
  container.bind("ListSchoolYearUseCase").to(ListSchoolYearUseCase);
  container.bind("AddHolidayUseCase").to(AddHolidayUseCase);
  container.bind("UpdateHolidayUseCase").to(UpdateHolidayUseCase);
  container.bind("UpdateMasterUseCase").to(UpdateMasterUseCase);
  container.bind("DeleteMasterUseCase").to(DeleteMasterUseCase);
  container.bind("ListSchoolsUseCase").to(ListSchoolsUseCase);
  container.bind("CloseSessionUseCase").to(CloseSessionUseCase);
  container.bind("ListClassesUseCase").to(ListClassesUseCase);
  container.bind("ListClassesByTeacherUseCase").to(ListClassesByTeacherUseCase);
  container.bind("SwitchToSchoolUsecase").to(SwitchToSchoolUsecase);
  container.bind("DeleteHolidayUseCase").to(DeleteHolidayUseCase);
  container.bind("ListHolidayUseCase").to(ListHolidayUseCase);
  container.bind("AddSchoolUseCase").to(AddSchoolUseCase);
  container.bind("UpdateSchoolUseCase").to(UpdateSchoolUseCase);
  container.bind("CancelSessionUseCase").to(CancelSessionUseCase);
  container.bind("StartSessionUseCase").to(StartSessionUseCase);
  container.bind("UpdateSessionDetailsUseCase").to(UpdateSessionDetailsUseCase);
  container.bind("ListInvoicesUseCase").to(ListInvoicesUseCase);
  container.bind("GetAllAppsVersionUseCase").to(GetAppVersionUseCase);
  container.bind("ArchiveAdminUseCase").to(ArchiveAdminUseCase);
  container.bind("ArchiveParentUseCase").to(ArchiveParentUseCase);
  container.bind("ArchiveStudentUseCase").to(ArchiveStudentUseCase);
  container.bind("ArchiveTeacherUseCase").to(ArchiveTeacherUseCase);
  container.bind("GetGradesOfCambridgeGroupUsecase").to(GetGradesOfCambridgeGroupUsecase);
  container.bind("GetPrimaryAveragesOfClassUsecase").to(GetPrimaryAveragesOfClassUsecase);
  container.bind("AddClassTypeUseCase").to(AddClassTypeUseCase);
  container.bind("UpdateAlertUseCase").to(UpdateAlertUseCase);
  container.bind("GetAlertDetailsUseCase").to(GetAlertDetailsUseCase);
  container.bind("UpdateTeacherConstraintsUseCase").to(UpdateTeacherConstraintsUseCase);
  container.bind("UpdateClassTypeActivityUseCase").to(UpdateClassTypeActivityUseCase);
  container.bind("UpdateIBGradesOfGroupUseCase").to(UpdateIBGradesOfGroupUseCase);
  container.bind("GetIBAdminObservationsUseCase").to(GetIBAdminObservationsUseCase);
  container.bind("UpdateAdminObservationsUseCase").to(UpdateAdminObservationsUseCase);
  container.bind("GetOneHomeworkUseCase").to(GetOneHomeworkUseCase);
  container.bind("RemoveParticipantsFromConversationUseCase").to(RemoveParticipantsFromConversationUseCase);
  container.bind("UpdateConversationNameUseCase").to(UpdateConversationNameUseCase);
  container.bind("UpdateConversationSeenStatusUseCase").to(UpdateConversationSeenStatusUseCase);
  container.bind("ListConversationParticipantsUseCase").to(ListConversationParticipantsUseCase);
  container.bind("GetMessageReactionsUseCase").to(GetMessageReactionsUseCase);
  container.bind("UpdateSubjectFromClassTypeUseCase").to(UpdateSubjectFromClassTypeUseCase);
  container.bind("AddSectionUseCase").to(AddSectionUseCase);
  container.bind("AddLevelUseCase").to(AddLevelUseCase);
  container.bind("DeleteLevelUseCase").to(DeleteLevelUseCase);
  container.bind("ListTeacherGroupUseCase").to(ListTeacherGroupUseCase);
  container.bind("UpdateFlagsUseCase").to(UpdateFlagsUseCase);
  container.bind("UpdateSessionStatusUseCase").to(UpdateSessionStatusUseCase);
  container.bind("AddBarCodeConfigUseCase").to(AddBarCodeConfigUseCase);
  container.bind("ListBarCodeConfigUseCase").to(ListBarCodeConfigUseCase);
  container.bind("UpdateBarCodeConfigUseCase").to(UpdateBarCodeConfigUseCase);
  container.bind("DeleteBarCodeConfigUseCase").to(DeleteBarCodeConfigUseCase);
  container.bind("AddSignatureUseCase").to(AddSignatureUseCase);
  container.bind("ListSignaturesUseCase").to(ListSignaturesUseCase);
  container.bind("UpdateSignatureUseCase").to(UpdateSignatureUseCase);
  container.bind("DeleteSignatureUseCase").to(DeleteSignatureUseCase);
  container.bind("GetSchoolDetailsUseCase").to(GetSchoolDetailsUseCase);
  container.bind("UpdateAppVersionUseCase").to(UpdateAppVersionUseCase);
  container.bind("SwitchStudentsClassUseCase").to(SwitchStudentsClassUseCase);
  container.bind("UnArchiveAdminUseCase").to(UnArchiveAdminUseCase);
  container.bind("UnArchiveParentUseCase").to(UnArchiveParentUseCase);
  container.bind("UnArchiveStudentUseCase").to(UnArchiveStudentUseCase);
  container.bind("UnArchiveTeacherUseCase").to(UnArchiveTeacherUseCase);
  container.bind("GetFieldsOfClassUseCase").to(GetFieldsOfClassUseCase);
  container.bind("PayInvoiceUseCase").to(PayInvoiceUseCase);
  container.bind("GetGradesOfFieldUseCase").to(GetGradesOfFieldUseCase);
  container.bind("GetSecondarySubjectsOfClassUseCase").to(GetSecondarySubjectsOfClassUseCase);
  container.bind("GetGradesOfSecondarySubjectUseCase").to(GetGradesOfSecondarySubjectUseCase);
  container.bind("GetCambridgeSubjectsOfClassUseCase").to(GetCambridgeSubjectsOfClassUseCase);
  container.bind("GetGradesOfCambridgeSubjectUseCase").to(GetGradesOfCambridgeSubjectUseCase);
  container.bind("GetGradesOfSecondaryGroupUseCase").to(GetGradesOfSecondaryGroupUseCase);
  container.bind("GetSecondaryAveragesOfClassUsecase").to(GetSecondaryAveragesOfClassUsecase);
  container.bind("GetCambridgeAveragesOfClassUsecase").to(GetCambridgeAveragesOfClassUsecase);
  container.bind("GetPrimaryBlankExamPageUsecase").to(GetPrimaryBlankExamPageUsecase);
  container.bind("GetCambridgeBlankExamPageUsecase").to(GetCambridgeBlankExamPageUsecase);
  container.bind("GetSecondaryBlankExamPageUsecase").to(GetSecondaryBlankExamPageUsecase);
  container.bind("GetAllPrimaryGradeReportsOfClassUseCase").to(GetAllPrimaryGradeReportsOfClassUseCase);
  container.bind("GetAllSecondaryGradeReportsOfClassUseCase").to(GetAllSecondaryGradeReportsOfClassUseCase);
  container.bind("GetAllCambridgeGradeReportsOfClassUseCase").to(GetAllCambridgeGradeReportsOfClassUseCase);
  container.bind("GetPrimaryGradeReportStatsUseCase").to(GetPrimaryGradeReportStatsUseCase);
  container.bind("GetSecondaryGradeReportStatsUseCase").to(GetSecondaryGradeReportStatsUseCase);
  container.bind("CompleteTermUseCase").to(CompleteTermUseCase);
  container.bind("IncompleteTermUseCase").to(IncompleteTermUseCase);
  container.bind("UpdatePrimaryGradesUseCase").to(UpdatePrimaryGradesUseCase);
  container.bind("UpdateSecondaryGradesUseCase").to(UpdateSecondaryGradesUseCase);
  container.bind("UpdateCambridgeGradesUseCase").to(UpdateCambridgeGradesUseCase);
  container.bind("UpdateSecondaryGradesOfGroupUseCase").to(UpdateSecondaryGradesOfGroupUseCase);
  container.bind("UpdateCambridgeGradesOfGroupUseCase").to(UpdateCambridgeGradesOfGroupUseCase);
  container.bind("GetPrimaryChildGradeReportUseCase").to(GetPrimaryChildGradeReportUseCase);
  container.bind("GetSecondaryChildGradeReportUseCase").to(GetSecondaryChildGradeReportUseCase);
  container.bind("GetCambridgeChildGradeReportUseCase").to(GetCambridgeChildGradeReportUseCase);
  container.bind("GetClassOverviewUseCase").to(GetClassOverviewUseCase);
  container.bind("GetGroupOverviewUseCase").to(GetGroupOverviewUseCase);
  container.bind("UpdateSmsSoldUseCase").to(UpdateSmsSoldUseCase);
  container.bind("UpdateBankTransferUseCase").to(UpdateBankTransferUseCase);
  container.bind("ListUsersForAlertUseCase").to(ListUsersForAlertUseCase);
  container.bind("PublishTermUseCase").to(PublishTermUseCase);
  container.bind("HideTermUseCase").to(HideTermUseCase);
  container.bind("GetAnnualAveragesOfClassUseCase").to(GetAnnualAveragesOfClassUseCase);
  container.bind("GetPrimaryAnnualGradeReportOfStudentUsecase").to(GetPrimaryAnnualGradeReportOfStudentUsecase);
  container.bind("GetAllPrimaryAnnualGradeReportOfClassUsecase").to(GetAllPrimaryAnnualGradeReportOfClassUsecase);
  container.bind("UpdateStudentPromotionStatusUsecase").to(UpdateStudentPromotionStatusUsecase);
  container.bind("GetDashboardUseCase").to(GetDashboardUseCase);
  container.bind("ListSmsSoldHistoriesUseCase").to(ListSmsSoldHistoriesUseCase);
  container.bind("GetLevelDegreesCoverageUsecase").to(GetLevelDegreesCoverageUsecase);
  container.bind("GetNotPromotedStudentsUsecase").to(GetNotPromotedStudentsUsecase);
  container.bind("SwitchLevelToNextSchoolYearUseCase").to(SwitchLevelToNextSchoolYearUseCase);
  container.bind("AddGradeReportTemplateUseCase").to(AddGradeReportTemplateUseCase);
  container.bind("ListGradeReportTemplateUseCase").to(ListGradeReportTemplateUseCase);
  container.bind("UpdateGradeReportTemplateUseCase").to(UpdateGradeReportTemplateUseCase);
  container.bind("DeleteGradeReportTemplateUseCase").to(DeleteGradeReportTemplateUseCase);
  container.bind("GetStudentProfileUseCase").to(GetStudentProfileUseCase);
  container.bind("GetTeacherProfileUsecase").to(GetTeacherProfileUsecase);
  container.bind("GetSchoolAvailableTimeConstraintsUseCase").to(GetSchoolAvailableTimeConstraintsUseCase);
  container.bind("UpdateAdminUseCase").to(UpdateAdminUseCase);
  container.bind("UpdateStudentUseCase").to(UpdateStudentUseCase);
  container.bind("UpdateParentUseCase").to(UpdateParentUseCase);
  container.bind("UpdateTeacherUseCase").to(UpdateTeacherUseCase);
  container.bind("UpdateNotAvailableTimesUseCase").to(UpdateNotAvailableTimesUseCase);
  container.bind("UpdateBankCheckUseCase").to(UpdateBankCheckUseCase);
  container.bind("UpdateClassConstraintsUseCase").to(UpdateClassConstraintsUseCase);
  container.bind("SwitchToUserUseCase").to(SwitchToUserUseCase);
  container.bind("ResendInvitationUseCase").to(ResendInvitationUseCase);
  container.bind("GetIBSubjectsOfClassUseCase").to(GetIBSubjectsOfClassUseCase);
  container.bind("GetGradesOfIBSubjectUseCase").to(GetGradesOfIBSubjectUseCase);
  container.bind("GetGradesOfIBGroupUseCase").to(GetGradesOfIBGroupUsecase);
  container.bind("GetIBBlankExamPageUsecase").to(GetIBBlankExamPageUsecase);
  container.bind("GetIBAveragesOfClassUsecase").to(GetIBAveragesOfClassUsecase);
  container.bind("GetIBStudentGradeReportUseCase").to(GetIBStudentGradeReportUseCase);
  container.bind("GetAllIBGradeReportsOfClassUseCase").to(GetAllIBGradeReportsOfClassUseCase);
  container.bind("GetIBChildGradeReportUseCase").to(GetIBChildGradeReportUseCase);
  container.bind("UpdateIBGradesOfClassUseCase").to(UpdateIBGradesOfClassUseCase);
  container.bind("UpdateIssueStatusUseCase").to(UpdateIssueStatusUseCase);
  container.bind("AssignTeacherToIssueUseCase").to(AssignTeacherToIssueUseCase);
  container.bind("UnAssignTeacherFromIssueUseCase").to(UnAssignTeacherFromIssueUseCase);
  container.bind("SendReplyUseCase").to(SendReplyUseCase);
  container.bind("GetTeacherOfStudentUseCase").to(GetTeacherOfStudentUseCase);
  container.bind("GetAllCambridgeAnnualGradeReportsOfClassUseCase").to(GetAllCambridgeAnnualGradeReportsOfClassUseCase);
  container.bind("GetStudentCambridgeAnnualGradeReportUseCase").to(GetStudentCambridgeAnnualGradeReportUseCase);
  container.bind("GetIBAnnualAveragesOfClassUseCase").to(GetIBAnnualAveragesOfClassUseCase);
  container.bind("GetCambridgeAnnualAveragesOfClassUseCase").to(GetCambridgeAnnualAveragesOfClassUseCase);
}