
import { MongoAdminRepo } from "../../newDatabase/mongo/repositories/MongoAdmin.repo";
import { MongoClassRepo } from "../../newDatabase/mongo/repositories/MongoClass.repo";
import { MongoClassGroupRepo } from "../../newDatabase/mongo/repositories/MongoClassGroup.repo";
import { MongoClassTypeRepo } from "../../newDatabase/mongo/repositories/MongoClassType.repo";
import { MongoGroupRepo } from "../../newDatabase/mongo/repositories/MongoGroup.repo";
import { MongoGroupTypeRepo } from "../../newDatabase/mongo/repositories/MongoGroupType.repo";
import { MongoLevelRepo } from "../../newDatabase/mongo/repositories/MongoLevel.repo";
import { MongoMasterRepo } from "../../newDatabase/mongo/repositories/MongoMaster.repo";
import { MongoNotificationRepo } from "../../newDatabase/mongo/repositories/MongoNotification.repo";
import { MongoNotificationSettingsRepo } from "../../newDatabase/mongo/repositories/MongoNotificationSettings.repo";
import { MongoParentRepo } from "../../newDatabase/mongo/repositories/MongoParent.repo";
import { MongoRoleRepo } from "../../newDatabase/mongo/repositories/MongoRole.repo";
import { MongoSchoolYearRepo } from "../../newDatabase/mongo/repositories/MongoSchoolYear.repo";
import { MongoSessionRepo } from "../../newDatabase/mongo/repositories/MongoSession.repo";
import { MongoSessionTypeRepo } from "../../newDatabase/mongo/repositories/MongoSessionType.repo";
import { MongoStudentRepo } from "../../newDatabase/mongo/repositories/MongoStudent.repo";
import { MongoStudentProfileRepo } from "../../newDatabase/mongo/repositories/MongoStudentProfile.repo";
import { MongoSubjectTypeRepo } from "../../newDatabase/mongo/repositories/MongoSubjectType.repo";
import { MongoSubLevelRepo } from "../../newDatabase/mongo/repositories/MongoSubLevel.repo";
import { MongoSubSubjectTypeRepo } from "../../newDatabase/mongo/repositories/MongoSubSubjectType.repo";
import { MongoTeacherRepo } from "../../newDatabase/mongo/repositories/MongoTeacher.repo";
import { MongoTeacherProfileRepo } from "../../newDatabase/mongo/repositories/MongoTeacherProfile.repo";
import { MongoVerificationCodeRepo } from "../../newDatabase/mongo/repositories/MongoVerificationCode.repo";
import { MongoMessageLinksRepo } from "../../newDatabase/mongo/repositories/MongoMessageLink.repo";
import { MongoMessageRepo } from "../../newDatabase/mongo/repositories/MongoMessage.repo";
import { MongoWeeklySessionRepo } from "../../newDatabase/mongo/repositories/MongoWeeklySession.repo";
import { MongoClassroomRepo } from "./../../newDatabase/mongo/repositories/MongoClassroom.repo";
import { MongoConversationRepo } from "../../newDatabase/mongo/repositories/MongoConversation.repo";
import { MongoMessageAttachmentRepo } from "../../newDatabase/mongo/repositories/MessageAttachment.repo";
import { MongoUsersRepo } from "./../../newDatabase/mongo/repositories/MongoUsers.repo";
import { container } from "./container";
import { UserRepository } from "../../feature/user-management/base-user/domain/base-user.repository";
import { OrganizationRepository } from "../../feature/organization-magement/domain/organization.repo";

  
export const registerUseRepos = (): void => {  

  container.bind("GroupTypeRepo").to(MongoGroupTypeRepo);
  container.bind("VerificationCodeRepo").to(MongoVerificationCodeRepo);
  container.bind("SchoolYearRepo").to(MongoSchoolYearRepo);
  container.bind("RoleRepo").to(MongoRoleRepo);
  container.bind("MasterRepo").to(MongoMasterRepo);
  container.bind("MessageLinksRepo").to(MongoMessageLinksRepo);
  container.bind("ClassGroupRepo").to(MongoClassGroupRepo);
  container.bind("MessageRepo").to(MongoMessageRepo);
  container.bind("ConversationRepo").to(MongoConversationRepo);
  container.bind("MessageAttachmentRepo").to(MongoMessageAttachmentRepo);
  container.bind("SessionRepo").to(MongoSessionRepo);
  container.bind("WeeklySessionRepo").to(MongoWeeklySessionRepo);
  container.bind("NotificationRepo").to(MongoNotificationRepo);
  container.bind("ClassRepo").to(MongoClassRepo);
  container.bind("StudentRepo").to(MongoStudentRepo);
  container.bind("ParentRepo").to(MongoParentRepo);
  container.bind("AdminRepo").to(MongoAdminRepo);
  container.bind("TeacherRepo").to(MongoTeacherRepo);
  container.bind("NotificationSettingsRepo").to(MongoNotificationSettingsRepo);
  container.bind("SubLevelRepo").to(MongoSubLevelRepo);
  container.bind("LevelRepo").to(MongoLevelRepo);
  container.bind("StudentProfileRepo").to(MongoStudentProfileRepo);
  container.bind("ClassTypeRepo").to(MongoClassTypeRepo);
  container.bind("SubjectTypeRepo").to(MongoSubjectTypeRepo);
  container.bind("TeacherProfileRepo").to(MongoTeacherProfileRepo);
  container.bind("ClassroomRepo").to(MongoClassroomRepo);
  container.bind("SessionTypeRepo").to(MongoSessionTypeRepo);
  container.bind("SubSubjectTypeRepo").to(MongoSubSubjectTypeRepo);
  container.bind("GroupRepo").to(MongoGroupRepo);
  container.bind("UsersRepo").to(MongoUsersRepo);
  container.bind("UserRepository").to(UserRepository);
  container.bind("OrganizationRepository").to(OrganizationRepository);
}
