import { AutomaticPromotionGradesRepo } from "../../feature/examGrade/domain/automaticPromotion/AutomaticPromotionGrades.repo";
import { CambridgeClassGradesRepo } from "../../feature/examGrade/domain/cambridge/CambridgeClassGrades.repo";
import { IBClassGradesRepo } from "../../feature/examGrade/domain/ib/IBClassGrades.repo";
import { PrimaryClassGradesRepo } from "../../feature/examGrade/domain/tunisian/primary/PrimaryClassGrades.repo";
import { SecondaryClassGradesRepo } from "../../feature/examGrade/domain/tunisian/secondary/SecondaryClassGrades.repo";
import { MongoAdminRepo } from "../../newDatabase/mongo/repositories/MongoAdmin.repo";
import { MongoAlertRepo } from "../../newDatabase/mongo/repositories/MongoAlert.repo";
import { MongoAppVersionRepo } from "../../newDatabase/mongo/repositories/MongoAppVersion.repo";
import { MongoBankCheckRepo } from "../../newDatabase/mongo/repositories/MongoBankCheck.repo";
import { MongoBankTransferRepo } from "../../newDatabase/mongo/repositories/MongoBankTransfer.repo";
import { MongoBarCodeConfigRepo } from "../../newDatabase/mongo/repositories/MongoBarCodeConfig.repo";
import { MongoCentralUserRepo } from "../../newDatabase/mongo/repositories/MongoCentralUser.repo";
import { MongoClassRepo } from "../../newDatabase/mongo/repositories/MongoClass.repo";
import { MongoClassGroupRepo } from "../../newDatabase/mongo/repositories/MongoClassGroup.repo";
import { MongoClassTypeRepo } from "../../newDatabase/mongo/repositories/MongoClassType.repo";
import { MongoCommentRepo } from "../../newDatabase/mongo/repositories/MongoComment.repo";
import { MongoDiplomaRepo } from "../../newDatabase/mongo/repositories/MongoDiploma.repo";
import { MongoExamGradeRepo } from "../../newDatabase/mongo/repositories/MongoExamGrade.repo";
import { MongoExamTypeRepo } from "../../newDatabase/mongo/repositories/MongoExamType.repo";
import { MongoExpenseRepo } from "../../newDatabase/mongo/repositories/MongoExpense.repo";
import { MongoGradeBookObservationRepo } from "../../newDatabase/mongo/repositories/MongoGradeBookObservation.repo";
import { MongoGradeReportTemplateRepo } from "../../newDatabase/mongo/repositories/MongoGradeReportTemplate.repo";
import { MongoGroupRepo } from "../../newDatabase/mongo/repositories/MongoGroup.repo";
import { MongoGroupTypeRepo } from "../../newDatabase/mongo/repositories/MongoGroupType.repo";
import { MongoHolidayRepo } from "../../newDatabase/mongo/repositories/MongoHoliday.repo";
import { MongoHomeworkRepo } from "../../newDatabase/mongo/repositories/MongoHomework.repo";
import { MongoInteractionRepo } from "../../newDatabase/mongo/repositories/MongoInteraction.repo";
import { MongoInvoiceRepo } from "../../newDatabase/mongo/repositories/MongoInvoice.repo";
import { MongoIssueRepo } from "../../newDatabase/mongo/repositories/MongoIssue.repo";
import { MongoIssueReasonRepo } from "../../newDatabase/mongo/repositories/MongoIssueReason.repo";
import { MongoLevelRepo } from "../../newDatabase/mongo/repositories/MongoLevel.repo";
import { MongoMasterRepo } from "../../newDatabase/mongo/repositories/MongoMaster.repo";
import { MongoMessageRepo } from "../../newDatabase/mongo/repositories/MongoMessage.repo";
import { MongoMessageAttachmentRepo } from "../../newDatabase/mongo/repositories/MongoMessageAttachment.repo";
import { MongoNotificationRepo } from "../../newDatabase/mongo/repositories/MongoNotification.repo";
import { MongoNotificationSettingsRepo } from "../../newDatabase/mongo/repositories/MongoNotificationSettings.repo";
import { MongoObservationRepo } from "../../newDatabase/mongo/repositories/MongoObservation.repo";
import { MongoObservationReasonRepo } from "../../newDatabase/mongo/repositories/MongoObservationReason.repo";
import { MongoParentRepo } from "../../newDatabase/mongo/repositories/MongoParent.repo";
import { MongoPaymentTemplateRepo } from "../../newDatabase/mongo/repositories/MongoPaymentTemplate.repo";
import { MongoPostRepo } from "../../newDatabase/mongo/repositories/MongoPost.repo";
import { MongoPreRegistrationRepo } from "../../newDatabase/mongo/repositories/MongoPreRegistration.repo";
import { MongoReactionRepo } from "../../newDatabase/mongo/repositories/MongoReaction.repo";
import { MongoRoleRepo } from "../../newDatabase/mongo/repositories/MongoRole.repo";
import { MongoSchoolRepo } from "../../newDatabase/mongo/repositories/MongoSchool.repo";
import { MongoSchoolYearRepo } from "../../newDatabase/mongo/repositories/MongoSchoolYear.repo";
import { MongoSectionRepo } from "../../newDatabase/mongo/repositories/MongoSection.repo";
import { MongoServiceRepo } from "../../newDatabase/mongo/repositories/MongoService.repo";
import { MongoSessionRepo } from "../../newDatabase/mongo/repositories/MongoSession.repo";
import { MongoSessionTypeRepo } from "../../newDatabase/mongo/repositories/MongoSessionType.repo";
import { MongoSmartCalendarScheduleRepo } from "../../newDatabase/mongo/repositories/MongoSmartCalendarSchedule.repo";
import { MongoSmartCalendarSessionRepo } from "../../newDatabase/mongo/repositories/MongoSmartCalendarSession.repo";
import { MongoSmsSoldHistoryRepo } from "../../newDatabase/mongo/repositories/MongoSmsSoldHistory.repo";
import { MongoStudentRepo } from "../../newDatabase/mongo/repositories/MongoStudent.repo";
import { MongoStudentPaymentConfiguration } from "../../newDatabase/mongo/repositories/MongoStudentPaymentConfiguration.repo";
import { MongoStudentProfileRepo } from "../../newDatabase/mongo/repositories/MongoStudentProfile.repo";
import { MongoSubjectTypeRepo } from "../../newDatabase/mongo/repositories/MongoSubjectType.repo";
import { MongoSubLevelRepo } from "../../newDatabase/mongo/repositories/MongoSubLevel.repo";
import { MongoSubSubjectTypeRepo } from "../../newDatabase/mongo/repositories/MongoSubSubjectType.repo";
import { MongoSupplierRepo } from "../../newDatabase/mongo/repositories/MongoSupplier.repo";
import { MongoTeacherRepo } from "../../newDatabase/mongo/repositories/MongoTeacher.repo";
import { MongoTeacherPaymentConfigurationRepo } from "../../newDatabase/mongo/repositories/MongoTeacherPaymentConfiguration.repo";
import { MongoTeacherPaymentHistoryRepo } from "../../newDatabase/mongo/repositories/MongoTeacherPaymentHistory.repo";
import { MongoTeacherProfileRepo } from "../../newDatabase/mongo/repositories/MongoTeacherProfile.repo";
import { MongoTermRepo } from "../../newDatabase/mongo/repositories/MongoTerm.repo";
import { MongoTransactionRepo } from "../../newDatabase/mongo/repositories/MongoTransaction.repo";
import { MongoTutorialRepo } from "../../newDatabase/mongo/repositories/MongoTutorial.repo";
import { MongoUserPostFeedRepo } from "../../newDatabase/mongo/repositories/MongoUserPostFeed.repo";
import { MongoVerificationCodeRepo } from "../../newDatabase/mongo/repositories/MongoVerificationCode.repo";
import { MongoWeeklySessionRepo } from "../../newDatabase/mongo/repositories/MongoWeeklySession.repo";
import { MongoClassroomRepo } from "./../../newDatabase/mongo/repositories/MongoClassroom.repo";
import { MongoConversationRepo } from "./../../newDatabase/mongo/repositories/MongoConversation.repo";
import { MongoMessageLinksRepo } from "./../../newDatabase/mongo/repositories/MongoMessageLinks.repo";
import { MongoUsersRepo } from "./../../newDatabase/mongo/repositories/MongoUsers.repo";
import { container } from "./container";
import { MongoSignatureRepo } from "../../newDatabase/mongo/repositories/MongoSignature.repo";
import { MongoChapterAttachmentRepo } from "../../newDatabase/mongo/repositories/MongoChapterAttachment.repo";
import { MongoChapterRepo } from "../../newDatabase/mongo/repositories/MongoChapter.repo";


  
  export const registerUseRepos = (): void => {  
  container.bind("SignatureRepo").to(MongoSignatureRepo);  
  container.bind("ChapterRepo").to(MongoChapterRepo);  
  container.bind("ChapterAttachmentRepo").to(MongoChapterAttachmentRepo);
  container.bind("TutorialRepo").to(MongoTutorialRepo);
  container.bind("ObservationRepo").to(MongoObservationRepo);
  container.bind("ObservationReasonRepo").to(MongoObservationReasonRepo);
  container.bind("SmartCalendarSessionRepo").to(MongoSmartCalendarSessionRepo);
  container.bind("SmartCalendarScheduleRepo").to(MongoSmartCalendarScheduleRepo);
  container.bind("TeacherPaymentConfigurationRepo").to(MongoTeacherPaymentConfigurationRepo);
  container.bind("GroupTypeRepo").to(MongoGroupTypeRepo);
  container.bind("VerificationCodeRepo").to(MongoVerificationCodeRepo);
  container.bind("SmsSoldHistoryRepo").to(MongoSmsSoldHistoryRepo);
  container.bind("AlertRepo").to(MongoAlertRepo);
  container.bind("BankTransferRepo").to(MongoBankTransferRepo);
  container.bind("AppVersionRepo").to(MongoAppVersionRepo);
  container.bind("BarCodeRepo").to(MongoBarCodeConfigRepo);
  container.bind("HolidayRepo").to(MongoHolidayRepo);
  container.bind("TeacherPaymentHistoryRepo").to(MongoTeacherPaymentHistoryRepo);
  container.bind("SchoolYearRepo").to(MongoSchoolYearRepo);
  container.bind("RoleRepo").to(MongoRoleRepo);
  container.bind("MasterRepo").to(MongoMasterRepo);
  container.bind("MessageLinksRepo").to(MongoMessageLinksRepo);
  container.bind("ClassGroupRepo").to(MongoClassGroupRepo);
  container.bind("MessageRepo").to(MongoMessageRepo);
  container.bind("ConversationRepo").to(MongoConversationRepo);
  container.bind("MessageAttachmentRepo").to(MongoMessageAttachmentRepo);
  container.bind("HomeworkRepo").to(MongoHomeworkRepo);
  container.bind("SessionRepo").to(MongoSessionRepo);
  container.bind("GradeBookObservationRepo").to(MongoGradeBookObservationRepo);
  container.bind("WeeklySessionRepo").to(MongoWeeklySessionRepo);
  container.bind("TermRepo").to(MongoTermRepo);
  container.bind("PostRepo").to(MongoPostRepo);
  container.bind("NotificationRepo").to(MongoNotificationRepo);
  container.bind("ClassRepo").to(MongoClassRepo);
  container.bind("PreRegistrationRepo").to(MongoPreRegistrationRepo);
  container.bind("PaymentTemplateRepo").to(MongoPaymentTemplateRepo);
  container.bind("IssueReasonRepo").to(MongoIssueReasonRepo);
  container.bind("DiplomaRepo").to(MongoDiplomaRepo);
  container.bind("StudentRepo").to(MongoStudentRepo);
  container.bind("SupplierRepo").to(MongoSupplierRepo);
  container.bind("ExpenseRepo").to(MongoExpenseRepo);
  container.bind("ParentRepo").to(MongoParentRepo);
  container.bind("AdminRepo").to(MongoAdminRepo);
  container.bind("TeacherRepo").to(MongoTeacherRepo);
  container.bind("TransactionRepo").to(MongoTransactionRepo);
  container.bind("NotificationSettingsRepo").to(MongoNotificationSettingsRepo);
  container.bind("SubLevelRepo").to(MongoSubLevelRepo);
  container.bind("LevelRepo").to(MongoLevelRepo);
  container.bind("StudentProfileRepo").to(MongoStudentProfileRepo);
  container.bind("ClassTypeRepo").to(MongoClassTypeRepo);
  container.bind("CentralUserRepo").to(MongoCentralUserRepo);
  container.bind("StudentPaymentConfigurationRepo").to(MongoStudentPaymentConfiguration);
  container.bind("UserPostFeedRepo").to(MongoUserPostFeedRepo);
  container.bind("SubjectTypeRepo").to(MongoSubjectTypeRepo);
  container.bind("TeacherProfileRepo").to(MongoTeacherProfileRepo);
  container.bind("SchoolRepo").to(MongoSchoolRepo);
  container.bind("BankCheckRepo").to(MongoBankCheckRepo);
  container.bind("ClassroomRepo").to(MongoClassroomRepo);
  container.bind("SessionTypeRepo").to(MongoSessionTypeRepo);
  container.bind("ServiceRepo").to(MongoServiceRepo);
  container.bind("SubSubjectTypeRepo").to(MongoSubSubjectTypeRepo);
  container.bind("GroupRepo").to(MongoGroupRepo);
  container.bind("InteractionRepo").to(MongoInteractionRepo);
  container.bind("IssueRepo").to(MongoIssueRepo);
  container.bind("ReactionRepo").to(MongoReactionRepo);
  container.bind("CommentRepo").to(MongoCommentRepo);
  container.bind("UsersRepo").to(MongoUsersRepo);
  container.bind("ExamGradeRepo").to(MongoExamGradeRepo);
  container.bind("ExamTypeRepo").to(MongoExamTypeRepo);
  container.bind("SectionRepo").to(MongoSectionRepo);
  container.bind("InvoiceRepo").to(MongoInvoiceRepo);
  container.bind("SecondaryClassGradesRepo").to(SecondaryClassGradesRepo);
  container.bind("PrimaryClassGradesRepo").to(PrimaryClassGradesRepo);
  container.bind("CambridgeClassGradesRepo").to(CambridgeClassGradesRepo);
  container.bind("IBClassGradesRepo").to(IBClassGradesRepo);
  container.bind("GradeReportTemplateRepo").to(MongoGradeReportTemplateRepo);
  container.bind("AutomaticPromotionGradesRepo").to(AutomaticPromotionGradesRepo);
}