import { AddAdminUseCase } from "../../feature/admins/useCases/AddAdmin.usecase";
import { GetAdminByNewIdUseCase } from "../../feature/admins/useCases/GetAdminByNewId.usecase";
import { GetAdminDashboardUseCase } from "../../feature/dashboards/useCases/getAdminDashboard.usecase";
import { ListAdminsUseCase } from "../../feature/admins/useCases/ListAdmins.usecase";
import { UpdateAdminUseCase } from "../../feature/admins/useCases/UpdateAdmin.usecase";
import { ArchiveAdminUseCase } from "../../feature/archive/useCases/archiveAdmin.usecase";
import { ArchiveParentUseCase } from "../../feature/archive/useCases/archiveParent.usecase";
import { ArchiveStudentUseCase } from "../../feature/archive/useCases/archiveStudent.usecase";
import { ArchiveTeacherUseCase } from "../../feature/archive/useCases/archiveTeacher.usecase";
import { UnArchiveAdminUseCase } from "../../feature/archive/useCases/unarchiveAdmin.usecase";
import { UnArchiveParentUseCase } from "../../feature/archive/useCases/unarchiveParent.usecase";
import { UnArchiveStudentUseCase } from "../../feature/archive/useCases/unarchiveStudent.usecase";
import { UnArchiveTeacherUseCase } from "../../feature/archive/useCases/unarchiveTeacher.usecase";
import { ForgetPasswordUseCase } from "../../feature/authentication/useCases/ForgetPassowrd.usecase";
import { LoginUseCase } from "../../feature/authentication/useCases/Login.usecase";
import { LoginByMasterUseCase } from "../../feature/authentication/useCases/LoginByMaster.usecase";
import { LogoutUseCase } from "../../feature/authentication/useCases/Logout.usecase";
import { ResendInvitationUseCase } from "../../feature/authentication/useCases/ResendInvitation.usecase";
import { ResetPasswordUseCase } from "../../feature/authentication/useCases/ResetPassword.usecase";
import { ResetUserPasswordUseCase } from "../../feature/authentication/useCases/ResetUserPassword.usecase";
import { SwitchToUserUseCase } from "../../feature/authentication/useCases/SwitchToUser.usecase";
import { UpdateCurrentUserPasswordUseCase } from "../../feature/authentication/useCases/UpdateCurrentUserPassword.usecase";
import { VerifyCodeUseCase } from "../../feature/authentication/useCases/VerifyCode.usecase";
import { AddRoleUseCase } from "../../feature/authorization/useCases/AddRole.usecase";
import { DeleteRoleUseCase } from "../../feature/authorization/useCases/DeleteRole.usecase";
import { GetOneRoleUseCase } from "../../feature/authorization/useCases/GetOneRole.usecase";
import { ListRolesUseCase } from "../../feature/authorization/useCases/ListRoles.usecase";
import { UpdateRoleUseCase } from "../../feature/authorization/useCases/UpdateRole.usecase";
import { AddClassUseCase } from "../../feature/classes/useCases/AddClass.usecase";
import { AssignStudentToClassUseCase } from "../../feature/classes/useCases/AssignStudentToClass.usecase";
import { AssignTeachersToSubjectsInClassUseCase } from "../../feature/classes/useCases/AssignTeacherToSubjectInClass.usecase";
import { AssignTeacherToSubSubjectInClassUseCase } from "../../feature/classes/useCases/AssignTeacherToSubSubjectInClass.usecase";
import { DeleteClassUseCase } from "../../feature/classes/useCases/DeleteClass.usecase";
import { GetClassDashboardUseCase } from "../../feature/classes/useCases/GetClassDashboard.usecase";
import { GetClassListUseCase } from "../../feature/classes/useCases/GetClassList.usecase";
import { GetClassOverviewUseCase } from "../../feature/classes/useCases/GetClassOverview.usecase";
import { GetGroupsOfClassUseCase } from "../../feature/classes/useCases/GetGroupsOfClass.usecase";
import { GetStudentsCodeBarePdfUseCase } from "../../feature/classes/useCases/GetStudentsCodeBarePdf.usecase";
import { GetStudentsOfClassUseCase } from "../../feature/classes/useCases/GetStudentsOfClass.usecase";
import { GetSubjectTypesOfClassUseCase } from "../../feature/classes/useCases/GetSubjectTypesOfClass.usecase";
import { GetTeacherClassAndGroupsUseCase } from "../../feature/classes/useCases/GetTeacherClassAndGroups.usecase";
import { ListClassesUseCase } from "../../feature/classes/useCases/ListClasses.usecase";
import { ListClassesByTeacherUseCase } from "../../feature/classes/useCases/ListClassesByTeacher.usecase";
import { UpdateClassUseCase } from "../../feature/classes/useCases/UpdateClass.usecase";
import { DeleteClassroomUseCase } from "../../feature/classrooms/useCases/DeleteClassroom.usecase";
import { GetAvailableClassroomUseCase } from "../../feature/classrooms/useCases/GetAvailableClassroom.usecase";
import { GetAvailableClassroomInWeeklySessionUseCase } from "../../feature/classrooms/useCases/GetAvailableClassroomInWeeklySession.usecase";
import { ListClassroomsUseCase } from "../../feature/classrooms/useCases/ListClassrooms.usecase";
import { UpdateClassroomUseCase } from "../../feature/classrooms/useCases/UpdateClassroom.usecase";
import { AddClassTypeUseCase } from "../../feature/classTypes/useCases/addClassTypes.usecase";
import { AddFieldToClasstypeUseCase } from "../../feature/classTypes/useCases/AddFieldToClasstype.usecase";
import { AddSubjectToClassTypeUseCase } from "../../feature/classTypes/useCases/AddSubjectToClassType.usecase";
import { AddSubSubjectToClassTypeUseCase } from "../../feature/classTypes/useCases/AddSubSubjectToClassType.usecase";
import { DeleteClassTypeUseCase } from "../../feature/classTypes/useCases/DeleteClassType.usecase";
import { DeleteFieldFromClassTypeUseCase } from "../../feature/classTypes/useCases/DeleteFieldFromClassType.usecase";
import { DeleteSubjectFromClassTypeUseCase } from "../../feature/classTypes/useCases/DeleteSubjectFromClassType.usecase";
import { DeleteSubSubjectFromClassTypeUseCase } from "../../feature/classTypes/useCases/DeleteSubSubjectFromClassType.usecase";
import { GetClassTypeUseCase } from "../../feature/classTypes/useCases/GetClassType.usecase";
import { GetFieldsOfClassTypeUseCase } from "../../feature/classTypes/useCases/GetFieldsOfClassTypes.usecase";
import { GetSubjectsOfClassTypesUseCase } from "../../feature/classTypes/useCases/GetSubjectsOfClassTypes.usecase";
import { ListClassTypeUseCase } from "../../feature/classTypes/useCases/ListClassTypes.usecase";
import { ListNextClassTypesUseCase } from "../../feature/classTypes/useCases/ListNextClassTypes.usecase";
import { ReorderFieldsOfClassTypesUseCase } from "../../feature/classTypes/useCases/ReorderFieldsOfClassType.usecase";
import { ReorderSubjectInClassTypeUseCase } from "../../feature/classTypes/useCases/ReorderSubjectInClassType.usecase";
import { ReorderSubSubjectInClassTypeUseCase } from "../../feature/classTypes/useCases/ReorderSubSubjectInClassType.usecase";
import { UpdateClassTypeUseCase } from "../../feature/classTypes/useCases/updateClassTypes.usecase";
import { UpdateFieldOfClassTypeUseCase } from "../../feature/classTypes/useCases/UpdateFieldOfClassType.usecase";
import { UpdateSubjectFromClassTypeUseCase } from "../../feature/classTypes/useCases/UpdateSubjectOfClassType.usecase";
import { UpdateSubSubjectOfClassTypeUseCase } from "../../feature/classTypes/useCases/UpdateSubSubjectOfClassType.usecase";
import { AddGroupUseCase } from "../../feature/groupManagement/useCases/AddGroup.usecase";
import { AssignStudentToGroupUseCase } from "../../feature/groupManagement/useCases/AssignStudentToGroup.usecase";
import { CheckGroupUseCase } from "../../feature/groupManagement/useCases/CheckGroup.usecase";
import { DeleteGroupUseCase } from "../../feature/groupManagement/useCases/DeleteGroup.usecase";
import { GetGroupListUseCase } from "../../feature/groupManagement/useCases/GetGroupList.usecase";
import { GetGroupsOfStudentUseCase } from "../../feature/groupManagement/useCases/GetGroupsOfStudent.usecase";
import { GetGroupsOfTeacherUseCase } from "../../feature/groupManagement/useCases/GetGroupsOfTeacher.usecase";
import { GetStudentsOfGroupUseCase } from "../../feature/groupManagement/useCases/GetStudentsOfGroup.usecase";
import { GetGroupOverviewUseCase } from "../../feature/groupManagement/useCases/GroupOverview.usecase";
import { ListTeacherGroupUseCase } from "../../feature/groupManagement/useCases/ListTeacherGroup.usecase";
import { ListUnenrolledStudentsForGroupUseCase } from "../../feature/groupManagement/useCases/ListUnenrolledStudentsForGroup.usecase";
import { UnassignStudentFromGroupUseCase } from "../../feature/groupManagement/useCases/UnassignStudentFromGroup.usecase";
import { UpdateGroupUseCase } from "../../feature/groupManagement/useCases/UpdateGroup.usecase";
import { UpdateGroupTeacherUseCase } from "../../feature/groupManagement/useCases/UpdateGroupTeacher.usecase";
import { AddGroupTypeUseCase } from "../../feature/groupType/useCases/AddGroupType.usecase";
import { DeleteGroupTypeUseCase } from "../../feature/groupType/useCases/DeleteGroupType.usecase";
import { ListGroupTypesUseCase } from "../../feature/groupType/useCases/ListGroupTypes.usecase";
import { UpdateGroupTypeUseCase } from "../../feature/groupType/useCases/UpdateGroupType.usecase";
import { AddLevelUseCase } from "../../feature/levels/useCases/AddLevel.usecase";
import { DeleteLevelUseCase } from "../../feature/levels/useCases/DeleteLevel.usecase";
import { GetLevelsOverviewUseCase } from "../../feature/levels/useCases/GetLevelsOverview.usecase";
import { ReorderLevelsUseCase } from "../../feature/levels/useCases/ReorderLevels.usecase";
import { UpdateLevelUseCase } from "../../feature/levels/useCases/UpdateLevel.usecase";
import { AddMasterUseCase } from "../../feature/masters/useCases/AddMaster.usecase";
import { DeleteMasterUseCase } from "../../feature/masters/useCases/DeleteMaster.usecase";
import { ListMastersUseCase } from "../../feature/masters/useCases/ListMasters.usecase";
import { UpdateMasterUseCase } from "../../feature/masters/useCases/UpdateMaster.usecase";
import { UpdateAppVersionUseCase } from "../../feature/masters/useCases/updateOsVersion.usecase";
import { AddMessageUseCase } from "../../feature/messages/useCases/AddMessage.usecase";
import { GetMessageReactionsUseCase } from "../../feature/messages/useCases/GetMessageReactions.usercase";
import { ListConversationParticipantsUseCase } from "../../feature/messages/useCases/ListConversationParticipants.usecase";
import { ListConversationsUseCase } from "../../feature/messages/useCases/ListConversations.usecase";
import { ReactToMessageUseCase } from "../../feature/messages/useCases/ReactToMessage.usecase";
import { AddParentUseCase } from "../../feature/parents/useCases/AddParent.usecase";
import { GetChildrenOfParentUseCase } from "../../feature/parents/useCases/GetChildrenOfParent.usecase";
import { GetParentByNewIdUseCase } from "../../feature/parents/useCases/GetParentByNewId.usecase";
import { ListParentsUseCase } from "../../feature/parents/useCases/ListParents.usecase";
import { UpdateParentUseCase } from "../../feature/parents/useCases/UpdateParent.usecase";
import { ApplyWeeklyScheduleForClassUseCase } from "../../feature/schedules/useCases/ApplyWeeklyScheduleForClass.usecase";
import { ApplyWeeklyScheduleForGroupUseCase } from "../../feature/schedules/useCases/ApplyWeeklyScheduleForGroup.usecase";
import { DeleteSessionUseCase } from "../../feature/schedules/useCases/DeleteSession.usecase";
import { GetEntityScheduleUseCase } from "../../feature/schedules/useCases/GetEntitySchedule.usecase";
import { GetScheduleUseCase } from "../../feature/schedules/useCases/GetSchedule.usecase";
import { AddSchoolUseCase } from "../../feature/schools/useCases/AddSchool.usecase";
import { GetSchoolDetailsUseCase } from "../../feature/schools/useCases/GetSchoolInformation.usecase";
import { ListSchoolsUseCase } from "../../feature/schools/useCases/ListSchools.usecase";
import { SwitchToSchoolUsecase } from "../../feature/schools/useCases/SwitchToSchool.usecase";
import { UpdateFlagsUseCase } from "../../feature/schools/useCases/UpdateFlags.usecase";
import { UpdateSchoolUseCase } from "../../feature/schools/useCases/UpdateSchool.usecase";
import { AddSchoolYearUseCase } from "../../feature/schoolYears/useCases/AddSchoolYear.usecase";
import { ListSchoolYearUseCase } from "../../feature/schoolYears/useCases/ListSchoolYear.usecase";
import { UpdateSchoolYearUseCase } from "../../feature/schoolYears/useCases/UpdateSchoolYear.usecase";
import { AddSessionForClassUseCase } from "../../feature/sessionManagement/useCases/AddSessionForClass.usecase";
import { AddSessionForGroupUseCase } from "../../feature/sessionManagement/useCases/AddSessionForGroup.usecase";
import { GetSessionDetailsUseCase } from "../../feature/sessionManagement/useCases/getSessionDetails.usecase";
import { UpdateSessionDetailsUseCase } from "../../feature/sessionManagement/useCases/updateSessionDetails.usecase";
import { UpdateSessionForClassUseCase } from "../../feature/sessionManagement/useCases/UpdateSessionForClass.usecase";
import { UpdateSessionForGroupUseCase } from "../../feature/sessionManagement/useCases/UpdateSessionForGroup.usecase";
import { AddSessionTypeUseCase } from "../../feature/sessionTypes/usecases/AddSessionType.usecase";
import { DeleteSessionTypeUseCase } from "../../feature/sessionTypes/usecases/DeleteSessionType.usecase";
import { ListSessionTypeUseCase } from "../../feature/sessionTypes/usecases/ListSessionType.usecase";
import { UpdateSessionTypeUseCase } from "../../feature/sessionTypes/usecases/UpdateSessionType.usecase";
import { AddStudentUseCase } from "../../feature/students/useCases/AddStudent.usecase";
import { GetStudentAttendanceCertificateUseCase } from "../../feature/students/useCases/GetStudentAttendanceCertificate.usecase";
import { GetStudentProfileUseCase } from "../../feature/students/useCases/GetStudentProfile.usecase";
import { ImportStudentsUseCase } from "../../feature/students/useCases/ImportStudents.usecase";
import { ToggleUserActivationUseCase } from "../../feature/students/useCases/ToggleUserActivation.usecase";
import { UpdateStudentUseCase } from "../../feature/students/useCases/UpdateStudent.usecase";
import { AddSubjectTypeUseCase } from "../../feature/subjectTypes/useCases/AddSubjectType.usecase";
import { DeleteSubjectTypeUseCase } from "../../feature/subjectTypes/useCases/DeleteSubjectType.usecase";
import { UpdateSubjectTypeUseCase } from "../../feature/subjectTypes/useCases/UpdateSubjectType.usecase";
import { AddSubLevelUseCase } from "../../feature/subLevels/useCases/AddSubLevel.usecase";
import { DeleteSubLevelUseCase } from "../../feature/subLevels/useCases/DeleteSubLevel.usecase";
import { ReorderSubLevelsUseCase } from "../../feature/subLevels/useCases/ReorderSubLevels.usecase";
import { UpdateSubLevelUseCase } from "../../feature/subLevels/useCases/UpdateSubLevel.usecase";
import { AddSubSubjectTypeUseCase } from "../../feature/subSubjectTypes/usecases/AddSubSubjectType.usecase";
import { DeleteSubSubjectTypeUseCase } from "../../feature/subSubjectTypes/usecases/DeleteSubSubjectType.usecase";
import { ListSubSubjectTypeUseCase } from "../../feature/subSubjectTypes/usecases/ListSubSubjectType.usecase";
import { UpdateSubSubjectTypeUsecase } from "../../feature/subSubjectTypes/usecases/UpdateSubSubjectType.usecase";
import { AddTeacherUseCase } from "../../feature/teachers/useCases/AddTeacher.usecase";
import { GetTeacherProfileUsecase } from "../../feature/teachers/useCases/GetTeacherProfile.usecase";
import { GetTeachersOfStudentUseCase } from "../../feature/teachers/useCases/GetTeachersOfStudent.usecase";
import { ListTeachersUseCase } from "../../feature/teachers/useCases/ListTeachers.usecase";
import { UpdateTeacherUseCase } from "../../feature/teachers/useCases/UpdateTeacher.usecase";
import { UploadAvatarUseCase } from "../../feature/users/useCases/UploadAvatar.usecase";
import { GetDraftWeeklyScheduleUseCase } from "../../feature/weeklySchedule/useCases/GetDraftWeeklySchedule.usecase";
import { GetNonDraftWeeklyScheduleUseCase } from "../../feature/weeklySchedule/useCases/GetNonDraftWeeklySchedule.usecase";
import { AddWeeklySessionForClassUseCase } from "../../feature/weeklySessions/useCases/AddWeeklySessionForClass.usecase";
import { AddWeeklySessionForGroupUseCase } from "../../feature/weeklySessions/useCases/AddWeeklySessionForGroup.usecase";
import { DeleteWeeklySessionUseCase } from "../../feature/weeklySessions/useCases/DeleteWeeklySession.usecase";
import { UpdateWeeklySessionForClassUseCase } from "../../feature/weeklySessions/useCases/UpdateWeeklySessionForClass.usecase";
import { UpdateWeeklySessionForGroupUseCase } from "../../feature/weeklySessions/useCases/UpdateWeeklySessionForGroup.usecase";
import { GetAppVersionUseCase } from "./../../feature/masters/useCases/getAllAppsVersion.usecase";
import { AddDirectConversationUseCase } from "./../../feature/messages/useCases/AddDirectConversation.usecase";
import { AddGroupConversationUseCase } from "./../../feature/messages/useCases/AddGroupConversation.usecase";
import { AddParticipantsToConversationUseCase } from "./../../feature/messages/useCases/AddParticipantsToConversation.usecase";
import { DeleteMessageUseCase } from "./../../feature/messages/useCases/DeleteMessage.usecase";
import { GetConversationUseCase } from "./../../feature/messages/useCases/getConversation.usecase";
import { ListConversationAttachmentsUseCase } from "./../../feature/messages/useCases/ListConversationAttachments.usecase";
import { ListConversationLinksUseCase } from "./../../feature/messages/useCases/ListConversationLinks.usecase";
import { ListConversationMessagesUseCase } from "./../../feature/messages/useCases/ListConversationMessages.usecase";
import { ListConversationMultimediaUseCase } from "./../../feature/messages/useCases/ListConversationMultimedia.usecase";
import { FindUsersByFullNameUseCase } from "./../../feature/messages/useCases/ListTargetUsers.usecase";
import { ListTargetUsersForGroupConversationAssignmentUseCase } from "./../../feature/messages/useCases/ListTargetUsersForGroupConversationAssignment.usecase";
import { RemoveParticipantsFromConversationUseCase } from "./../../feature/messages/useCases/RemoveParticipantsFromConversation.usecase";
import { UpdateConversationNameUseCase } from "./../../feature/messages/useCases/UpdateConversationName.usecase";
import { UpdateConversationSeenStatusUseCase } from "./../../feature/messages/useCases/UpdateConversationSeenStatus.usecase";
import { UpdateSmsSoldUseCase } from "./../../feature/schools/useCases/UpdateSmsSold.usecase";
import { CancelSessionUseCase } from "./../../feature/sessionManagement/useCases/cancelSession.usecase";
import { CloseSessionUseCase } from "./../../feature/sessionManagement/useCases/closeSession.usecase";
import { ConfirmAttendanceUseCase } from "./../../feature/sessionManagement/useCases/confirmAttendance.usecase";
import { StartSessionUseCase } from "./../../feature/sessionManagement/useCases/startSession.usecase";
import { UpdateSessionStatusUseCase } from "./../../feature/sessionManagement/useCases/updateSessionStatus.usecase";
import { SwitchStudentsClassUseCase } from "./../../feature/students/useCases/switchStudentsClass.usecase";
import { VerifyAndFetchUsersUseCase } from "./../../feature/users/useCases/verifyUsersExistence.usecase";
import { container } from './container';
import { ListStudentsUseCase } from "../../feature/students/useCases/ListStudents.usecase"
import { GetChildAttendanceStatsUseCase } from "../../feature/parents/useCases/GetChildAttendanceStats.usecase"
import { GetTeacherDashboardUseCase } from "../../feature/dashboards/useCases/GetTeacherDashboard.usecase"
import { GetParentDashboardUseCase } from "../../feature/dashboards/useCases/GetParentDashboard.usecase"
import { GetStudentDashboardUseCase } from "../../feature/dashboards/useCases/GetStudentDashboard.usecase"
import { UnAssignTeacherFromSubSubjectUseCase } from '../../feature/classes/useCases/UnAssignTeacherFromSubSubject.usecase';
import { UnAssignTeacherFromSubjectUseCase } from '../../feature/classes/useCases/UnAssignTeacherFromSubject.usecase';
import { UnassignStudentFromClassUseCase } from '../../feature/classes/useCases/UnassignStudentFromClass.usecase';
import { GetSubjectsOfClassUseCase } from '../../feature/classes/useCases/GetSubjectsOfClass.usecase';
import { UpdateStudentGroupUseCase } from '../../feature/classes/useCases/UpdateStudentGroup.usecase';
import { AddClassroomUseCase } from "../../feature/classrooms/useCases/AddClassroom.usecase";

export const registerUseCases = (): void => {  
  container.bind("GetChildAttendanceStatsUseCase").to(GetChildAttendanceStatsUseCase);  
  container.bind("GetTeacherDashboardUseCase").to(GetTeacherDashboardUseCase);  
  container.bind("GetParentDashboardUseCase").to(GetParentDashboardUseCase);  
  container.bind("GetStudentDashboardUseCase").to(GetStudentDashboardUseCase);  
  container.bind("GetTeachersOfStudentUseCase").to(GetTeachersOfStudentUseCase);  
  container.bind("GetSubjectTypesOfClassUseCase").to(GetSubjectTypesOfClassUseCase);  
  container.bind("GetGroupsOfStudentUseCase").to(GetGroupsOfStudentUseCase);
  container.bind("UnAssignTeacherFromSubSubjectUseCase").to(UnAssignTeacherFromSubSubjectUseCase);  
  container.bind("UnAssignTeacherFromSubjectUseCase").to(UnAssignTeacherFromSubjectUseCase);  
  container.bind("UnassignStudentFromClassUseCase").to(UnassignStudentFromClassUseCase);  
  container.bind("GetSubjectsOfClassUseCase").to(GetSubjectsOfClassUseCase);  
  container.bind("UpdateStudentGroupUseCase").to(UpdateStudentGroupUseCase);  
  container.bind("UpdateGroupTypeUseCase").to(UpdateGroupTypeUseCase);  
  container.bind("GetTeacherClassAndGroupsUseCase").to(GetTeacherClassAndGroupsUseCase);  
  container.bind("GetStudentsCodeBarePdfUseCase").to(GetStudentsCodeBarePdfUseCase);  
  container.bind("GetClassListUseCase").to(GetClassListUseCase);  
  container.bind("GetClassDashboardUseCase").to(GetClassDashboardUseCase);  
  container.bind("AssignTeacherToSubSubjectInClassUseCase").to(AssignTeacherToSubSubjectInClassUseCase);  
  container.bind("AssignTeachersToSubjectsInClassUseCase").to(AssignTeachersToSubjectsInClassUseCase);  
  container.bind("AddClassUseCase").to(AddClassUseCase);  
  container.bind("AssignStudentToClassUseCase").to(AssignStudentToClassUseCase);  
  container.bind("ListGroupTypesUseCase").to(ListGroupTypesUseCase);  
  container.bind("DeleteGroupTypeUseCase").to(DeleteGroupTypeUseCase);  
  container.bind("AddGroupTypeUseCase").to(AddGroupTypeUseCase);  
  container.bind("ListClassroomsUseCase").to(ListClassroomsUseCase);  
  container.bind("UpdateGroupTeacherUseCase").to(UpdateGroupTeacherUseCase);  
  container.bind("DeleteGroupUseCase").to(DeleteGroupUseCase);  
  container.bind("UpdateGroupUseCase").to(UpdateGroupUseCase);  
  container.bind("GetGroupsOfTeacherUseCase").to(GetGroupsOfTeacherUseCase);  
  container.bind("UnassignStudentFromGroupUseCase").to(UnassignStudentFromGroupUseCase);  
  container.bind("ListUnenrolledStudentsForGroupUseCase").to(ListUnenrolledStudentsForGroupUseCase);  
  container.bind("GetGroupListUseCase").to(GetGroupListUseCase);  
  container.bind("AddGroupUseCase").to(AddGroupUseCase);  
  container.bind("CheckGroupUseCase").to(CheckGroupUseCase);  
  container.bind("AssignStudentToGroupUseCase").to(AssignStudentToGroupUseCase);  
  container.bind("UpdateWeeklySessionForGroupUseCase").to(UpdateWeeklySessionForGroupUseCase);  
  container.bind("AddWeeklySessionForGroupUseCase").to(AddWeeklySessionForGroupUseCase);  
  container.bind("UpdateSessionForGroupUseCase").to(UpdateSessionForGroupUseCase);  
  container.bind("AddSessionForGroupUseCase").to(AddSessionForGroupUseCase);  
  container.bind("ApplyWeeklyScheduleForGroupUseCase").to(ApplyWeeklyScheduleForGroupUseCase);
  container.bind("GetLevelsOverviewUseCase").to(GetLevelsOverviewUseCase);  
  container.bind("ResetUserPasswordUseCase").to(ResetUserPasswordUseCase);  
  container.bind("ListTeachersUseCase").to(ListTeachersUseCase);  
  container.bind("GetStudentAttendanceCertificateUseCase").to(GetStudentAttendanceCertificateUseCase);  
  container.bind("GetChildrenOfParentUseCase").to(GetChildrenOfParentUseCase);  
  container.bind("GetAdminByNewIdUseCase").to(GetAdminByNewIdUseCase);  
  container.bind("ListAdminsUseCase").to(ListAdminsUseCase);  
  container.bind("GetParentByNewIdUseCase").to(GetParentByNewIdUseCase);  
  container.bind("ListParentsUseCase").to(ListParentsUseCase);
  container.bind("ToggleUserActivationUseCase").to(ToggleUserActivationUseCase);
  container.bind("LoginByMasterUseCase").to(LoginByMasterUseCase);
  container.bind("LoginUseCase").to(LoginUseCase);
  container.bind("LogoutUseCase").to(LogoutUseCase);
  container.bind("ResetPasswordUseCase").to(ResetPasswordUseCase);
  container.bind("VerifyCodeUseCase").to(VerifyCodeUseCase);
  container.bind("ForgetPasswordUseCase").to(ForgetPasswordUseCase);
  container.bind("UpdateCurrentUserPasswordUseCase").to(UpdateCurrentUserPasswordUseCase);
  container.bind("UploadAvatarUseCase").to(UploadAvatarUseCase);
  container.bind("GetNonDraftWeeklyScheduleUseCase").to(GetNonDraftWeeklyScheduleUseCase);
  container.bind("AddTeacherUseCase").to(AddTeacherUseCase);
  container.bind("ListSessionTypeUseCase").to(ListSessionTypeUseCase);
  container.bind("UpdateWeeklySessionForClassUseCase").to(UpdateWeeklySessionForClassUseCase);
  container.bind("AddWeeklySessionForClassUseCase").to(AddWeeklySessionForClassUseCase);
  container.bind("UpdateSessionForClassUseCase").to(UpdateSessionForClassUseCase);
  container.bind("AddSessionForClassUseCase").to(AddSessionForClassUseCase);
  container.bind("ApplyWeeklyScheduleForClassUseCase").to(ApplyWeeklyScheduleForClassUseCase);
  container.bind("GetEntityScheduleUseCase").to(GetEntityScheduleUseCase);
  container.bind("GetAvailableClassroomInWeeklySessionUseCase").to(GetAvailableClassroomInWeeklySessionUseCase);
  container.bind("GetAvailableClassroomUseCase").to(GetAvailableClassroomUseCase);
  container.bind("DeleteWeeklySessionUseCase").to(DeleteWeeklySessionUseCase);
  container.bind("DeleteSessionUseCase").to(DeleteSessionUseCase);
  container.bind("GetDraftWeeklyScheduleUseCase").to(GetDraftWeeklyScheduleUseCase);
  container.bind("GetScheduleUseCase").to(GetScheduleUseCase);
  container.bind("ImportStudentsUseCase").to(ImportStudentsUseCase);
  container.bind("AddParentUseCase").to(AddParentUseCase);
  container.bind("AddAdminUseCase").to(AddAdminUseCase);
  container.bind("AddStudentUseCase").to(AddStudentUseCase);
  container.bind("GetClassTypeUseCase").to(GetClassTypeUseCase);
  container.bind("UpdateSchoolYearUseCase").to(UpdateSchoolYearUseCase);
  container.bind("AddSchoolYearUseCase").to(AddSchoolYearUseCase);
  container.bind("ReorderSubLevelsUseCase").to(ReorderSubLevelsUseCase);
  container.bind("DeleteClassroomUseCase").to(DeleteClassroomUseCase);
  container.bind("UpdateClassroomUseCase").to(UpdateClassroomUseCase);
  container.bind("GetStudentsOfGroupUseCase").to(GetStudentsOfGroupUseCase);
  container.bind("GetGroupsOfClassUseCase").to(GetGroupsOfClassUseCase);
  container.bind("GetStudentsOfClassUseCase").to(GetStudentsOfClassUseCase);
  container.bind("ReorderLevelsUseCase").to(ReorderLevelsUseCase);
  container.bind("AddClassroomUseCase").to(AddClassroomUseCase);
  container.bind("DeleteSessionTypeUseCase").to(DeleteSessionTypeUseCase);
  container.bind("UpdateSessionTypeUseCase").to(UpdateSessionTypeUseCase);
  container.bind("AddSessionTypeUseCase").to(AddSessionTypeUseCase);
  container.bind("DeleteSubSubjectTypeUseCase").to(DeleteSubSubjectTypeUseCase);
  container.bind("UpdateClassUseCase").to(UpdateClassUseCase);
  container.bind("DeleteClassUseCase").to(DeleteClassUseCase);
  container.bind("AddMessageUseCase").to(AddMessageUseCase);
  container.bind("ListConversationsUseCase").to(ListConversationsUseCase);
  container.bind("ListConversationMessagesUseCase").to(ListConversationMessagesUseCase);
  container.bind("ListConversationLinksUseCase").to(ListConversationLinksUseCase);
  container.bind("ListConversationAttachmentsUseCase").to(ListConversationAttachmentsUseCase);
  container.bind("ListConversationMultimediaUseCase").to(ListConversationMultimediaUseCase);
  container.bind("AddDirectConversationUseCase").to(AddDirectConversationUseCase);
  container.bind("GetSessionDetailsUseCase").to(GetSessionDetailsUseCase);
  container.bind("ReactToMessageUseCase").to(ReactToMessageUseCase);
  container.bind("VerifyAndFetchUsersUseCase").to(VerifyAndFetchUsersUseCase);
  container.bind("FindUsersByFullNameUseCase").to(FindUsersByFullNameUseCase);
  container.bind("GetConversationUseCase").to(GetConversationUseCase);
  container.bind("ListClassTypeUseCase").to(ListClassTypeUseCase);
  container.bind("AddFieldToClasstypeUseCase").to(AddFieldToClasstypeUseCase);
  container.bind("AddSubSubjectToClassTypeUseCase").to(AddSubSubjectToClassTypeUseCase);
  container.bind("AddSubjectToClassTypeUseCase").to(AddSubjectToClassTypeUseCase);
  container.bind("GetFieldsOfClassTypeUseCase").to(GetFieldsOfClassTypeUseCase);
  container.bind("GetSubjectsOfClassTypesUseCase").to(GetSubjectsOfClassTypesUseCase);
  container.bind("ListNextClassTypesUseCase").to(ListNextClassTypesUseCase);
  container.bind("ReorderFieldsOfClassTypesUseCase").to(ReorderFieldsOfClassTypesUseCase);
  container.bind("ReorderSubSubjectInClassTypeUseCase").to(ReorderSubSubjectInClassTypeUseCase);
  container.bind("ReorderSubjectInClassTypeUseCase").to(ReorderSubjectInClassTypeUseCase);
  container.bind("UpdateClassTypeUseCase").to(UpdateClassTypeUseCase);
  container.bind("DeleteMessageUseCase").to(DeleteMessageUseCase);
  container.bind("DeleteFieldFromClassTypeUseCase").to(DeleteFieldFromClassTypeUseCase);
  container.bind("DeleteSubSubjectFromClassTypeUseCase").to(DeleteSubSubjectFromClassTypeUseCase);
  container.bind("DeleteSubjectFromClassTypeUseCase").to(DeleteSubjectFromClassTypeUseCase);
  container.bind("AddGroupConversationUseCase").to(AddGroupConversationUseCase);
  container.bind("AddParticipantsToConversationUseCase").to(AddParticipantsToConversationUseCase);
  container.bind("ListMastersUseCase").to(ListMastersUseCase);
  container.bind("ListTargetUsersForGroupConversationAssignmentUseCase").to(ListTargetUsersForGroupConversationAssignmentUseCase);
  container.bind("ListRolesUseCase").to(ListRolesUseCase);
  container.bind("UpdateSubSubjectOfClassTypeUseCase").to(UpdateSubSubjectOfClassTypeUseCase);
  container.bind("ListSubSubjectTypeUseCase").to(ListSubSubjectTypeUseCase);
  container.bind("UpdateFieldOfClassTypeUseCase").to(UpdateFieldOfClassTypeUseCase);
  container.bind("UpdateLevelUseCase").to(UpdateLevelUseCase);
  container.bind("AddRoleUseCase").to(AddRoleUseCase);
  container.bind("UpdateRoleUseCase").to(UpdateRoleUseCase);
  container.bind("AddSubLevelUseCase").to(AddSubLevelUseCase);
  container.bind("UpdateSubLevelUseCase").to(UpdateSubLevelUseCase);
  container.bind("DeleteSubLevelUseCase").to(DeleteSubLevelUseCase);
  container.bind("GetOneRoleUseCase").to(GetOneRoleUseCase);
  container.bind("DeleteRoleUseCase").to(DeleteRoleUseCase);
  container.bind("ConfirmAttendanceUseCase").to(ConfirmAttendanceUseCase);
  container.bind("AddSubjectTypeUseCase").to(AddSubjectTypeUseCase);
  container.bind("UpdateSubjectTypeUseCase").to(UpdateSubjectTypeUseCase);
  container.bind("AddMasterUseCase").to(AddMasterUseCase);
  container.bind("DeleteSubjectTypeUseCase").to(DeleteSubjectTypeUseCase);
  container.bind("AddSubSubjectTypeUseCase").to(AddSubSubjectTypeUseCase);
  container.bind("DeleteClassTypeUseCase").to(DeleteClassTypeUseCase);
  container.bind("UpdateSubSubjectTypeUsecase").to(UpdateSubSubjectTypeUsecase);
  container.bind("ListSchoolYearUseCase").to(ListSchoolYearUseCase);
  container.bind("UpdateMasterUseCase").to(UpdateMasterUseCase);
  container.bind("DeleteMasterUseCase").to(DeleteMasterUseCase);
  container.bind("ListSchoolsUseCase").to(ListSchoolsUseCase);
  container.bind("CloseSessionUseCase").to(CloseSessionUseCase);
  container.bind("ListClassesUseCase").to(ListClassesUseCase);
  container.bind("ListClassesByTeacherUseCase").to(ListClassesByTeacherUseCase);
  container.bind("SwitchToSchoolUsecase").to(SwitchToSchoolUsecase);
  container.bind("AddSchoolUseCase").to(AddSchoolUseCase);
  container.bind("UpdateSchoolUseCase").to(UpdateSchoolUseCase);
  container.bind("CancelSessionUseCase").to(CancelSessionUseCase);
  container.bind("StartSessionUseCase").to(StartSessionUseCase);
  container.bind("UpdateSessionDetailsUseCase").to(UpdateSessionDetailsUseCase);
  container.bind("GetAllAppsVersionUseCase").to(GetAppVersionUseCase);
  container.bind("ArchiveAdminUseCase").to(ArchiveAdminUseCase);
  container.bind("ArchiveParentUseCase").to(ArchiveParentUseCase);
  container.bind("ArchiveStudentUseCase").to(ArchiveStudentUseCase);
  container.bind("ArchiveTeacherUseCase").to(ArchiveTeacherUseCase);
  container.bind("AddClassTypeUseCase").to(AddClassTypeUseCase);
  container.bind("RemoveParticipantsFromConversationUseCase").to(RemoveParticipantsFromConversationUseCase);
  container.bind("UpdateConversationNameUseCase").to(UpdateConversationNameUseCase);
  container.bind("UpdateConversationSeenStatusUseCase").to(UpdateConversationSeenStatusUseCase);
  container.bind("ListConversationParticipantsUseCase").to(ListConversationParticipantsUseCase);
  container.bind("GetMessageReactionsUseCase").to(GetMessageReactionsUseCase);
  container.bind("UpdateSubjectFromClassTypeUseCase").to(UpdateSubjectFromClassTypeUseCase);
  container.bind("AddLevelUseCase").to(AddLevelUseCase);
  container.bind("DeleteLevelUseCase").to(DeleteLevelUseCase);
  container.bind("ListTeacherGroupUseCase").to(ListTeacherGroupUseCase);
  container.bind("UpdateFlagsUseCase").to(UpdateFlagsUseCase);
  container.bind("UpdateSessionStatusUseCase").to(UpdateSessionStatusUseCase);
  container.bind("GetSchoolDetailsUseCase").to(GetSchoolDetailsUseCase);
  container.bind("UpdateAppVersionUseCase").to(UpdateAppVersionUseCase);
  container.bind("UnArchiveAdminUseCase").to(UnArchiveAdminUseCase);
  container.bind("UnArchiveParentUseCase").to(UnArchiveParentUseCase);
  container.bind("UnArchiveStudentUseCase").to(UnArchiveStudentUseCase);
  container.bind("UnArchiveTeacherUseCase").to(UnArchiveTeacherUseCase);
  container.bind("GetClassOverviewUseCase").to(GetClassOverviewUseCase);
  container.bind("GetGroupOverviewUseCase").to(GetGroupOverviewUseCase);
  container.bind("UpdateSmsSoldUseCase").to(UpdateSmsSoldUseCase);
  container.bind("GetAdminDashboardUseCase").to(GetAdminDashboardUseCase);
  container.bind("GetStudentProfileUseCase").to(GetStudentProfileUseCase);
  container.bind("GetTeacherProfileUsecase").to(GetTeacherProfileUsecase);
  container.bind("UpdateAdminUseCase").to(UpdateAdminUseCase);
  container.bind("UpdateStudentUseCase").to(UpdateStudentUseCase);
  container.bind("UpdateParentUseCase").to(UpdateParentUseCase);
  container.bind("UpdateTeacherUseCase").to(UpdateTeacherUseCase);
  container.bind("SwitchToUserUseCase").to(SwitchToUserUseCase);
  container.bind("ResendInvitationUseCase").to(ResendInvitationUseCase);
  container.bind("SwitchStudentsClassUseCase").to(SwitchStudentsClassUseCase);
  container.bind("ListStudentsUseCase").to(ListStudentsUseCase);
}