export const enum GetSubjectsOfClassByAdminTranslationKeysEnum {
  GET_SUBJECTS_OF_CLASS_BY_ADMIN_RESPONSE = "GET_SUBJECTS_OF_CLASS_BY_ADMIN_RESPONSE",
  TEACHER_NOT_FOUND = "TEACHER_NOT_FOUND",
  TEACHER_NOT_INCLUDED_IN_CLASS = "TEACHER_NOT_INCLUDED_IN_CLASS",
  CLASS_NOT_FOUND = "CLASS_NOT_FOUND",
}
