import { MessageAttachment } from "./../feature/messages/domain/messageAttachment.entity";
import { Message } from "./../feature/messages/domain/message.entity";
import { Conversation } from "./../feature/messages/domain/conversation.entity";
import { ICounterSchema } from "../core/newId/CounterModel";
import { Supplier } from "../feature/supplier/supplier.entity";
import { IComment } from "./schema/announcement/comment.schema";
import { IFeed } from "./schema/announcement/feed.schema";
import { IPost } from "./schema/announcement/post.schema";
import { IReaction } from "./schema/announcement/reaction.schema";
import { IInvoice } from "./schema/finance/Invoice.schema";
import { IBankCheck } from "./schema/finance/bankCheck.schema";
import { IExpense } from "./schema/finance/expense.schema";
import { IPaymentConfiguration } from "./schema/finance/paymentConfiguration.schema";
import { IPaymentTemplate } from "./schema/finance/paymentTemplate.schema";
import { IService } from "./schema/finance/service.schema";
import { ITeacherPaymentConfiguration } from "./schema/finance/teacherPaymentConfiguration.schema";
import { ITeacherPaymentHistory } from "./schema/finance/teacherPaymentHistory.schema";
import { ITransaction } from "./schema/finance/transaction.schema";
import { INotification } from "./schema/notification/notification.schema";
import { INotificationSettings } from "./schema/notification/notificationSettings.schema";
import { IClassroom } from "./schema/pedagogy/Campus/classroom.schema";
import { IExamType } from "./schema/pedagogy/Performance/examType.schema";
import { IHomework } from "./schema/pedagogy/Performance/homework.schema";
import { IInteraction } from "./schema/pedagogy/Performance/interaction.schema";
import { IIssue } from "./schema/pedagogy/Performance/issue.schema";
import { IIssueReason } from "./schema/pedagogy/Performance/issueReason.schema";
import { IObservation } from "./schema/pedagogy/Performance/observation.schema";
import { IObservationReason } from "./schema/pedagogy/Performance/observationReason.schema";
import { IStudentProfile } from "./schema/pedagogy/Profile/studentProfile.schema";
import { ITeacherProfile } from "./schema/pedagogy/Profile/teacherProfile.schema";
import { IClass } from "./schema/pedagogy/class/class.schema";
import { IClassType } from "./schema/pedagogy/class/classType.schema";
import { IClassGroup } from "./schema/pedagogy/class/classGroup.schema";
import { ISession } from "./schema/pedagogy/session/session.schema";
import { ISessionType } from "./schema/pedagogy/session/sessionType.schema";
import { IWeeklySession } from "./schema/pedagogy/session/weeklySession.schema";
import { IHoliday } from "./schema/pedagogy/structure/holiday.schema";
import { ILevel } from "./schema/pedagogy/structure/level.schema";
import { ISchoolYear } from "./schema/pedagogy/structure/schoolYear.schema";
import { ISection } from "./schema/pedagogy/structure/section.schema";
import { ISubLevel } from "./schema/pedagogy/structure/subLevel.schema";
import { ITerm } from "./schema/pedagogy/structure/term.schema";
import { ISubSubjectType } from "./schema/pedagogy/subject/subSubjectType.schema";
import { ISubjectType } from "./schema/pedagogy/subject/subjectType.schema";
import { IAdmin } from "./schema/users/admin.schema";
import { IParent } from "./schema/users/parent.schema";
import { IStudent } from "./schema/users/student.schema";
import { ITeacher } from "./schema/users/teacher.schema";
import { ICentralUser } from "./schema/users/user.central.schema";
import { IVerificationCode } from "./schema/users/verificationCode.schema";
import { Diploma } from "../feature/diploma/diploma.entity";
import { Group } from "../feature/groupManagement/domains/group.entity";
import { GroupType } from "../feature/groupManagement/domains/groupType.entity";

export type entityInterfaces = {
  admin: IAdmin;
  teacher: ITeacher;
  parent: IParent;
  student: IStudent;
  schoolYear: ISchoolYear;
  classroom: IClassroom;
  class: IClass;
  level: ILevel;
  term: ITerm;
  subLevel: ISubLevel;
  section: ISection;
  subSubjectType: ISubSubjectType;
  subjectType: ISubjectType;
  classType: IClassType;
  examType: IExamType;
  observationReason: IObservationReason;
  observation: IObservation;
  studentProfile: IStudentProfile;
  teacherProfile: ITeacherProfile;
  sessionType: ISessionType;
  classGroup: IClassGroup;
  holiday: IHoliday;
  weeklySession: IWeeklySession;
  session: ISession;
  invoice: IInvoice;
  bankCheck: IBankCheck;
  service: IService;
  paymentConfiguration: IPaymentConfiguration;
  paymentTemplate: IPaymentTemplate;
  homework: IHomework;
  verificationCode: IVerificationCode;
  notification: INotification;
  expense: IExpense;
  transaction: ITransaction;
  notificationSettings: INotificationSettings;
  counter: ICounterSchema;
  teacherPaymentHistory: ITeacherPaymentHistory;
  teacherPaymentConfiguration: ITeacherPaymentConfiguration;
  issue: IIssue;
  issueReason: IIssueReason;
  interaction: IInteraction;
  feed: IFeed;
  post: IPost;
  reaction: IReaction;
  comment: IComment;
  supplier: Supplier;
  diploma: Diploma;
  conversation: Conversation;
  message: Message;
  messageAttachment: MessageAttachment;
  group: Group;
  groupType: GroupType;
};

export type centralEntityInterface = {
  parent: ICentralUser;
  admin: ICentralUser;
  teacher: ICentralUser;
  student: ICentralUser;
};
